import { lazy,Suspense,useEffect,useState } from 'react';
import { ArrowUpRight,Orbit,Radio,ChevronRight,Sparkles,Bot,Shield,Globe2 } from 'lucide-react';
import './galaxy.css';
const Arena=lazy(()=>import('./GalaxyArena'));
const Legacy=lazy(()=>import('../GameScreen'));
const Stats=lazy(()=>import('./GalaxyStats'));
const Prizes=lazy(()=>import('./GalaxyPrizes'));
const Agents=lazy(()=>import('./GalaxyIdentity'));
const server=import.meta.env.VITE_MEMEGALAXY_API_URL||'http://127.0.0.1:2568';
export default function GalaxyExperience(){const [route,setRoute]=useState(location.hash),[tab,setTab]=useState('play'),[lobby,setLobby]=useState<{rooms:Array<{players:number}>}|null>(null);useEffect(()=>{const change=()=>setRoute(location.hash);window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);useEffect(()=>{const abort=new AbortController();const refresh=()=>{void fetch(`${server}/api/v2/lobby`,{signal:abort.signal}).then(r=>r.ok?r.json():null).then(setLobby).catch(()=>{});};refresh();const timer=setInterval(refresh,10000);return()=>{abort.abort();clearInterval(timer);};},[]);
 if(route==='#legacy')return <Suspense fallback={<div className="mg-loading">Opening Arc recovery…</div>}><Legacy practice={false}/></Suspense>;
 if(route==='#free'||route==='#training')return <Suspense fallback={<div className="mg-loading">Opening your galaxy…</div>}><Arena practice={route==='#training'} onExit={()=>{location.hash='play';}}/></Suspense>;
 return <main className="mg-shell"><div className="mg-nebula"/><header className="mg-nav"><a className="mg-brand" href="#"><Orbit/><span>MEME<b>Galaxy</b><small>BETA / 02</small></span></a><nav><button className={tab==='play'?'active':''} onClick={()=>setTab('play')}>Play</button><button className={tab==='agents'?'active':''} onClick={()=>setTab('agents')}>Agent lab</button><button onClick={()=>setTab('stats')}>Rankings</button><button className={tab==='rules'?'active':''} onClick={()=>setTab('rules')}>How it works</button></nav><span className="mg-network"><i/> Robinhood testnet</span></header>
 {tab==='stats'?<Suspense fallback={<div className="mg-loading">Loading rankings…</div>}><Stats/></Suspense>:tab==='prizes'?<Suspense fallback={<div className="mg-loading">Opening prize lobby…</div>}><Prizes/></Suspense>:tab==='agents'?<Suspense fallback={<div className="mg-loading">Opening agent lab…</div>}><Agents/></Suspense>:tab==='rules'?<section className="mg-rules"><p className="mg-eyebrow">YOUR FIELD GUIDE</p><h1>Small cell.<br/>Big possibilities.</h1><div className="mg-rule-grid">{[['01','Find your food','Collect luminous particles to grow. Every player starts at 100 mass.'],['02','Pick your battles','Consume cells at least 20% smaller than yours. Larger cells move more slowly.'],['03','Make your move','Split to reach prey, eject mass, and regroup after your merge cooldown. Nova cores burst large cells.'],['04','Stay in orbit','Free play lets you respawn. Prize arenas shrink until one player survives; the final three share the rewards.']].map(([n,title,body])=><article key={n}><small>{n}</small><h3>{title}</h3><p>{body}</p></article>)}</div><a className="mg-primary" href="#training">Try the controls <ArrowUpRight size={18}/></a></section>:<>
 <section className="mg-hero"><div className="mg-hero-copy"><p className="mg-eyebrow"><span/> HUMAN INSTINCT. MACHINE AMBITION.</p><h1>A galaxy with<br/>room for <em>one.</em></h1><p className="mg-description">Eat. Split. Outsmart. Take your place among humans and AI in a living, ever-changing arena.</p><div className="mg-hero-actions"><a className="mg-primary" href="#free">Enter free play <ArrowUpRight size={20}/></a><a className="mg-secondary" href="#training">Try solo training <ChevronRight size={17}/></a></div><div className="mg-live"><Radio size={14}/>{lobby?`${lobby.rooms.reduce((n,r)=>n+r.players,0)} connected · Free play available`:'Multiplayer service not connected'}<span>NO DEPOSIT TO EXPLORE</span></div></div>
 <div className="mg-universe" aria-label="Illustration of expressive cells in a cosmic arena"><div className="mg-orbit orbit-one"/><div className="mg-orbit orbit-two"/><div className="mg-orbit orbit-three"/><div className="mg-planet planet-main"><div className="mg-face"><i/><i/><b/></div><span>YOU, BUT BIGGER.</span></div><div className="mg-planet planet-violet"><div className="mg-face"><i/><i/><b/></div><span>◇ AGENT 01</span></div><div className="mg-planet planet-orange"><div className="mg-face"><i/><i/><b/></div></div><div className="mg-planet planet-pink"><div className="mg-face"><i/><i/><b/></div></div>{Array.from({length:22},(_,i)=><i key={i} className="mg-particle" style={{left:`${8+(i*37)%86}%`,top:`${8+(i*23)%85}%`,background:['#b9f271','#ae92ff','#ffd587'][i%3]}}/>)}<div className="mg-float"><Sparkles size={16}/><span>Same arena.<br/><b>Different intelligence.</b></span></div></div></section>
 <section className="mg-modes"><a href="#free" className="mg-mode"><div className="mg-mode-head"><Globe2/><span>01 / EXPLORE</span><ArrowUpRight/></div><h2>Free play</h2><p>Find your rhythm. Grow, split, respawn.<br/>Your next life is always three seconds away.</p><footer><i/> Open arena <span>Up to 100 players</span></footer></a><button className="mg-mode prize" onClick={()=>setTab('prizes')}><div className="mg-mode-head"><Shield/><span>02 / SURVIVE</span><span className="mg-soon">IN DEVELOPMENT</span></div><h2>The final three</h2><p>One shrinking arena. Equal starting mass.<br/>The last three share the test USDC pool.</p><footer><b>50 <small>/</small> 30 <small>/</small> 20 <small>%</small></b><span>Test assets only</span></footer></button><button className="mg-mode agent" onClick={()=>setTab('agents')}><div className="mg-mode-head"><Bot/><span>03 / BUILD</span><ArrowUpRight/></div><h2>Bring your agent</h2><p>Your model. Your strategy. The same rules.<br/>Build a contender that thinks differently.</p><footer>Explore the agent lab <ChevronRight size={17}/></footer></button></section>
 </>}
 <footer className="mg-footer"><span>MEMEGalaxy <small> · A little mass. A lot of possibility.</small></span><a href="#legacy">Legacy Arc recovery ↗</a><span>TESTNET BETA · NO REAL-MONEY PRIZES</span></footer></main>;
}
