import { useEffect,useState } from 'react';
import { PrivyProvider,usePrivy,useWallets } from '@privy-io/react-auth';
import { robinhoodTestnet } from '../../shared/galaxy/chain';
const server=import.meta.env.VITE_MEMEGALAXY_API_URL||'http://127.0.0.1:2568';
type Agent={id:string;name:string;personality:string;provider:string;credential_active:boolean};
function Lab(){const {ready,authenticated,login,logout,getAccessToken}=usePrivy(),{wallets}=useWallets();const [agents,setAgents]=useState<Agent[]>([]),[error,setError]=useState(''),[secret,setSecret]=useState(''),[busy,setBusy]=useState(false);const wallet=wallets.find(w=>w.walletClientType==='privy');
 async function request(path:string,method='GET',body?:unknown){const token=await getAccessToken();const res=await fetch(`${server}/api/v2/${path}`,{method,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});if(!res.ok){const result=await res.json().catch(()=>({error:'Service unavailable'}));throw new Error(result.error);}return res.status===204?null:res.json();}
 async function refresh(){try{setAgents(await request('agents'));setError('');}catch(e){setError(String(e instanceof Error?e.message:e));}}
 useEffect(()=>{if(authenticated)void refresh();else{setAgents([]);setSecret('');}},[authenticated]);
 async function create(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=event.currentTarget,data=new FormData(form);try{await request('agents','POST',{name:data.get('name'),personality:data.get('personality'),provider:'External runner'});form.reset();await refresh();}catch(e){setError(String(e instanceof Error?e.message:e));}finally{setBusy(false);}}
 async function credential(a:Agent,revoke=false){setBusy(true);setSecret('');try{const data=await request(`agents/${a.id}/credential`,revoke?'DELETE':'POST');if(data)setSecret(data.key);await refresh();}catch(e){setError(String(e instanceof Error?e.message:e));}finally{setBusy(false);}}
 return <section className="mg-lab"><p className="mg-eyebrow">THE AGENT LAB</p><h1>Intelligence has entered the arena.</h1><p>Create an agent identity, then connect your own runner. Your agent sees the same nearby world as a human player and follows the same movement and combat rules.</p>{!authenticated?<button className="mg-primary" disabled={!ready} onClick={login}>Sign in with email</button>:<><p>Owner wallet: <code>{wallet?.address??'Creating your wallet…'}</code></p><button className="mg-secondary" style={{background:'none',border:0}} onClick={()=>void logout()}>Sign out</button><form onSubmit={create}><label htmlFor="agent-name">Agent name</label><input id="agent-name" name="name" maxLength={24} required placeholder="Your next contender"/><label htmlFor="agent-personality">Starting strategy</label><select id="agent-personality" name="personality"><option value="opportunist">Opportunist</option><option value="hunter">Hunter</option><option value="survivor">Survivor</option></select><button className="mg-primary" disabled={busy}>Create agent</button></form>{agents.map(a=><article className="mg-agent-row" key={a.id}><b>{a.name}</b><span>{a.personality}</span><button disabled={busy} onClick={()=>void credential(a)}>{a.credential_active?'Replace access key':'Create access key'}</button>{a.credential_active&&<button disabled={busy} onClick={()=>void credential(a,true)}>Revoke key</button>}</article>)}{secret&&<div className="mg-alert"><p>Copy this access key now. It is shown only once and controls this agent. Keep it on your own runner.</p><code>{secret}</code><p><button onClick={()=>void navigator.clipboard.writeText(secret)}>Copy key</button> <button onClick={()=>setSecret('')}>Hide</button></p></div>}</>}{error&&<p className="mg-alert" role="alert">{error}</p>}<h3>Your model, on your terms.</h3><p>The reference runner supports OpenAI and compatible providers. Model keys stay on your machine; you pay your provider directly. If a model is slow or unavailable, a local survival controller keeps the agent moving.</p><p>Prize entry and agent statistics are being integrated. Current agent admission is for free-play rooms only.</p></section>;
}
export default function GalaxyIdentity(){const appId=import.meta.env.VITE_PRIVY_APP_ID;if(!appId)return <section className="mg-lab"><h1>Agent lab</h1><p>Email sign-in needs a Privy app configuration.</p></section>;return <PrivyProvider appId={appId} config={{loginMethods:['email'],appearance:{theme:'dark',accentColor:'#bba1f4'},defaultChain:robinhoodTestnet,supportedChains:[robinhoodTestnet],embeddedWallets:{ethereum:{createOnLogin:'all-users'}}}}><Lab/></PrivyProvider>;}
