import {useEffect,useState} from 'react';
import {createPublicClient,createWalletClient,custom,http,encodeFunctionData,formatUnits,type Address} from 'viem';
import {arcTestnet,escrowAbi} from '../../shared/chain';
import {useGalaxySession} from './GalaxySession';
import {PageHeading,Notice,Badge} from './GalaxyUi';
const rpc=createPublicClient({chain:arcTestnet,transport:http()});
const address=import.meta.env.VITE_ESCROW_ADDRESS as Address|undefined;
type Entry={id:bigint;amount:bigint;reward:bigint;arena:bigint;tokensClaimed:boolean;usdcClaimed:boolean;status:number;deadline:number};
export default function GalaxyLegacyRecovery(){const {wallet,connect}=useGalaxySession(),[entries,setEntries]=useState<Entry[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){if(!wallet||!address)return;const count=await rpc.readContract({address,abi:escrowAbi,functionName:'currentEpoch'}),found:Entry[]=[];for(let id=1n;id<=count;id++){const [e,p]=await Promise.all([rpc.readContract({address,abi:escrowAbi,functionName:'entryInfo',args:[id,wallet.address]}),rpc.readContract({address,abi:escrowAbi,functionName:'epochInfo',args:[id]})]);if(e[0]>0n&&(!e[3]||!e[4]))found.push({id,amount:e[0],arena:e[1],reward:e[2],tokensClaimed:e[3],usdcClaimed:e[4],status:Number(p[0]),deadline:Number(p[2])});}setEntries(found);}
 useEffect(()=>{void refresh().catch(e=>setMessage(e.message));},[wallet?.address]);
 async function recover(e:Entry,fn:'cancel'|'claimToken'|'claimUSDC'|'recoverArena'){if(!wallet||!address)return;setBusy(true);setMessage('');try{await wallet.switchChain(5042002);const client=createWalletClient({account:wallet.address,chain:arcTestnet,transport:custom(await wallet.getEthereumProvider())});const args=fn==='cancel'?[e.id]:fn==='recoverArena'?[e.id,e.arena]:[e.id,wallet.address];const hash=await client.sendTransaction({to:address,data:encodeFunctionData({abi:escrowAbi,functionName:fn,args} as any)});const receipt=await rpc.waitForTransactionReceipt({hash});if(receipt.status!=='success')throw Error('Transaction reverted');setMessage('Recovery confirmed: '+hash);await refresh();}catch(err){setMessage((err as Error).message);}finally{setBusy(false);}}
 return <><PageHeading eyebrow="ORIGINAL TEST ASSETS" title="Legacy Arc recovery." action={<a className="mg-button secondary" href="#lobby">Back to lobby</a>}>Connect the original wallet. Onchain withdrawals remain available without a Privy account.</PageHeading><Notice>Arc uses test USDC for network gas. New ZeroDev wallets do not contain assets held by your previous test wallets.</Notice>{!wallet?<button className="mg-button primary" onClick={connect}>Connect original wallet</button>:wallet.smart?<Notice>Use Change wallet in the account menu to select the original external wallet.</Notice>:!address?<Notice>Legacy escrow is not configured.</Notice>:entries.length?entries.map(e=><article className="mg-card" key={String(e.id)}><div className="mg-card-top"><h2>Epoch #{String(e.id)}</h2><Badge>ARC TESTNET</Badge></div><p>{formatUnits(e.amount,18)} DOMINATE · {formatUnits(e.reward,6)} test USDC reward</p><div className="mg-actions">{e.status===1?<button className="mg-button secondary" disabled={busy} onClick={()=>void recover(e,'cancel')}>Cancel and refund</button>:<>{e.status===2&&e.arena>0n&&Date.now()/1000>=e.deadline&&<button className="mg-button secondary" disabled={busy} onClick={()=>void recover(e,'recoverArena')}>Recover arena</button>}{!e.tokensClaimed&&<button className="mg-button primary" disabled={busy||e.status!==3&&Date.now()/1000<e.deadline} onClick={()=>void recover(e,'claimToken')}>Withdraw tokens</button>}{!e.usdcClaimed&&<button className="mg-button secondary" disabled={busy||e.status!==3&&Date.now()/1000<e.deadline} onClick={()=>void recover(e,'claimUSDC')}>Claim USDC</button>}</>}</div></article>):<Notice>No outstanding Arc entries found for this wallet.</Notice>}{message&&<Notice>{message}</Notice>}</>;
}
