import {useEffect,useState} from 'react';
import {createPublicClient,createWalletClient,http,custom,encodeFunctionData,formatUnits,type Address} from 'viem';
import {galaxyEscrowAbi,robinhoodTestnet} from '../../shared/galaxy/chain';
import {useGalaxySession} from './GalaxySession';
import {Badge,Notice} from './GalaxyUi';
const rpc=createPublicClient({chain:robinhoodTestnet,transport:http()});
type Claim={epoch:string;tokens:bigint;usdc:bigint;tokenClaimed:boolean;usdcClaimed:boolean;status:number;arena:bigint;arenaStatus:number;deadline:number};
export default function GalaxyClaims(){const {api,wallet,lobby}=useGalaxySession(),[claims,setClaims]=useState<Claim[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){if(!wallet||!lobby?.escrow)return;const mine=await api('prizes/me'),found:Claim[]=[];for(const batch of Array.from({length:Math.ceil(mine.entries.length/5)},(_,i)=>mine.entries.slice(i*5,i*5+5))){const rows=await Promise.all(batch.filter((e:any)=>e.wallet.toLowerCase()===wallet.address.toLowerCase()).map(async(e:any)=>{const [entry,epoch]=await Promise.all([rpc.readContract({address:lobby.escrow!,abi:galaxyEscrowAbi,functionName:'entryInfo',args:[BigInt(e.epoch),wallet.address as Address]}),rpc.readContract({address:lobby.escrow!,abi:galaxyEscrowAbi,functionName:'epochInfo',args:[BigInt(e.epoch)]})]);const arena=entry[1]>0n?await rpc.readContract({address:lobby.escrow!,abi:galaxyEscrowAbi,functionName:'arenaInfo',args:[BigInt(e.epoch),entry[1]]}):undefined;return {epoch:String(e.epoch),tokens:entry[0],arena:entry[1],arenaStatus:Number(arena?.status??0),usdc:arena?.status===3||Number(epoch[0])===3&&epoch[4]===0n?1_000_000n:entry[2],tokenClaimed:entry[3],usdcClaimed:entry[4],status:Number(epoch[0]),deadline:Number(epoch[2])};}));found.push(...rows.filter(r=>r.tokens>0n&&(!r.tokenClaimed||!r.usdcClaimed)));}setClaims(found);}
 useEffect(()=>{void refresh().catch(e=>setMessage(e.message));},[wallet?.address,lobby?.escrow,api]);
 async function claim(row:Claim,fn:'claimToken'|'claimUSDC'|'recoverArena'){if(!wallet||!lobby?.escrow)return;setBusy(true);try{const args=fn==='recoverArena'?[BigInt(row.epoch),row.arena]:[BigInt(row.epoch),wallet.address as Address];const hash=await wallet.send({to:lobby.escrow,data:encodeFunctionData({abi:galaxyEscrowAbi,functionName:fn,args} as any)});const receipt=await rpc.waitForTransactionReceipt({hash});if(receipt.status!=='success')throw new Error('Transaction reverted');await api('prizes/transactions','POST',{hash}).catch(()=>{});setMessage('Claim confirmed. Your wallet shows the returned test assets.');await refresh();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 if(!claims.length&&!message)return null;return <article className="mg-card" style={{marginBottom:24}}><h2>Outstanding test assets</h2><p className="mg-inline-note">Claims remain available even after the next epoch opens. Your wallet confirms test-ETH network gas.</p>{claims.map(r=><div key={r.epoch} style={{padding:'16px 0',borderTop:'1px solid #ffffff12'}}><div className="mg-card-top"><b>Epoch #{r.epoch}</b><Badge tone={r.status===3?'lime':'violet'}>{r.status===3?'RESOLVED':'LOCKED'}</Badge></div><p>{!r.tokenClaimed&&formatUnits(r.tokens,18)+' MEMEGALAXY'} {!r.usdcClaimed&&' · '+formatUnits(r.usdc,6)+' test USDC'}</p><div className="mg-actions">{(r.status===3||Date.now()/1000>=r.deadline&&[2,3].includes(r.arenaStatus))&&!r.tokenClaimed&&<button className="mg-button secondary" disabled={busy} onClick={()=>void claim(r,'claimToken')}>Withdraw tokens</button>}{(r.status===3||[2,3].includes(r.arenaStatus))&&!r.usdcClaimed&&<button className="mg-button primary" disabled={busy} onClick={()=>void claim(r,'claimUSDC')}>Claim USDC</button>}{r.status===2&&r.arenaStatus===1&&r.arena>0n&&Date.now()/1000>=r.deadline&&<button className="mg-button danger" disabled={busy} onClick={()=>void claim(r,'recoverArena')}>Recover unresolved arena</button>}</div></div>)}{message&&<Notice>{message}</Notice>}</article>;
}