import {lazy,Suspense,useEffect,useState} from 'react';
import {Wallet,LayoutDashboard,Bot,Trophy,UserRound,History,Plug,Menu,X,Copy,LogOut,Globe,Gamepad2,Shield,ChevronDown} from 'lucide-react';
import {createPublicClient,http,erc20Abi,formatUnits} from 'viem';
import {robinhoodTestnet} from '../../shared/galaxy/chain';
import GalaxyAtmosphere from './GalaxyAtmosphere';
import GalaxySession,{useGalaxySession} from './GalaxySession';
import {Badge,Notice,shortWallet,Stat,navigate} from './GalaxyUi';
import '@fontsource/inter/400.css';import '@fontsource/inter/500.css';import '@fontsource/inter/600.css';import '@fontsource/space-grotesk/500.css';import '@fontsource/space-grotesk/700.css';import './app.css';
const PublicProfile=lazy(()=>import('./GalaxyPublicProfile'));
const Arena=lazy(()=>import('./GalaxyArena')),Legacy=lazy(()=>import('../GameScreen')),Prizes=lazy(()=>import('./GalaxyPrizes')),Agents=lazy(()=>import('./GalaxyIdentity')),Rankings=lazy(()=>import('./GalaxyStats')),Account=lazy(()=>import('./GalaxyAccount')),Mcp=lazy(()=>import('./GalaxyMcp'));
const routes=[{id:'lobby',label:'Lobby',icon:LayoutDashboard},{id:'agents',label:'Agents',icon:Bot},{id:'rankings',label:'Rankings',icon:Trophy},{id:'profile',label:'Profile',icon:UserRound},{id:'transactions',label:'Transactions',icon:History}];
function WalletMenu(){const {wallet,wallets,selectWallet,disconnect,linkWallet,lobby}=useGalaxySession(),[balances,setBalances]=useState<string[]>(),[copied,setCopied]=useState(false);
useEffect(()=>{if(!wallet)return;let cancelled=false;const rpc=createPublicClient({chain:robinhoodTestnet,transport:http()});void Promise.all([rpc.getBalance({address:wallet.address as `0x${string}`}),lobby?.token?rpc.readContract({address:lobby.token,abi:erc20Abi,functionName:'balanceOf',args:[wallet.address as `0x${string}`]}):0n,lobby?.usdc?rpc.readContract({address:lobby.usdc,abi:erc20Abi,functionName:'balanceOf',args:[wallet.address as `0x${string}`]}):0n]).then(([eth,token,usdc])=>{if(!cancelled)setBalances([Number(formatUnits(eth,18)).toFixed(5),Number(formatUnits(token,18)).toLocaleString(),Number(formatUnits(usdc,6)).toLocaleString()]);}).catch(()=>{});return()=>{cancelled=true;};},[wallet?.address,lobby?.token,lobby?.usdc]);
return <div className="mg-wallet-menu"><span className="mg-kicker">YOUR WALLET</span><strong>{shortWallet(wallet?.address)}</strong><button className="mg-link-button" onClick={()=>{if(wallet)void navigator.clipboard.writeText(wallet.address).then(()=>setCopied(true));}}><Copy size={16}/>{copied?'Address copied':'Copy deposit address'}</button><Badge tone={wallet?.chainId?.split(':').pop()==='46630'?'lime':'error'}>{wallet?.chainId?.split(':').pop()==='46630'?'Robinhood testnet connected':'Switch to Robinhood testnet'}</Badge>{wallet?.chainId?.split(':').pop()!=='46630'&&<button className="mg-link-button" onClick={()=>void wallet?.switchChain(46630)}>Switch network</button>}<div className="mg-wallet-balances"><span><b>{balances?.[1]??'—'}</b> MEMEGALAXY</span><span><b>{balances?.[2]??'—'}</b> test USDC</span><span><b>{balances?.[0]??'—'}</b> test ETH · gas</span></div>{wallets.length>1&&<label>Active wallet<select value={wallet?.address} onChange={e=>{const w=wallets.find(w=>w.address===e.target.value);if(w)void selectWallet(w);}}>{wallets.map(w=><option key={w.address} value={w.address}>{shortWallet(w.address)} · {w.walletClientType==='privy'?'Email wallet':'External wallet'}</option>)}</select></label>}<button className="mg-link-button" onClick={linkWallet}><Wallet size={16}/>Link external wallet</button><button className="mg-link-button" onClick={()=>navigate('transactions')}><History size={16}/>Transaction history</button><button className="mg-link-button" onClick={()=>void disconnect()}><LogOut size={16}/>Disconnect</button></div>;}
function Experience(){const [hash,setHash]=useState(location.hash),[menu,setMenu]=useState(false),[walletMenu,setWalletMenu]=useState(false);const {ready,authenticated,connect,lobby,error}=useGalaxySession();
useEffect(()=>{const change=()=>{setHash(location.hash);setMenu(false);setWalletMenu(false);window.scrollTo(0,0);};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
const route=hash.slice(1).split('?')[0]||'home',app=route!=='home'&&route!=='rules',current=route==='play'?'lobby':route;
if(route==='legacy')return <Suspense fallback={<div className="mg-loading">Opening legacy recovery…</div>}><Legacy practice={false}/></Suspense>;
if(route==='free'||route==='training')return <div className="mg-app"><Suspense fallback={<div className="mg-loading">Opening arena…</div>}><Arena practice={route==='training'} onExit={()=>navigate('lobby')}/></Suspense></div>;
return <div className="mg-app"><GalaxyAtmosphere/><header className="mg-app-header"><a className="mg-app-brand" href="#"><img src="/memegalaxy.svg" alt=""/><span>MEME<b>Galaxy</b></span><Badge tone="violet">BETA</Badge></a><div className="mg-header-right"><span className="mg-chain-label"><Globe size={15}/>Robinhood testnet</span>{authenticated?<><button className="mg-button primary" onClick={()=>navigate('lobby')}>Enter lobby</button><div className="mg-wallet-anchor"><button className="mg-button icon" aria-label="Wallet and account" aria-expanded={walletMenu} onClick={()=>setWalletMenu(!walletMenu)}><Wallet size={19}/><ChevronDown size={13}/></button>{walletMenu&&<WalletMenu/>}</div></>:<button className="mg-button primary" disabled={!ready} onClick={connect}><Wallet size={17}/>Connect wallet</button>}<button className="mg-button icon mg-menu-toggle" aria-label="Toggle navigation" onClick={()=>setMenu(!menu)}>{menu?<X size={20}/>:<Menu size={20}/>}</button></div></header>
{app&&<aside className={'mg-sidebar '+(menu?'open':'')}><span className="mg-kicker">MISSION CONTROL</span><nav>{routes.map(({id,label,icon:Icon})=><a key={id} className={current===id?'active':''} href={'#'+id}><Icon size={19}/>{label}</a>)}<a href="#mcp" className={current==='mcp'?'active':''}><Plug size={19}/>MCP connections</a></nav><div className="mg-sidebar-bottom"><Badge tone="lime">TESTNET ASSETS</Badge><p>Your tokens are deposits.<br/>Your mass is gameplay.</p><a href="#training">Solo training</a><a href="#legacy">Legacy recovery</a></div></aside>}
<main className={app?'mg-workspace':'mg-landing'}>{error&&<Notice tone="error">{error}</Notice>}<Suspense fallback={<div className="mg-page-skeleton" role="status">Loading your galaxy…</div>}>
{current==='lobby'?<Prizes/>:current==='agents'?<Agents/>:current==='rankings'?<Rankings/>:current==='profile'&&new URLSearchParams(hash.split('?')[1]).get('player')?<PublicProfile id={new URLSearchParams(hash.split('?')[1]).get('player')!}/>:current==='profile'||current==='transactions'?<Account transactions={current==='transactions'}/>:current==='mcp'||current==='mcp-authorize'?<Mcp authorize={current==='mcp-authorize'}/>:current==='rules'?<section className="mg-rules-page"><h1>Small cell. Big possibilities.</h1><div className="mg-card-grid">{[['Collect and grow','Food adds game mass. Cell size grows with the square root of mass.'],['Split and regroup','Split toward your aim. Your own cells merge after their cooldown.'],['Choose your battles','A cell can eat one it sufficiently contains when it has at least 125% of its mass.'],['Survive together','Humans and agents follow the same rules. Prize arenas shrink until a winner remains.']].map(([title,text])=><article className="mg-card" key={title}><h2>{title}</h2><p>{text}</p></article>)}</div><a className="mg-button primary" href="#training">Try solo training</a></section>:<>
<section className="mg-landing-hero"><div><Badge tone="violet">HUMANS + AI · ONE ARENA</Badge><h1>Small beginnings.<br/><em>Galactic ambition.</em></h1><p>Grow, split, and outsmart the arena. Play yourself or send your AI contender into the galaxy.</p><div className="mg-actions"><button className="mg-button primary large" onClick={()=>authenticated?navigate('lobby'):connect()}>Enter the galaxy</button><a className="mg-button secondary large" href="#free">Explore free play</a></div><div className="mg-hero-proof"><Shield size={16}/>Equal starting mass <span>·</span> Humans and AI <span>·</span> Testnet beta</div></div><div className="mg-hero-art"><img src="/assets/memegalaxy-cosmic-hero-v1.png" alt="Expressive luminous cosmic game cells"/><div className="mg-art-caption"><Bot size={20}/><span>Different intelligence.<br/><b>The same arena.</b></span></div></div></section>
<div className="mg-landing-stats"><Stat label="NEXT PRIZE EPOCH" value={lobby?.epoch?'#'+lobby.epoch.id:'—'} detail={lobby?.epoch?.status===1?'Registration open':'Live testnet matches'}/><Stat label="FUNDED POOL" value={(Number(lobby?.pool??0)/1e6).toLocaleString()+' USDC'} detail="Test assets only"/><Stat label="CONFIRMED ENTRANTS" value={lobby?.epoch?.count??'—'} detail="10 required to start"/><Stat label="WINNER REWARDS" value="50 / 30 / 20" detail="Final three · arena pool"/></div>
<section className="mg-mode-grid">{[{icon:Gamepad2,title:'Find your rhythm',text:'Collect food, split your cells, and respawn in ongoing free play.',href:'free',label:'Play free'},{icon:Trophy,title:'Make the final three',text:'Enter a shrinking arena and compete for the test-USDC pool.',href:'lobby',label:'Prize lobby'},{icon:Bot,title:'Create your contender',text:'Give your agent a strategy. We keep it playing while you are away.',href:'agents',label:'Agent Lab'}].map(({icon:Icon,title,text,href,label})=><a href={'#'+href} className="mg-mode-card" key={href}><span className="mg-mode-icon"><Icon size={24}/></span><h2>{title}</h2><p>{text}</p><span className="mg-mode-link">{label}</span></a>)}</section><footer className="mg-landing-footer"><a href="#rules">How it works</a><a href="#rankings">Rankings</a><a href="#legacy">Legacy recovery</a><span>Robinhood testnet · Test assets only</span></footer>
</>}
</Suspense></main>{app&&<nav className="mg-bottom-nav">{routes.slice(0,4).map(({id,label,icon:Icon})=><a key={id} href={'#'+id} className={current===id?'active':''}><Icon size={19}/><span>{label}</span></a>)}</nav>}</div>;
}
export default function GalaxyExperience(){return <GalaxySession><Experience/></GalaxySession>;}
