import {lazy,Suspense,useEffect,useState} from 'react';
import {ShieldCheck,LogOut,Wallet,Menu,X,LayoutDashboard,Crosshair,Coins,Shirt,ListChecks,CheckCheck,History,Settings2} from 'lucide-react';
import GalaxySession,{useGalaxySession} from './GalaxySession';
import {Notice,Empty,Badge,shortWallet} from './GalaxyUi';
import '@fontsource/inter/400.css';import '@fontsource/inter/500.css';import '@fontsource/inter/600.css';import '@fontsource/space-grotesk/500.css';import '@fontsource/space-grotesk/700.css';
import './app.css';import './cosmic.css';import './admin.css';
const Admin=lazy(()=>import('./GalaxyAdmin'));
const sections=[{id:'overview',title:'Overview',icon:LayoutDashboard},{id:'drops',title:'Stock Hunt',icon:Crosshair},{id:'assets',title:'Reward assets',icon:Coins},{id:'skins',title:'Skin catalog',icon:Shirt},{id:'tasks',title:'Tasks',icon:ListChecks},{id:'reviews',title:'Verification queue',icon:CheckCheck},{id:'credits',title:'GUSD adjustments',icon:Coins},{id:'retirement',title:'Retirement rates',icon:Settings2},{id:'audit',title:'Audit history',icon:History}];
function Portal(){
 const {authenticated,connect,disconnect,wallet,api,ready}=useGalaxySession();
 const [access,setAccess]=useState<'checking'|'allowed'|'denied'>('checking'),[error,setError]=useState(''),[revision,setRevision]=useState(0),[section,setSection]=useState(location.hash.slice(1)||'overview'),[menu,setMenu]=useState(false);
 useEffect(()=>{const change=()=>{setSection(location.hash.slice(1)||'overview');setMenu(false);window.scrollTo(0,0);};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
 useEffect(()=>{setAccess('checking');setError('');if(!authenticated)return;const abort=new AbortController();void api('admin/economy','GET',undefined,abort.signal).then(()=>{if(!abort.signal.aborted)setAccess('allowed');}).catch(e=>{if(!abort.signal.aborted){setAccess('denied');setError(e.status===403?'This wallet is not authorized to administer MEMEGalaxy.':e.message);}});return()=>abort.abort();},[authenticated,api,wallet?.address,revision]);
 const active=sections.some(s=>s.id===section)?section:'overview';
 return <div className="mg-app mg-redesign mg-admin-portal"><header className="mg-app-header"><a className="mg-app-brand" href="#overview"><img src="/memegalaxy.svg" alt=""/><span>MEMEGalaxy</span><Badge>ADMIN</Badge></a><div className="mg-header-right"><span className="mg-admin-private"><ShieldCheck size={16}/>Private operations</span>{authenticated?<><span className="mg-admin-address">{shortWallet(wallet?.address)}</span><button className="mg-button secondary" onClick={()=>void disconnect()}><LogOut size={16}/>Disconnect</button></>:<button className="mg-button primary" disabled={!ready} onClick={connect}><Wallet size={16}/>Connect admin wallet</button>}{authenticated&&access==='allowed'&&<button className="mg-button icon mg-menu-toggle" aria-expanded={menu} aria-label="Admin navigation" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button>}</div></header>
 {!authenticated||access!=='allowed'?<main className="mg-admin-gate"><ShieldCheck size={40}/><span className="mg-eyebrow">MEMEGALAXY OPERATIONS</span><h1>Your galaxy.<br/>Under control.</h1><p>This private workspace is reserved for approved operators. Connect the allowlisted external wallet to continue.</p>{!authenticated?<button className="mg-button primary" disabled={!ready} onClick={connect}>Connect admin wallet</button>:access==='checking'?<Notice>Verifying administrator permissions…</Notice>:<><Notice tone="error">{error}</Notice><button className="mg-button secondary" onClick={()=>setRevision(n=>n+1)}>Check access again</button></>}<small>Robinhood testnet · No private keys are requested or stored by this panel.</small></main>:<><aside className={'mg-sidebar '+(menu?'open':'')}><span className="mg-kicker">OPERATIONS</span><nav>{sections.map(({id,title,icon:Icon})=><a key={id} href={'#'+id} className={active===id?'active':''} aria-current={active===id?'page':undefined}><Icon size={18}/>{title}</a>)}</nav><div className="mg-sidebar-bottom"><Badge>TESTNET ONLY</Badge><p>Every write is authenticated.<br/>Changes are recorded in the audit log.</p><a href="https://memegalaxy.usamahabduljalil21.chatgpt.site/" target="_blank" rel="noreferrer">Open player app</a></div></aside><main className="mg-workspace"><Suspense fallback={<Notice>Loading administration…</Notice>}><Admin key={wallet?.address} section={active}/></Suspense></main></>}
 </div>;
}
export default function GalaxyAdminPortal(){return <GalaxySession><Portal/></GalaxySession>;}
