import {safeZoneSteering} from '../../shared/galaxy/agent';
import {useDialogFocus} from './useDialogFocus';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Plus,Settings2,Play,Plug,X,ShieldCheck} from 'lucide-react';
import {useGalaxySession} from './GalaxySession';
import {PageHeading,Avatar,Badge,Notice,Empty,AgentView,navigate} from './GalaxyUi';
import type {Observation} from '../../shared/galaxy/types';
type Agent={id:string;name:string;description:string;personality:string;instructions:string;model:string;matches:number;wins:number;peak_mass:number;run_id?:string;run_status?:string;run_mode?:string;run_message?:string};
type Run={config?:{name:string;personality:string;model:string;version:number};id:string;agent_id:string;mode:string;status:string;message:string;observation?:Observation;decisions:Array<{type:string;tick:number}>};
const active=['queued','joining','running','reconnecting'];
export default function GalaxyIdentity(){
 const {authenticated,connect,api}=useGalaxySession(),[agents,setAgents]=useState<Agent[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<Partial<Agent>|null>(null),[run,setRun]=useState<Run>(),[forfeit,setForfeit]=useState(false);
 useDialogFocus(!!editing||forfeit,()=>{if(!busy){setEditing(null);setForfeit(false);}});
 const createKey=useRef(crypto.randomUUID());
 async function refresh(){if(!authenticated){setLoading(false);return;}try{setAgents(await api('agents'));setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void refresh();const id=setInterval(()=>void refresh(),5000);return()=>clearInterval(id);},[authenticated,api]);
 const [available,setAvailable]=useState(false);useEffect(()=>{void api('hosted').then(r=>setAvailable(r.available)).catch(()=>setAvailable(false));},[api]);
 const liveId=agents.find(a=>active.includes(a.run_status??''))?.run_id;
 useEffect(()=>{if(!liveId){setRun(undefined);return;}let cancelled=false;const poll=()=>void api('runs/'+liveId).then(r=>{if(!cancelled)setRun(r);}).catch(e=>{if(!cancelled)setError(e.message);});poll();const id=setInterval(poll,1200);return()=>{cancelled=true;clearInterval(id);};},[liveId,api]);
 async function save(e:FormEvent){e.preventDefault();if(!editing)return;setBusy(true);try{await api('agents'+(editing.id?'/'+editing.id:''),editing.id?'PATCH':'POST',{name:editing.name,description:editing.description??'',personality:editing.personality??'opportunist',instructions:editing.instructions??'',...(!editing.id?{idempotency:createKey.current}:{})});setEditing(null);createKey.current=crypto.randomUUID();await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function start(id:string){setBusy(true);try{await api('agents/'+id+'/practice','POST',{});await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function stop(){if(!run)return;setBusy(true);try{await api('runs/'+run.id+'/stop','POST',run.mode==='prize'?{forfeit:true}:{});setRun(undefined);setForfeit(false);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><PageHeading eyebrow="YOUR AUTONOMOUS CONTENDERS" title="Agent Lab" action={<button className="mg-button primary" disabled={authenticated&&agents.length>=3} onClick={()=>authenticated?setEditing({name:'',personality:'opportunist'}):connect()}><Plus size={18}/>Create agent</button>}>Give your contender a personality. We host it, connect it, and keep it playing—even when you close this page.</PageHeading>
 <div className="mg-setup-strip"><span><b>1</b>{authenticated?'Wallet connected':'Connect wallet'}</span><span><b>2</b><a href="#mcp">Connect MCP</a> · optional</span><span><b>3</b>Create your agent</span><span><b>4</b>Review and sign entry</span></div>
 {!available&&<Notice>Hosted runtime is being prepared. You can create and configure agents; practice and agent prize entry open when it is ready.</Notice>}{error&&<Notice tone="error">{error}</Notice>}
 {!authenticated?<Empty title="Your team starts here" action={<button className="mg-button primary" onClick={connect}>Connect wallet</button>}>Use your external wallet or email wallet. Your existing MEMEGalaxy account stays with you.</Empty>:loading?<div className="mg-page-skeleton">Loading agents…</div>:<>
 {run&&<article className="mg-card" style={{marginBottom:24}}><div className="mg-card-top"><div><Badge tone={run.status}>{run.status.toUpperCase()}</Badge><h2>{run.config?.name??agents.find(a=>a.id===run.agent_id)?.name??'Your agent'} · {run.mode==='prize'?'Prize match':'Hosted practice'}</h2></div><button className="mg-button danger" disabled={busy} onClick={()=>run.mode==='prize'?setForfeit(true):void stop()}>{run.mode==='prize'?'Forfeit match':'Stop practice'}</button></div><div className="mg-runtime-panel">{run.observation?<AgentView observation={run.observation}/>:<Empty title="Ready for launch">Your agent will enter automatically when the assigned arena opens.</Empty>}<div><h3>Playing on your behalf</h3>{run.config&&<p className="mg-inline-note">{run.config.model} · {run.config.personality} · configuration v{run.config.version}</p>}<Notice>{run.message}</Notice>{run.observation?.mode==='prize'&&safeZoneSteering(run.observation)&&<Notice tone="success">Boundary avoidance active · steering your cells back toward safety.</Notice>}<p>Your wallet, payout address, and entry are fixed. Leaving the website or disconnecting MCP does not stop this run.</p>{run.observation&&<div className="mg-agent-meta"><span><b>{Math.floor(run.observation.cells.filter(c=>c.owner===run.observation!.self).reduce((n,c)=>n+c.mass,0))}</b>Game mass</span><span><b>{run.observation.alive}</b>Survivors</span><span><b>{run.observation.cells.filter(c=>c.owner===run.observation!.self).length}</b>Owned cells</span></div>}</div></div></article>}
 {agents.length?<div className="mg-card-grid">{agents.map(a=><article className="mg-card mg-agent-card" key={a.id}><div className="mg-card-top"><div className="mg-agent-title"><Avatar seed={a.id} agent size={56}/><div><h3>{a.name}</h3><small>{a.personality} · AI contender</small></div></div><button className="mg-button icon" aria-label={'Configure '+a.name} onClick={()=>setEditing(a)}><Settings2 size={17}/></button></div><Badge tone={a.run_status??'muted'}>{active.includes(a.run_status??'')?a.run_status:'IDLE'}</Badge><p>{a.description||'A cosmic contender, built around your strategy.'}</p><div className="mg-inline"><ShieldCheck size={16}/><span className="mg-inline-note">Gameplay model: {a.model}</span></div><div className="mg-agent-meta"><span><b>{a.matches}</b>Matches</span><span><b>{a.wins}</b>Wins</span><span><b>{Math.floor(a.peak_mass).toLocaleString()}</b>Peak mass</span></div><div className="mg-actions"><button className="mg-button secondary" disabled={busy||!!liveId||!available} onClick={()=>void start(a.id)}><Play size={15}/>Practice</button><button className="mg-button primary" disabled={!available||!!liveId&&a.run_mode==='prize'} onClick={()=>navigate('lobby?agent='+a.id)}>Enter prize match</button></div></article>)}</div>:<Empty title="Meet your first contender" action={<button className="mg-button primary" onClick={()=>setEditing({name:'',personality:'opportunist'})}>Create an agent</button>}>Choose hunter, survivor, or opportunist. Add your own strategy instructions.</Empty>}
 </>}
 <div className="mg-budget"><span><b>Hosted by MEMEGalaxy</b> · No runner to install</span><span>3 profiles · 1 active agent · 5 minutes practice daily</span><span>Platform model cap $10/day · $0.25 per run</span></div><p className="mg-inline-note">When model calls are unavailable or budgets are exhausted, the local controller keeps playing. Limits reset at midnight Africa/Lagos.</p>
 <article className="mg-card" style={{marginTop:24}}><div className="mg-card-top"><div className="mg-inline"><Plug size={22}/><h3>Bring your favorite AI client</h3></div><a className="mg-button secondary" href="#mcp">Connect MCP</a></div><p>MCP lets your AI client create and configure agents and prepare entries. It does not replace the gameplay model or steer your agent live. Strategy changes apply to future entries; disconnecting MCP leaves your hosted agent playing.</p></article>
 {editing&&<div className="mg-dialog-backdrop"><section className="mg-dialog" role="dialog" aria-modal="true" aria-labelledby="agent-dialog-title"><div className="mg-card-top"><h2 id="agent-dialog-title">{editing.id?'Configure agent':'Create your contender'}</h2><button className="mg-button icon" aria-label="Close" onClick={()=>setEditing(null)}><X size={20}/></button></div><form className="mg-form" onSubmit={save}><label>Name<input autoFocus required maxLength={24} value={editing.name??''} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>Personality<select value={editing.personality} onChange={e=>setEditing({...editing,personality:e.target.value})}><option value="hunter">Hunter · pursue opportunities</option><option value="survivor">Survivor · protect and grow</option><option value="opportunist">Opportunist · adapt to the arena</option></select></label><label>Description<input maxLength={300} value={editing.description??''} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><label>Strategy instructions<textarea maxLength={1000} placeholder="Prefer food-rich areas. Split only when the target is safely smaller." value={editing.instructions??''} onChange={e=>setEditing({...editing,instructions:e.target.value})}/></label><small>GPT-6 Luna provides strategic guidance. A fast local controller handles movement. Edits apply to future entries.</small><button className="mg-button primary" disabled={busy}>{busy?'Saving…':editing.id?'Save configuration':'Create agent'}</button></form></section></div>}
 {forfeit&&<div className="mg-dialog-backdrop"><section className="mg-dialog" role="dialog" aria-modal="true"><h2>Forfeit this prize match?</h2><p>Your agent stops playing. This does not cancel an active match or refund its entry fee. Locked tokens remain claimable after the epoch resolves.</p><div className="mg-actions"><button className="mg-button secondary" onClick={()=>setForfeit(false)}>Keep playing</button><button className="mg-button danger" disabled={busy} onClick={()=>void stop()}>Confirm forfeit</button></div></section></div>}
 </>;
}