import type { ReactNode } from 'react';
import { Bot,UserRound,Orbit } from 'lucide-react';
import type { Observation } from '../../shared/galaxy/types';
import { radius } from '../../shared/galaxy/rules';
export function PageHeading({eyebrow,title,children,action}:{eyebrow:string;title:string;children?:ReactNode;action?:ReactNode}){return <div className="mg-page-heading"><div className="mg-heading-orbit" aria-hidden="true"><img src="/assets/memegalaxy-cosmic-hero-v1.png" alt=""/></div><div className="mg-heading-copy"><span className="mg-kicker">{eyebrow}</span><h1>{title}</h1>{children&&<p>{children}</p>}</div>{action}</div>;}
export function Stat({label,value,detail}:{label:string;value:ReactNode;detail?:ReactNode}){return <div className="mg-stat"><span>{label}</span><strong>{value}</strong>{detail&&<small>{detail}</small>}</div>;}
export function Notice({children,tone='info'}:{children:ReactNode;tone?:'info'|'error'|'success'}){return <div className={'mg-notice '+tone} role={tone==='error'?'alert':'status'}>{children}</div>;}
export function Empty({title,children,action}:{title:string;children?:ReactNode;action?:ReactNode}){return <div className="mg-empty"><Orbit size={32}/><h3>{title}</h3><p>{children}</p>{action}</div>;}
export function Avatar({seed,agent=false,size=48}:{seed:string;agent?:boolean;size?:number}){const colors=['#c7ef77','#a78bfa','#72d6e7','#f2b078','#ec8eba'],n=[...seed].reduce((v,c)=>v+c.charCodeAt(0),0);return <span className="mg-avatar" style={{width:size,height:size,background:colors[n%colors.length]+'22',color:colors[n%colors.length]}}>{agent?<svg width={size*.72} height={size*.72} viewBox="0 0 64 64" aria-hidden="true"><circle cx="32" cy="32" r="25" fill="currentColor" fillOpacity=".2" stroke="currentColor" strokeWidth="2"/><ellipse cx="23" cy="29" rx="5" ry="7" fill="currentColor"/><ellipse cx="41" cy="29" rx="5" ry="7" fill="currentColor"/><path d="M24 41Q32 49 40 41" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><path d="M10 11L15 7M49 7L54 11" stroke="currentColor" strokeWidth="2"/></svg>:<UserRound size={size*.45}/>}</span>;}
export function Badge({children,tone='muted'}:{children:ReactNode;tone?:string}){return <span className={'mg-badge '+tone}>{children}</span>;}
export function AgentView({observation:o}:{observation:Observation}){const scale=280/(o.viewport.half*2),x=(v:number)=>140+(v-o.viewport.x)*scale,y=(v:number)=>140+(v-o.viewport.y)*scale;return <svg className="mg-agent-preview" viewBox="0 0 280 280" role="img" aria-label="Your agent's live visible arena"><rect width="280" height="280" fill="#0c1324"/><defs><pattern id="agent-grid" width="28" height="28" patternUnits="userSpaceOnUse"><path d="M 28 0 L 0 0 0 28" fill="none" stroke="#ffffff" strokeOpacity=".05"/></pattern></defs><rect width="280" height="280" fill="url(#agent-grid)"/>{o.food.map(f=><circle key={f.id} cx={x(f.x)} cy={y(f.y)} r="2" fill="#d4ef86"/>)}<rect x={x(-o.safeHalf)} y={y(-o.safeHalf)} width={o.safeHalf*2*scale} height={o.safeHalf*2*scale} fill="none" stroke="#ec8eba" strokeWidth="2" strokeDasharray="6 4"/>{o.objects.map(v=><circle key={v.id} cx={x(v.x)} cy={y(v.y)} r={Math.max(4,45*scale)} fill="#75d9bb33" stroke="#75d9bb" strokeDasharray="3 2"/>)}{o.cells.map(c=><circle key={c.id} cx={x(c.x)} cy={y(c.y)} r={Math.max(3,radius(c.mass)*scale)} fill={c.owner===o.self?'#c7ef77':'#a78bfa'} stroke={c.owner===o.self?'#fff':'#c4afff'} strokeWidth={c.owner===o.self?2:1}/>)}<text x="14" y="264" fill="#c2cbe0" fontSize="11">OWNED AGENT · VISIBLE STATE</text></svg>;}
export const shortWallet=(value?:string)=>value?`${value.slice(0,6)}…${value.slice(-4)}`:'Preparing wallet';
export const navigate=(route:string)=>{location.hash=route;};
