import {useEffect,useState} from 'react';
import {PageHeading,Empty} from './GalaxyUi';
const docs=[
 ['wallets','Wallets & sign-in','Connect an external Ethereum wallet or create/use a passkey wallet through ZeroDev. Email-code sign-in is temporarily paused while ZeroDev resolves its OTP service issue. One ownership message verifies sign-in without moving funds. Each wallet has its own profile; previous Privy test profiles are not migrated. New wallets start empty and use a wallet-prefix name until you edit Profile. Passkeys are scoped to this site’s domain, so a local-development passkey is separate from a production passkey.'],
 ['gas','Smart wallets & network gas','ZeroDev wallets can submit token approvals and prize registration together as one atomic bundle. Sponsorship depends on an active project gas policy on Robinhood testnet. If unavailable, the bundle fails safely. External wallets confirm individual transactions and pay test ETH gas. The 1 test USDC entry fee remains separate. Previous test assets stay with their original wallet; use Rewards or Legacy recovery to claim them.'],
 ['controls','Controls & movement','Steer with your mouse, WASD or arrow keys. On mobile, drag to steer. Press Space to split and E to eject mass, or use the touch buttons. Bigger cells move more slowly. Merge cooldown is 20 seconds plus 0.02 seconds per mass unit. Use the speaker button for sound and fold Galaxy Leaders to make more room.'],
 ['modes','Choose a game mode','Free Play is continuous online multiplayer with respawns. Solo Training runs locally with labeled bots and gives no rewards or achievements. Stock Hunt is human-only online multiplayer with rare test Stock Token rewards and respawns. Prize Matches lock a refundable MEMEGALAXY deposit and end with elimination.'],
 ['hunt','Stock Hunt','Enter without a fee or minimum population. You start with 100 mass and respawn three seconds after death. Rare drops normally appear every 3–7 minutes, last 60 seconds, and require half a second of contact. Spawn-protected players cannot collect. Confirmed rewards survive death. The initial limit is five pickups daily, resetting at midnight Africa/Lagos. One active session per owner and wallet.'],
 ['claims','Weekly Stock Token claims','Earnings collected Monday–Sunday unlock the following Monday at 00:00 Africa/Lagos, after the weekly allocation is confirmed onchain. This is a shared reset, not seven days from each pickup. Unclaimed rewards stay available. Claims use the wallet fixed when you entered; switching wallets never redirects past earnings. You pay testnet ETH gas. All assets are test assets.'],
 ['skins','Skins & bonuses','Common 1×, Rare 1.1×, Premium 1.25×, Veteran 1.5× and VIP 2× are the initial reward tiers. Equip one owned skin in the Wardrobe. A skin changes Stock Hunt pickup amounts only, not speed, combat, mass or USDC prize rewards. Your skin and bonus freeze when you enter Stock Hunt. Different skins unlock through achievements, GUSD purchases, or both.'],
 ['gusd','GalaxyUsd credits','GUSD is an in-app credit, not a dollar-backed asset, transferable token or cash balance. Earn it through approved tasks or configured token-retirement offers, and spend it on published skins. GUSD has no dollar peg and cannot be withdrawn. Each offer shows its exact credit amount.'],
 ['tasks','Tasks & verification','Opening a task link does not earn credits. Submit the requested proof. Supported linked Telegram membership is checked automatically when configured; other actions go to admin review. Rewards are limited by task dates, participant limits and available task budget. A task can reward an account and social identity only once.'],
 ['retirement','Retire MEMEGALAXY for GUSD','Review the token amount, GUSD credit, quote expiry and gas before signing. Retired tokens enter a contract with no withdrawal path and become permanently inaccessible. This does not reduce the token’s reported total supply. Credits arrive after chain confirmation. Rate changes affect future conversions; outdated quotes must be reviewed again.'],
 ['prizes','Prize registration & rollovers','Minimum refundable deposit: 1,000 MEMEGALAXY. Entry fee: 1 test USDC; network gas is separate. Every player starts with 100 game mass. Registration begins with a 20-minute window. Fewer than ten entrants roll over for five minutes without another charge. Underfunded windows retry after twenty minutes. Arena opening follows the required contract-visible randomness blocks.'],
 ['payouts','The final three','An epoch reserves 100–1,000 test USDC and divides it among balanced arenas by entrant count. Each arena’s final three receive 50%, 30%, and 20%. Arenas shrink until one winner remains. Deposited tokens return after the epoch resolves.'],
 ['funds','Your funds stay separate','Locked deposits are separate from game mass. Waiting cancellation refunds your deposit and entry fee; spent gas cannot be refunded. Entry fees stay escrowed until valid settlement. Unresolved arenas become recoverable two hours after their start. Claims and legacy recovery remain accessible when new entries pause.'],
 ['agents','Hosted agents & MCP','Agents use the same validated movement interface as humans. Hosted agents keep playing when you close the website. MCP manages profiles and prepares entries; it does not replace the gameplay model or steer live. Prize registration freezes the agent’s controller, wallet and configuration. Stock Hunt currently admits human players only.'],
];
export default function GalaxyDocs(){const [query,setQuery]=useState('');useEffect(()=>{const reveal=()=>{const section=new URLSearchParams(location.hash.split('?')[1]).get('section');if(section){setQuery('');requestAnimationFrame(()=>document.getElementById(section)?.scrollIntoView({block:'center'}));}};reveal();window.addEventListener('hashchange',reveal);return()=>window.removeEventListener('hashchange',reveal);},[]);const visible=docs.filter(d=>d.join(' ').toLowerCase().includes(query.toLowerCase()));return <><PageHeading eyebrow="FLIGHT MANUAL" title="Everything you need to play."/><label className="mg-doc-search">Search the guide<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try skins, claims, controls…"/></label><div className="mg-doc-grid">{visible.map(([id,title,text])=><article className="mg-card" key={id} id={id}><h2>{title}</h2><p>{text}</p></article>)}</div>{!visible.length&&<Empty title="No matching guide">Try another word.</Empty>}</>;}
