import {useEffect,useState} from 'react';
import {Crosshair,Trophy,Orbit,Gamepad2,ArrowUpRight} from 'lucide-react';
import {useGalaxySession} from './GalaxySession';
import {PageHeading,Badge,navigate,Notice} from './GalaxyUi';
import SkinPortrait from './SkinPortrait';
import GalaxyArena from './GalaxyArena';
export default function GalaxyLobby({hunt=false}:{hunt?:boolean}){const {authenticated,connect,api,lobby}=useGalaxySession(),[ticket,setTicket]=useState<any>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[now,setNow]=useState(Date.now()),[entry,setEntry]=useState<any>();useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t);},[]);useEffect(()=>{setEntry(undefined);if(!authenticated)return;let cancelled=false;const load=()=>void api('prizes/me').then(r=>{if(!cancelled)setEntry(r.entries.find((e:any)=>String(e.epoch)===String(lobby?.epoch?.id)&&e.confirmed));}).catch(()=>{});load();const t=setInterval(load,10000);return()=>{cancelled=true;clearInterval(t);};},[api,authenticated,lobby?.epoch?.id]);const remaining=Math.max(0,Math.ceil((lobby?.epoch?.deadline??0)-now/1000)),countdown=lobby?.epoch?.status===1?(remaining>0?Math.floor(remaining/60)+':'+String(remaining%60).padStart(2,'0'):'Opening soon'):lobby?.epoch?.status===2?'Match in progress':'Next epoch pending';
 async function join(){setError('');if(!authenticated){connect();return;}setBusy(true);try{setTicket(await api('hunt/admission','POST',{}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(ticket)return <GalaxyArena practice={false} admission={ticket} onExit={()=>{setTicket(undefined);navigate('lobby');}}/>;
 return <><PageHeading eyebrow="CHOOSE YOUR ORBIT" title={hunt?'The hunt is always on.':'Where will you play today?'} action={<a className="mg-button secondary" href="#docs">How to play</a>}/>{error&&<Notice tone="error">{error}</Notice>}<section className="mg-play-grid">
 <article className="mg-play-card hunt"><div className="mg-card-top"><Badge tone="lime">STOCK HUNT · NEW</Badge><Crosshair/></div><div className="mg-play-art"><SkinPortrait skin="solar-fox" size={150}/><span className="mg-stock-orb">TSLA</span><span className="mg-stock-orb second">AMZN</span></div><h2>Hunt. Grow. Collect.</h2><p>Rare test Stock Tokens. Endless second chances.</p><button className="mg-button primary" disabled={busy} onClick={()=>void join()}>{busy?'Joining arena…':'Enter Stock Hunt'}<ArrowUpRight size={18}/></button><small>Free entry · Humans · Weekly claims</small></article>
 <article className="mg-play-card prize"><div className="mg-card-top"><Badge tone="violet">PRIZE MATCH</Badge><Trophy/></div><div className="mg-play-art"><SkinPortrait skin="supernova" size={150}/></div><h2>Claim your place.</h2><p>{Number(lobby?.pool??0)/1e6} test USDC available · {lobby?.epoch?.count??0} entrants</p><Badge tone={entry?'lime':'violet'}>{entry?`Registered · ${entry.controller==='agent'?'AI agent':'Human'}`:countdown}</Badge><a className="mg-button secondary" href="#prizes">{entry?'View your entry':'Open prize lobby'}<ArrowUpRight size={18}/></a><small>Last three share the arena pool</small></article>
 <article className="mg-play-card free"><Orbit size={25}/><SkinPortrait skin="orbit-frog" size={90}/><h2>Free Play</h2><p>A living multiplayer arena.</p><a className="mg-button secondary" href="#free">Play online</a></article>
 <article className="mg-play-card training"><Gamepad2 size={25}/><SkinPortrait skin="comet-cat" size={90}/><h2>Solo Training</h2><p>Find your rhythm with local bots.</p><a className="mg-button secondary" href="#training">Start training</a></article>
 </section><div className="mg-quick-links"><a href="#wardrobe">Discover your next skin ↗</a><a href="#earn">Earn GUSD ↗</a><a href="#rewards">View weekly rewards ↗</a></div><p className="mg-inline-note">Robinhood Chain testnet · All reward assets are test assets.</p></>;
}
