import {lazy,Suspense,useEffect,useState} from 'react';
import {Wallet,LayoutDashboard,Bot,Trophy,UserRound,History,Plug,Menu,X,Copy,LogOut,Globe,Gamepad2,Shield,ChevronDown,Shirt,Coins,Gift,BookOpen,Settings} from 'lucide-react';
import {createPublicClient,http,erc20Abi,formatUnits} from 'viem';
import {robinhoodTestnet} from '../../shared/galaxy/chain';
import GalaxyAtmosphere from './GalaxyAtmosphere';
import GalaxyLanding from './GalaxyLanding';
import GalaxySession,{useGalaxySession} from './GalaxySession';
import {Badge,Notice,shortWallet,navigate} from './GalaxyUi';
import '@fontsource/inter/400.css';import '@fontsource/inter/500.css';import '@fontsource/inter/600.css';import '@fontsource/space-grotesk/500.css';import '@fontsource/space-grotesk/700.css';import './app.css';import './cosmic.css';
const Lobby=lazy(()=>import('./GalaxyLobby')),Docs=lazy(()=>import('./GalaxyDocs')),Admin=lazy(()=>import('./GalaxyAdmin')),Wardrobe=lazy(()=>import('./GalaxyEconomy').then(m=>({default:m.Wardrobe}))),Earn=lazy(()=>import('./GalaxyEconomy').then(m=>({default:m.Earn}))),Rewards=lazy(()=>import('./GalaxyEconomy').then(m=>({default:m.Rewards})));
const PublicProfile=lazy(()=>import('./GalaxyPublicProfile'));
const Arena=lazy(()=>import('./GalaxyArena')),Prizes=lazy(()=>import('./GalaxyPrizes')),Agents=lazy(()=>import('./GalaxyIdentity')),Rankings=lazy(()=>import('./GalaxyStats')),Account=lazy(()=>import('./GalaxyAccount')),Mcp=lazy(()=>import('./GalaxyMcp'));
const routes=[{id:'lobby',label:'Lobby',icon:LayoutDashboard},{id:'agents',label:'Agents',icon:Bot},{id:'rankings',label:'Rankings',icon:Trophy},{id:'profile',label:'Profile',icon:UserRound},{id:'wardrobe',label:'Wardrobe',icon:Shirt},{id:'earn',label:'Earn GUSD',icon:Coins},{id:'rewards',label:'Rewards',icon:Gift},{id:'transactions',label:'Transactions',icon:History},{id:'docs',label:'How to play',icon:BookOpen}];
function WalletMenu(){const {wallet,wallets,selectWallet,disconnect,linkWallet,lobby,playerName}=useGalaxySession(),[balances,setBalances]=useState<string[]>(),[copied,setCopied]=useState(false);
useEffect(()=>{if(!wallet)return;let cancelled=false;const rpc=createPublicClient({chain:robinhoodTestnet,transport:http()});void Promise.all([rpc.getBalance({address:wallet.address as `0x${string}`}),lobby?.token?rpc.readContract({address:lobby.token,abi:erc20Abi,functionName:'balanceOf',args:[wallet.address as `0x${string}`]}):0n,lobby?.usdc?rpc.readContract({address:lobby.usdc,abi:erc20Abi,functionName:'balanceOf',args:[wallet.address as `0x${string}`]}):0n]).then(([eth,token,usdc])=>{if(!cancelled)setBalances([Number(formatUnits(eth,18)).toFixed(5),Number(formatUnits(token,18)).toLocaleString(),Number(formatUnits(usdc,6)).toLocaleString()]);}).catch(()=>{});return()=>{cancelled=true;};},[wallet?.address,lobby?.token,lobby?.usdc]);
return <div className="mg-wallet-menu" id="mg-wallet-menu"><span className="mg-kicker">YOUR WALLET</span><strong>{playerName}</strong><small>{shortWallet(wallet?.address)}</small><button className="mg-link-button" onClick={()=>{if(wallet)void navigator.clipboard.writeText(wallet.address).then(()=>setCopied(true));}}><Copy size={16}/>{copied?'Address copied':'Copy deposit address'}</button><Badge tone={wallet?.chainId?.split(':').pop()==='46630'?'lime':'error'}>{wallet?.chainId?.split(':').pop()==='46630'?'Robinhood testnet connected':'Switch to Robinhood testnet'}</Badge>{wallet?.chainId?.split(':').pop()!=='46630'&&<button className="mg-link-button" onClick={()=>void wallet?.switchChain(46630)}>Switch network</button>}<div className="mg-wallet-balances"><span><b>{balances?.[1]??'—'}</b> MEMEGALAXY</span><span><b>{balances?.[2]??'—'}</b> test USDC</span><span><b>{balances?.[0]??'—'}</b> test ETH · gas</span></div>{wallets.length>1&&<label>Active wallet<select value={wallet?.address} onChange={e=>{const w=wallets.find(w=>w.address===e.target.value);if(w)void selectWallet(w);}}>{wallets.map(w=><option key={w.address} value={w.address}>{shortWallet(w.address)} · {w.walletClientType==='zerodev'?'ZeroDev smart wallet':'External wallet'}</option>)}</select></label>}<button className="mg-link-button" onClick={linkWallet}><Wallet size={16}/>Change wallet</button><button className="mg-link-button" onClick={()=>navigate('profile')}><UserRound size={16}/>Player profile</button><button className="mg-link-button" onClick={()=>navigate('transactions')}><History size={16}/>Transaction history</button><button className="mg-link-button" onClick={()=>void disconnect()}><LogOut size={16}/>Disconnect</button></div>;}
export function Experience(){const [hash,setHash]=useState(location.hash),[menu,setMenu]=useState(false),[walletMenu,setWalletMenu]=useState(false);const {ready,authenticated,connect,lobby,error,api,playerName}=useGalaxySession();const [isAdmin,setIsAdmin]=useState(false),[socialMessage,setSocialMessage]=useState('');useEffect(()=>{setIsAdmin(false);if(authenticated)void api('economy').then(e=>setIsAdmin(e.roles.includes('economy'))).catch(()=>{});},[authenticated,api]);
useEffect(()=>{const params=new URLSearchParams(location.search);if(!authenticated||!params.has('code')||!params.has('state'))return;const code=params.get('code')!,state=params.get('state')!;if(sessionStorage.getItem('mg-x-state')!==state)return;sessionStorage.removeItem('mg-x-state');history.replaceState(null,'',location.pathname+'#earn');setHash('#earn');void api('social/x/complete','POST',{code,state}).then(()=>setSocialMessage('X account connected. You can now submit supported tasks for verification.')).catch(e=>setSocialMessage('X connection failed: '+e.message));},[authenticated,api]);
useEffect(()=>{const change=()=>{setHash(location.hash);setMenu(false);setWalletMenu(false);window.scrollTo(0,0);};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape'){setMenu(false);setWalletMenu(false);}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[]);
useEffect(()=>{if(!menu)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous;};},[menu]);
const route=hash.slice(1).split('?')[0]||'home',app=route!=='home',current=route==='play'?'lobby':route;

if(route==='free'||route==='training')return <div className="mg-app mg-redesign"><Suspense fallback={<div className="mg-loading">Opening arena…</div>}><Arena practice={route==='training'} onExit={()=>navigate('lobby')}/></Suspense></div>;
return <div className={'mg-app mg-redesign '+(app?'mg-app-view':'mg-home-view')}><GalaxyAtmosphere/><a className="mg-skip" href="#main-content" onClick={e=>{e.preventDefault();document.getElementById('main-content')?.focus();}}>Skip to content</a><header className="mg-app-header"><a className="mg-app-brand" href="#"><img src="/memegalaxy.svg" alt=""/><span>MEME<b>Galaxy</b></span><Badge tone="violet">BETA</Badge></a><nav className="mg-header-nav" aria-label="Main navigation"><a href="#lobby">Play</a><a href="#agents">Agent Lab</a><a href="#rankings">Rankings</a><a href="#docs">Discover</a></nav><div className="mg-header-right"><span className="mg-chain-label"><Globe size={15}/>Robinhood testnet</span>{authenticated?<div className="mg-wallet-anchor"><button className="mg-button primary mg-account-button" aria-label={playerName+' · Wallet and account'} aria-expanded={walletMenu} aria-controls="mg-wallet-menu" onClick={()=>setWalletMenu(!walletMenu)}><UserRound size={18}/><span>{playerName}</span><ChevronDown size={14}/></button>{walletMenu&&<WalletMenu/>}</div>:<button className="mg-button primary" disabled={!ready} onClick={connect}><Wallet size={17}/>Connect wallet</button>}<button className="mg-button icon mg-menu-toggle" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X size={20}/>:<Menu size={20}/>}</button></div></header>
{!app&&menu&&<nav className="mg-home-mobile-nav" aria-label="Mobile navigation"><a href="#lobby">Play</a><a href="#agents">Agent Lab</a><a href="#rankings">Rankings</a><a href="#docs">How to play</a></nav>}{app&&<aside className={'mg-sidebar '+(menu?'open':'')}><span className="mg-kicker">MISSION CONTROL</span><nav>{routes.map(({id,label,icon:Icon},index)=><a data-section={index===0?'PLAY':index===4?'COLLECTION':undefined} aria-current={current===id?'page':undefined} key={id} className={current===id?'active':''} href={'#'+id}><Icon size={19}/>{label}</a>)}{isAdmin&&<a href="#admin"><Settings size={19}/>Economy admin</a>}<a href="#mcp" className={current==='mcp'?'active':''}><Plug size={19}/>MCP connections</a></nav><div className="mg-sidebar-bottom"><Badge tone="lime">TESTNET ASSETS</Badge><p>A little space to make<br/>a name for yourself.</p><a href="#training">Solo training</a></div></aside>}
<main tabIndex={-1} id="main-content" className={app?'mg-workspace':'mg-landing'}>{error&&<Notice tone="error">{error}</Notice>}{socialMessage&&<Notice>{socialMessage}</Notice>}<Suspense fallback={<div className="mg-page-skeleton" role="status">Loading your galaxy…</div>}>
{current==='lobby'||current==='hunt'?<Lobby hunt={current==='hunt'}/>:current==='prizes'?<Prizes/>:current==='wardrobe'?<Wardrobe/>:current==='earn'?<Earn/>:current==='rewards'?<Rewards/>:current==='admin'?<Admin/>:current==='docs'||current==='rules'?<Docs/>:current==='agents'?<Agents/>:current==='rankings'?<Rankings/>:current==='profile'&&new URLSearchParams(hash.split('?')[1]).get('player')?<PublicProfile id={new URLSearchParams(hash.split('?')[1]).get('player')!}/>:current==='profile'||current==='transactions'?<Account transactions={current==='transactions'}/>:current==='mcp'||current==='mcp-authorize'?<Mcp authorize={current==='mcp-authorize'}/>:<>
<GalaxyLanding/>
</>}
</Suspense></main>{app&&<nav className="mg-bottom-nav">{routes.slice(0,4).map(({id,label,icon:Icon})=><a key={id} href={'#'+id} className={current===id?'active':''}><Icon size={19}/><span>{label}</span></a>)}<button className="mg-more-button" onClick={()=>setMenu(!menu)} aria-expanded={menu}><Menu size={19}/><span>More</span></button></nav>}</div>;
}
export default function GalaxyExperience(){return <GalaxySession><Experience/></GalaxySession>;}
