import {lazy,Suspense,useEffect,useState} from 'react';
import {Crosshair,Trophy,Orbit,Gamepad2,Shirt,Coins,Gift,BookOpen} from 'lucide-react';
import {useGalaxySession} from './GalaxySession';
import {PageHeading,Badge,navigate,Notice} from './GalaxyUi';
import SkinPortrait from './SkinPortrait';
const GalaxyArena=lazy(()=>import('./GalaxyArena'));
export default function GalaxyLobby({hunt=false}:{hunt?:boolean}){
 const {authenticated,connect,api,lobby,playerName}=useGalaxySession(),[ticket,setTicket]=useState<any>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[now,setNow]=useState(Date.now()),[entry,setEntry]=useState<any>();
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t);},[]);
 useEffect(()=>{setEntry(undefined);if(!authenticated)return;let cancelled=false;const load=()=>void api('prizes/me').then(r=>{if(!cancelled)setEntry(r.entries.find((e:any)=>String(e.epoch)===String(lobby?.epoch?.id)&&e.confirmed));}).catch(()=>{});load();const t=setInterval(load,10000);return()=>{cancelled=true;clearInterval(t);};},[api,authenticated,lobby?.epoch?.id]);
 const remaining=Math.max(0,Math.ceil((lobby?.epoch?.deadline??0)-now/1000)),countdown=lobby?.epoch?.status===1?(remaining>0?Math.floor(remaining/60)+':'+String(remaining%60).padStart(2,'0'):'Opening soon'):lobby?.epoch?.status===2?'In progress':'Awaiting epoch';
 async function join(){setError('');if(!authenticated){connect();return;}setBusy(true);try{setTicket(await api('hunt/admission','POST',{}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(ticket)return <Suspense fallback={<Notice>Opening Stock Hunt…</Notice>}><GalaxyArena practice={false} admission={ticket} onExit={()=>{setTicket(undefined);navigate('lobby');}}/></Suspense>;
 return <><PageHeading eyebrow={authenticated?'WELCOME BACK, '+playerName:'YOUR NEXT ORBIT'} title={hunt?'The hunt is always on.':'Let’s make some space.'} action={<a className="mg-button secondary" href="#docs"><BookOpen size={16}/>How to play</a>}/>{error&&<Notice tone="error">{error}</Notice>}
 <div className="mg-lobby-label"><span>SELECT YOUR ARENA</span><span>01 — 04</span></div>
 <section className="mg-orbit-modes">
  <article className="mg-hunt-feature"><img className="mg-hunt-backdrop" src="/assets/memegalaxy-orbit-hero.webp" alt=""/><div className="mg-card-top"><Badge tone="lime"><Crosshair size={13}/> STOCK HUNT</Badge><span className="mg-mode-number">01</span></div><div className="mg-hunt-copy"><span className="mg-eyebrow">A LITTLE LUCK. A LOT OF INSTINCT.</span><h2>Find your<br/><em>next fortune.</em></h2><p>Hunt rare test Stock Tokens.<br/>Keep every find. Come back for more.</p><div className="mg-actions"><button className="mg-button primary" disabled={busy} onClick={()=>void join()}>{busy?'Joining arena…':'Enter Stock Hunt'}</button><a className="mg-text-link" href="#rewards">My rewards</a></div></div><div className="mg-mode-foot"><span>Free entry</span><span>Human players</span><span>Weekly claims</span></div></article>
  <article className="mg-prize-feature"><div className="mg-card-top"><Badge tone="violet"><Trophy size={13}/> PRIZE MATCHES</Badge><span className="mg-mode-number">02</span></div><span className="mg-eyebrow">THE LAST THREE TAKE THE STARS</span><h2>Make it count.</h2><div className="mg-prize-value">{lobby?Number(lobby.pool??0)/1e6:'—'}<span>test USDC pool</span></div><div className="mg-prize-details"><div><b>{countdown}</b><span>{lobby?.epoch?.status===1?'Registration closes in':'Epoch status'}</span></div><div><b>{lobby?.epoch?.count??'—'}<small> / 10 min</small></b><span>Confirmed entrants</span></div></div>{entry&&<Badge tone="lime">Registered · {entry.controller==='agent'?'AI agent':'Human'}</Badge>}<a className="mg-button secondary" href="#prizes">{entry?'View your entry':'Open prize lobby'}</a></article>
  <a className="mg-compact-mode" href="#free"><div className="mg-compact-icon"><Orbit size={26}/></div><div><span className="mg-eyebrow">03 / NO PRESSURE. JUST PLAY.</span><h2>Free Play</h2><p>One living arena. Endless second chances.</p></div><span className="mg-mode-chip">Play online</span></a>
  <a className="mg-compact-mode" href="#training"><div className="mg-compact-icon"><Gamepad2 size={26}/></div><div><span className="mg-eyebrow">04 / FIND YOUR RHYTHM</span><h2>Solo Training</h2><p>Perfect your moves with local bots.</p></div><span className="mg-mode-chip">Practice</span></a>
 </section>
 <div className="mg-lobby-label"><span>MAKE IT YOUR GALAXY</span></div><section className="mg-orbit-shortcuts"><a href="#wardrobe"><SkinPortrait skin="comet-cat" size={70}/><div><h3>Dress for the orbit.</h3><p>Skins with a little extra gravity.</p></div><Shirt size={18}/></a><a href="#earn"><Coins size={32}/><div><h3>A mission. A new look.</h3><p>Complete tasks. Earn GUSD.</p></div><Coins size={18}/></a><a href="#rewards"><Gift size={32}/><div><h3>Your finds, forever.</h3><p>Track and claim weekly rewards.</p></div><Gift size={18}/></a></section><p className="mg-inline-note mg-testnet-footnote">Robinhood Chain testnet · All financial rewards are test assets.</p>
 </>;
}
