import {useDialogFocus} from './useDialogFocus';
import { useEffect,useRef,useState } from 'react';
import {useGalaxySession} from './GalaxySession';
import {PageHeading,Stat,Notice,Badge,Empty,shortWallet} from './GalaxyUi';
import {Trophy,X} from 'lucide-react';
import { createPublicClient,createWalletClient,http,custom,encodeFunctionData,erc20Abi,formatUnits,parseAbi,type Address,type Hex } from 'viem';
import { robinhoodTestnet,galaxyEscrowAbi } from '../../shared/galaxy/chain';
import GalaxyArena from './GalaxyArena';

const legacyEscrows=[{address:'0x9abc7283af8bcb13b617ce8519fa74b3ba00da75' as Address,label:'Earlier testnet escrow'},{address:'0x109b0b74fd2417d210da573fd64f160e28aeb2d3' as Address,label:'Previous testnet escrow'}];
const rpc=createPublicClient({chain:robinhoodTestnet,transport:http()});
type Lobby={enabled:boolean;escrow?:Address;token?:Address;usdc?:Address;faucet?:Address;pool:string;timing?:{underfilledRolloverMinutes:number;randomness:string};epoch:null|{id:string;status:number;deadline:number;count:number;recovery:number}};
type LegacyEntry={escrow:Address;label:string;epoch:bigint;status:number;recovery:number;entry:readonly [bigint,bigint,bigint,boolean,boolean]};
function PrizeLobby(){const admissionAttempt=useRef(false);const {ready,authenticated,connect:login,api,wallet,playerName}=useGalaxySession();const [lobby,setLobby]=useState<Lobby>(),[amount,setAmount]=useState('1000'),[agents,setAgents]=useState<Array<{id:string;name:string}>>([]),[selected,setSelected]=useState('human'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[gas,setGas]=useState(''),[review,setReview]=useState<any>(),[entry,setEntry]=useState<readonly [bigint,bigint,bigint,boolean,boolean]>(),[legacyEntries,setLegacyEntries]=useState<LegacyEntry[]>([]),[history,setHistory]=useState<Array<{hash:string;kind:string;status:string}>>([]),[admission,setAdmission]=useState<{roomId:string;token:string}>(),[balances,setBalances]=useState(''),[myController,setMyController]=useState('human'),[now,setNow]=useState(Date.now());
 useDialogFocus(!!gas,()=>{if(!busy)setGas('');});
 async function refresh(){try{const l:Lobby=await api('prizes');setLobby(l);let myEntries:Array<{epoch:string;controller:string;confirmed:boolean}>=[];if(authenticated){setAgents(await api('agents'));const mine=await api('prizes/me');setHistory(mine.transactions);myEntries=mine.entries;setMyController(mine.entries.find((e:any)=>String(e.epoch)===l.epoch?.id&&e.confirmed)?.controller??'human');}if(wallet&&l.escrow&&l.epoch){const chainEntry=await rpc.readContract({address:l.escrow,abi:galaxyEscrowAbi,functionName:'entryInfo',args:[BigInt(l.epoch.id),wallet.address as Address]});setEntry(chainEntry);if(l.epoch.status===2&&chainEntry[0]>0n&&myEntries.some(e=>String(e.epoch)===l.epoch!.id&&e.controller==='human'&&e.confirmed)&&!admissionAttempt.current){admissionAttempt.current=true;try{setAdmission(await api('prizes/admission','POST',{epoch:l.epoch.id,agent:false}));}catch{admissionAttempt.current=false;}}}if(wallet){
 const found:LegacyEntry[]=[];
 for(const old of legacyEscrows){
  if(l.escrow?.toLowerCase()===old.address.toLowerCase())continue;
  try{
   const oldEpoch=await rpc.readContract({address:old.address,abi:galaxyEscrowAbi,functionName:'currentEpoch'});
   if(oldEpoch===0n)continue;
   const [info,oldEntry]=await Promise.all([
    rpc.readContract({address:old.address,abi:galaxyEscrowAbi,functionName:'epochInfo',args:[oldEpoch]}),
    rpc.readContract({address:old.address,abi:galaxyEscrowAbi,functionName:'entryInfo',args:[oldEpoch,wallet.address as Address]})
   ]);
   if(oldEntry[0]>0n&&(Number(info[0])===1||!oldEntry[3]||!oldEntry[4]))found.push({escrow:old.address,label:old.label,epoch:oldEpoch,status:Number(info[0]),recovery:Number(info[2]),entry:oldEntry});
  }catch{}
 }
 setLegacyEntries(found);
}else setLegacyEntries([]);if(wallet&&l.token&&l.usdc){const [token,usdc,eth]=await Promise.all([rpc.readContract({address:l.token,abi:erc20Abi,functionName:'balanceOf',args:[wallet.address as Address]}),rpc.readContract({address:l.usdc,abi:erc20Abi,functionName:'balanceOf',args:[wallet.address as Address]}),rpc.getBalance({address:wallet.address as Address})]);setBalances(`${Number(formatUnits(token,18)).toLocaleString()} MEMEGALAXY · ${formatUnits(usdc,6)} test USDC · ${Number(formatUnits(eth,18)).toFixed(5)} test ETH`);}}catch(e){setMessage(e instanceof Error?e.message:'Service unavailable');}}
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),10000);return()=>clearInterval(timer);},[authenticated,wallet?.address,api]);
 useEffect(()=>{admissionAttempt.current=false;setEntry(undefined);},[wallet?.address]);
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id);},[]);
 useEffect(()=>{if(!authenticated)return;const params=new URLSearchParams(location.hash.split('?')[1]);const id=params.get('agent');if(id)setSelected(id);const draft=params.get('draft');if(draft)void api('entry-drafts/'+draft).then(d=>{setSelected(d.agent_id);setAmount(d.deposit);setMessage('Entry prepared by MCP. Review the details and approve in your wallet.');}).catch(e=>setMessage(e.message));},[authenticated,api]);
 const remaining=Math.max(0,Math.ceil((lobby?.epoch?.deadline??0)-now/1000));
 async function send(to:Address,data:Hex){if(!wallet)throw new Error('Wallet is not ready');await wallet.switchChain(46630);const client=createWalletClient({account:wallet.address as Address,chain:robinhoodTestnet,transport:custom(await wallet.getEthereumProvider())});const hash=await client.sendTransaction({to,data});const receipt=await rpc.waitForTransactionReceipt({hash});if(receipt.status!=='success')throw new Error('Transaction reverted');if(to===lobby?.escrow)await api('prizes/transactions','POST',{hash}).catch(()=>{});return hash;}
 async function estimate(){if(!wallet||!lobby?.escrow||!lobby.token||!lobby.usdc)return;setBusy(true);setMessage('');try{const authorization=await api('prizes/authorize','POST',{deposit:amount,name:playerName,...(selected==='human'?{}:{agentId:selected})});const fee=await rpc.getGasPrice();setReview({...authorization,deposit:amount,agentId:selected});setGas(`About ${formatUnits(fee*450000n*12n/10n,18)} test ETH for approvals and entry (conservative estimate; your wallet shows the final quote).`);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function join(){if(!lobby?.epoch||!lobby.escrow||!lobby.token||!lobby.usdc||!wallet||!review)return;setBusy(true);try{if(wallet.address.toLowerCase()!==review.wallet||lobby.epoch.id!==review.epoch)throw new Error('Wallet or epoch changed. Close this review and prepare a new entry.');for(const [asset,value] of [[lobby.token,BigInt(review.amount)],[lobby.usdc,1000000n]] as const){const allowed=await rpc.readContract({address:asset,abi:erc20Abi,functionName:'allowance',args:[wallet.address as Address,lobby.escrow]});if(allowed<value){setMessage('Confirm the exact token allowance in your wallet.');await send(asset,encodeFunctionData({abi:erc20Abi,functionName:'approve',args:[lobby.escrow,value]}));}}const a=await api('prizes/authorize','POST',{deposit:review.deposit,name:review.name,...(review.agentId==='human'?{}:{agentId:review.agentId})});if(a.epoch!==review.epoch||a.controller!==review.controller||a.wallet!==review.wallet)throw new Error('Entry details changed. Prepare a new review.');setMessage('Confirm your testnet entry in your wallet.');await send(lobby.escrow,encodeFunctionData({abi:galaxyEscrowAbi,functionName:'register',args:[BigInt(a.epoch),a.userId,a.controller,BigInt(a.amount),BigInt(a.expiry),a.signature]}));setMessage('Entry confirmed. Your controller is fixed for this epoch.');setGas('');setReview(undefined);await refresh();}catch(e){setMessage(e instanceof Error?e.message:'Entry failed');}finally{setBusy(false);}}
 async function operate(fn:'cancel'|'claimToken'|'claimUSDC'|'recoverArena'){if(!lobby?.escrow||!lobby.epoch||!wallet)return;setBusy(true);try{const id=BigInt(lobby.epoch.id);const data=fn==='cancel'?encodeFunctionData({abi:galaxyEscrowAbi,functionName:fn,args:[id]}):fn==='recoverArena'?encodeFunctionData({abi:galaxyEscrowAbi,functionName:fn,args:[id,entry?.[1]??0n]}):encodeFunctionData({abi:galaxyEscrowAbi,functionName:fn,args:[id,wallet.address as Address]});await send(lobby.escrow,data);setMessage('Transaction confirmed.');await refresh();}catch(e){setMessage(e instanceof Error?e.message:'Transaction failed');}finally{setBusy(false);}}
 async function operateLegacy(previous:LegacyEntry,fn:'cancel'|'claimToken'|'claimUSDC'|'recoverArena'){
  if(!wallet)return;setBusy(true);
  try{
   const args=fn==='cancel'?[previous.epoch]:fn==='recoverArena'?[previous.epoch,previous.entry[1]]:[previous.epoch,wallet.address as Address];
   await send(previous.escrow,encodeFunctionData({abi:galaxyEscrowAbi,functionName:fn,args} as any));
   setMessage('Previous entry transaction confirmed.');await refresh();
  }catch(e){setMessage(e instanceof Error?e.message:'Previous entry transaction failed');}
  finally{setBusy(false);}
 }
 if(admission)return <GalaxyArena practice={false} admission={admission} onExit={()=>setAdmission(undefined)}/>;
 return <><PageHeading eyebrow="PRIZE MATCHES · TESTNET" title="One arena. Three winners." action={<a className="mg-button secondary" href="#docs?section=prizes">Rules & payouts ↗</a>}/>
 <div className="mg-two-column"><div className="mg-stack"><article className="mg-card mg-epoch-card"><div className="mg-card-top"><Badge tone="violet">{lobby?.epoch?'EPOCH '+lobby.epoch.id:'PRIZE EPOCH'}</Badge><Badge tone={lobby?.epoch?.status===2?'lime':'muted'}>{lobby?.epoch?.status===1?'REGISTRATION':lobby?.epoch?.status===2?'MATCH IN PROGRESS':'AWAITING NEXT EPOCH'}</Badge></div><div className="mg-countdown">{lobby?.epoch?.status===1?remaining>0?String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0'):'Launching…':lobby?.epoch?.status===2?'Arena live':'Next orbit'}</div><div className="mg-progress"><span style={{width:Math.min(100,(lobby?.epoch?.count??0)/10*100)+'%'}}/></div><div className="mg-card-top"><span>{lobby?.epoch?.count??0} confirmed entrants</span><span className="mg-inline-note">10 to start · 500 max</span></div><div className="mg-actions"><a className="mg-button secondary" href="#free">Explore free play</a><a className="mg-button secondary" href="#training">Solo training</a></div></article>
 <div className="mg-stat-grid"><Stat label="AVAILABLE PRIZE FUNDS" value={(lobby?Number(formatUnits(BigInt(lobby.pool),6)):0).toLocaleString()} detail="test USDC · 100 needed"/><Stat label="STARTING GAME MASS" value="100" detail="Equal for every entrant"/><Stat label="ENTRY FEE" value="1 USDC" detail="Test asset · gas separate"/></div>
 </div>
 <div className="mg-stack"><article className="mg-card"><div className="mg-card-top"><h2>{entry&&entry[0]>0n?'Your confirmed entry':'Choose your contender'}</h2><Badge tone="violet">TEST ASSETS</Badge></div>
 {!lobby?.enabled&&<Notice>New entries are currently paused. Cancellation, claims, and recovery remain available.</Notice>}
 {!authenticated?<Empty title="Connect to participate" action={<button className="mg-button primary" disabled={!ready} onClick={login}>Connect wallet</button>}>Use an external wallet or your email-created wallet.</Empty>:<>
 <div className="mg-review-line"><span>Payout wallet</span><b>{shortWallet(wallet?.address)}</b></div><p className="mg-inline-note">{balances||'Checking test-asset balances…'}</p>
 {lobby?.faucet&&<button className="mg-link-button" disabled={busy} onClick={()=>{setBusy(true);void send(lobby.faucet!,encodeFunctionData({abi:parseAbi(['function claim()']),functionName:'claim'})).then(()=>{setMessage('Test assets received. The faucet can be used once per day.');return refresh();}).catch(e=>setMessage(e.message)).finally(()=>setBusy(false));}}>Claim free test assets</button>}
 {entry&&entry[0]>0n?<><div className="mg-review-line"><span>Locked tokens</span><b>{formatUnits(entry[0],18)} MEMEGALAXY</b></div><div className="mg-review-line"><span>Controller</span><b>{myController==='agent'?'Hosted AI agent':'You · human'}</b></div><div className="mg-review-line"><span>Prize obligation</span><b>{formatUnits(entry[2],6)} test USDC</b></div><Notice>{myController==='agent'?'Your agent is queued automatically and stays active after this page closes. Track its state in Agent Lab.':'Your arena opens automatically when it is ready. Keep this page open to play.'}</Notice><div className="mg-actions">
 {lobby?.epoch?.status===1&&<button className="mg-button secondary" disabled={busy} onClick={()=>void operate('cancel')}>Cancel and refund</button>}
 {myController==='agent'?<a className="mg-button primary" href="#agents">View my agent</a>:lobby?.epoch?.status===2&&<button className="mg-button primary" disabled={busy} onClick={()=>void api('prizes/admission','POST',{epoch:lobby.epoch!.id,agent:false}).then(setAdmission).catch(e=>setMessage(e.message))}>Enter my arena</button>}
 {lobby?.epoch?.status===3&&!entry[3]&&<button className="mg-button secondary" disabled={busy} onClick={()=>void operate('claimToken')}>Withdraw tokens</button>}
 {lobby?.epoch?.status===3&&!entry[4]&&<button className="mg-button secondary" disabled={busy} onClick={()=>void operate('claimUSDC')}>Claim USDC</button>}
 {lobby?.epoch?.status===2&&Date.now()/1000>=lobby.epoch.recovery&&<button className="mg-button danger" disabled={busy} onClick={()=>void operate('recoverArena')}>Recover unresolved arena</button>}</div></>:<form className="mg-form" onSubmit={e=>{e.preventDefault();void estimate();}}><label>Controller<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="human">Play myself · human</option>{agents.map(a=><option value={a.id} key={a.id}>{a.name} · hosted AI</option>)}</select></label>{selected==='human'&&<a className="mg-inline-note" href="#profile">Edit your player name in Profile ↗</a>}<label>Refundable deposit<input required inputMode="decimal" pattern="[0-9]+(\\.[0-9]{1,18})?" value={amount} onChange={e=>{setAmount(e.target.value);setGas('');}}/></label><small>Minimum 1,000 MEMEGALAXY. Extra deposits give no gameplay advantage.</small><button className="mg-button primary" disabled={!lobby?.enabled||busy||!wallet||lobby.epoch?.status!==1||(lobby.epoch?.deadline??0)<=Date.now()/1000}>{busy?'Confirming…':'Review entry'}</button><a className="mg-inline-note" href="#agents">Create an AI contender in Agent Lab</a></form>}
 </>}</article></div></div>
 {legacyEntries.map(previous=><article className="mg-card" key={previous.escrow} style={{marginTop:24}}><h3>{previous.label}</h3><p>{formatUnits(previous.entry[0],18)} MEMEGALAXY locked · epoch {previous.epoch.toString()}</p><div className="mg-actions">{previous.status===1&&<button className="mg-button secondary" disabled={busy} onClick={()=>void operateLegacy(previous,'cancel')}>Cancel and refund</button>}{previous.status===2&&Date.now()/1000>=previous.recovery&&previous.entry[1]>0n&&<button className="mg-button secondary" disabled={busy} onClick={()=>void operateLegacy(previous,'recoverArena')}>Recover arena</button>}{previous.status===3&&!previous.entry[3]&&<button className="mg-button secondary" disabled={busy} onClick={()=>void operateLegacy(previous,'claimToken')}>Withdraw tokens</button>}{previous.status===3&&!previous.entry[4]&&<button className="mg-button secondary" disabled={busy} onClick={()=>void operateLegacy(previous,'claimUSDC')}>Claim USDC</button>}</div></article>)}
 {message&&<Notice>{message}</Notice>}
 {gas&&<div className="mg-dialog-backdrop"><section className="mg-dialog" role="dialog" aria-modal="true" aria-labelledby="entry-review"><div className="mg-card-top"><h2 id="entry-review">Review your entry</h2><button className="mg-button icon" aria-label="Close review" disabled={busy} onClick={()=>setGas('')}><X size={20}/></button></div><div className="mg-review-line"><span>Epoch</span><b>#{lobby?.epoch?.id}</b></div><div className="mg-review-line"><span>Controller</span><b>{review?.name} · {review?.config?'Hosted AI':'Human'}</b></div><div className="mg-review-line"><span>Refundable lock</span><b>{review?.deposit} MEMEGALAXY</b></div><div className="mg-review-line"><span>Entry fee</span><b>1 test USDC</b></div><div className="mg-review-line"><span>Payout wallet</span><b>{shortWallet(wallet?.address)}</b></div>{review?.config&&<><div className="mg-review-line"><span>Gameplay model</span><b>{review.config.model}</b></div><div className="mg-review-line"><span>Strategy</span><b>{review.config.personality} · v{review.config.version}</b></div><p className="mg-inline-note">{review.config.instructions||"Survive and grow"}</p></>}<p className="mg-inline-note">{gas}</p><Notice>Waiting cancellation returns the deposit and entry fee; spent gas is not refundable. Controller, strategy, and payout wallet are fixed at registration. Your wallet confirms the exact allowances, entry fee, and test-ETH gas.</Notice>{message&&<Notice>{message}</Notice>}<button className="mg-button primary" disabled={busy} onClick={()=>void join()}>{busy?'Waiting for wallet…':'Approve and enter'}</button></section></div>}
 </>;
}
export default function GalaxyPrizes(){return <PrizeLobby/>;}
