import {useEffect,useState} from 'react';
import {createWalletClient,custom,type Address,parseUnits,formatUnits} from 'viem';
import {robinhoodTestnet} from '../../shared/galaxy/chain';
import {retirementAbi} from '../../shared/galaxy/economy-chain';
import {useGalaxySession} from './GalaxySession';
import {useEconomyData} from './GalaxyEconomy';
import {PageHeading,Notice,Badge,Empty} from './GalaxyUi';
type DraftTask={title:string;instructions:string;platform:string;target:string;reward:number;budget:number;maxParticipants:number;startsAt:string;endsAt:string;enabled:boolean};
const initialTask:DraftTask={title:'',instructions:'',platform:'x',target:'',reward:0,budget:0,maxParticipants:100,startsAt:'',endsAt:'',enabled:false};
export default function GalaxyAdmin(){const {api,wallet,authenticated,connect}=useGalaxySession(),{data,error,busy,act}=useEconomyData('admin/economy'),[settings,setSettings]=useState<any>(),[task,setTask]=useState(initialTask),[message,setMessage]=useState(''),[asset,setAsset]=useState(''),[adjustment,setAdjustment]=useState({owner:'',delta:0,reason:'',idempotency:crypto.randomUUID()});useEffect(()=>{if(data)setSettings(structuredClone(data.config.settings));},[data]);
 const update=(key:string,value:unknown)=>setSettings((s:any)=>({...s,[key]:value}));const rate=(key:string,value:unknown)=>setSettings((s:any)=>({...s,retirement:{...s.retirement,[key]:value}}));
 async function save(){await api('admin/config','POST',settings);setMessage('Saved. Changed retirement rates also require onchain activation.');}
 async function activate(){if(!wallet||!data.retirement)throw Error('Connect the configured admin wallet and deploy the retirement contract first');await wallet.switchChain(46630);const client=createWalletClient({account:wallet.address as Address,chain:robinhoodTestnet,transport:custom(await wallet.getEthereumProvider())});await client.writeContract({address:data.retirement,abi:retirementAbi,functionName:'configure',args:[BigInt(data.config.settings.retirement.version),data.config.settings.retirement.enabled]});setMessage('Rate activation submitted. Quotes open once the onchain version matches.');}
 return <><PageHeading eyebrow="ECONOMY OPERATIONS" title="Control the next orbit."/>{error&&<Notice tone="error">{error}</Notice>}{message&&<Notice>{message}</Notice>}{!authenticated?<Empty title="Administrator sign-in required" action={<button className="mg-button primary" onClick={connect}>Connect wallet</button>}/>:!settings?<Empty title={error?"Economy access unavailable":"Loading authorized economy settings"}/>:<>
 <div className="mg-two-column"><form className="mg-card mg-form" onSubmit={e=>{e.preventDefault();void act(save);}}><h2>Stock Hunt drops</h2><label className="mg-check"><input type="checkbox" checked={settings.enabled} onChange={e=>update('enabled',e.target.checked)}/>Enable funded drops</label>{[['minInterval','Minimum interval (seconds)',30],['maxInterval','Maximum interval (seconds)',30],['lifetime','Drop lifetime (seconds)',10],['dailyLimit','Daily pickups per owner/wallet',1],['contactTicks','Required contact ticks (30 per second)',15]].map(([key,label,min])=><label key={key}>{label}<input type="number" min={min} required value={settings[key]} onChange={e=>update(String(key),Number(e.target.value))}/></label>)}<label>Base reward (test Stock Tokens)<input inputMode="decimal" required value={formatUnits(BigInt(settings.baseUnits),18)} onChange={e=>{try{update('baseUnits',parseUnits(e.target.value,18).toString());}catch{}}}/></label><button className="mg-button primary" disabled={busy}>Save future drop settings</button></form>
 <form className="mg-card mg-form" onSubmit={e=>{e.preventDefault();void act(save);}}><h2>MEMEGALAXY → GUSD</h2><label className="mg-check"><input type="checkbox" checked={settings.retirement.enabled} onChange={e=>rate('enabled',e.target.checked)}/>Enable configured retirement offers</label><label>MEMEGALAXY per conversion unit<input required inputMode="decimal" value={formatUnits(BigInt(settings.retirement.tokens),18)} onChange={e=>{try{rate('tokens',parseUnits(e.target.value,18).toString());}catch{}}}/></label><label>GUSD per conversion unit<input type="number" min="0" required value={settings.retirement.credits} onChange={e=>rate('credits',Number(e.target.value))}/></label><label>New rate version<input type="number" min="1" required value={settings.retirement.version} onChange={e=>rate('version',Number(e.target.value))}/></label><button className="mg-button primary" disabled={busy}>Save rate configuration</button><button type="button" className="mg-button secondary" disabled={busy||!data.retirement} onClick={()=>void act(activate)}>Activate saved version onchain</button><p className="mg-inline-note">A new rate version invalidates unsubmitted old quotes. Credited retirements stay fixed.</p></form></div>
 <article className="mg-card" style={{marginTop:24}}><h2>Funded test assets</h2><p className="mg-inline-note">Vault: {data.vault??'Not deployed'}</p><div className="mg-table-wrap"><table className="mg-table"><thead><tr><th>Asset</th><th>Vault balance</th><th>Reserved + earned</th><th>Available</th><th>Drops</th></tr></thead><tbody>{data.assets.map((a:any)=><tr key={a.address}><td>{a.symbol}<small>{a.address}</small></td><td>{formatUnits(BigInt(a.balance),a.decimals)}</td><td>{formatUnits(BigInt(a.reserved)+BigInt(a.obligations),a.decimals)}</td><td>{formatUnits(BigInt(a.balance)-BigInt(a.reserved)-BigInt(a.obligations),a.decimals)}</td><td><button className="mg-button secondary" disabled={busy} onClick={()=>void act(()=>api('admin/assets','POST',{address:a.address,enabled:!a.enabled}))}>{a.enabled?'Disable':'Enable'}</button></td></tr>)}</tbody></table></div><form className="mg-actions" onSubmit={e=>{e.preventDefault();void act(()=>api('admin/assets','POST',{address:asset,enabled:false}));}}><input aria-label="Additional verified test asset address" value={asset} onChange={e=>setAsset(e.target.value)} placeholder="0x… testnet asset" required/><button className="mg-button secondary" disabled={busy}>Verify and add asset</button></form></article>
 <h2>Skin catalog</h2><div className="mg-card-grid">{data.skins.map((s:any)=><SkinEditor key={s.id+':'+s.version} skin={s} busy={busy} save={v=>act(()=>api('admin/skins/'+s.id,'PATCH',v))}/>)}</div>
 <h2>Publish a task</h2><form className="mg-card mg-form" onSubmit={e=>{e.preventDefault();void act(async()=>{await api('admin/tasks','POST',{...task,startsAt:new Date(task.startsAt).toISOString(),endsAt:new Date(task.endsAt).toISOString()});setTask(initialTask);});}}><label>Title<input required value={task.title} maxLength={100} onChange={e=>setTask({...task,title:e.target.value})}/></label><label>Instructions<textarea required value={task.instructions} maxLength={2000} onChange={e=>setTask({...task,instructions:e.target.value})}/></label><label>Platform<select value={task.platform} onChange={e=>setTask({...task,platform:e.target.value})}><option value="x">X · manual review unless a verifier is configured</option><option value="telegram">Telegram membership</option><option value="other">Other · manual review</option></select></label><label>Task URL or Telegram chat ID<input required value={task.target} onChange={e=>setTask({...task,target:e.target.value})}/></label><div className="mg-filter-bar">{[['reward','Reward in GUSD'],['budget','Total GUSD budget'],['maxParticipants','Maximum participants']].map(([k,label])=><label key={k}>{label}<input required type="number" min="1" value={(task as any)[k]} onChange={e=>setTask({...task,[k]:Number(e.target.value)})}/></label>)}</div><label>Starts (your local time)<input type="datetime-local" required value={task.startsAt} onChange={e=>setTask({...task,startsAt:e.target.value})}/></label><label>Expires (your local time)<input type="datetime-local" required value={task.endsAt} onChange={e=>setTask({...task,endsAt:e.target.value})}/></label><label className="mg-check"><input type="checkbox" checked={task.enabled} onChange={e=>setTask({...task,enabled:e.target.checked})}/>Publish when scheduled</label><button className="mg-button primary" disabled={busy}>Create task</button></form>
 <h2>Task management</h2>{data.tasks.map((t:any)=><article className="mg-card mg-card-top" key={t.id}><div><h3>{t.title}</h3><span>{t.spent} / {t.budget} GUSD awarded</span></div><button className="mg-button secondary" disabled={busy} onClick={()=>void act(()=>api('admin/tasks/'+t.id,'PATCH',{enabled:!t.enabled}))}>{t.enabled?'Pause':'Enable'}</button></article>)}
 <h2>Verification queue</h2>{data.submissions.length?data.submissions.map((s:any)=><ReviewCard key={s.id} submission={s} busy={busy} review={(status,reason)=>act(()=>api('admin/reviews/'+s.id,'POST',{status,reason}))}/>):<Empty title="The review queue is clear"/>}
 <h2>Credit adjustment</h2><form className="mg-card mg-form" onSubmit={e=>{e.preventDefault();void act(async()=>{await api('admin/credits','POST',adjustment);setAdjustment({owner:'',delta:0,reason:'',idempotency:crypto.randomUUID()});});}}><label>Account identifier<input required maxLength={200} value={adjustment.owner} placeholder="Owner ID from the verification queue" onChange={e=>setAdjustment({...adjustment,owner:e.target.value})}/></label><label>GUSD adjustment<input required type="number" min="-1000000" max="1000000" value={adjustment.delta} onChange={e=>setAdjustment({...adjustment,delta:Number(e.target.value)})}/></label><label>Audit reason<input required minLength={5} maxLength={500} value={adjustment.reason} onChange={e=>setAdjustment({...adjustment,reason:e.target.value})}/></label><button className="mg-button secondary" disabled={busy||adjustment.delta===0}>Record adjustment</button></form>
 <details className="mg-card"><summary>Audit history</summary>{data.audit.map((a:any,i:number)=><div className="mg-review-line" key={i}><span>{a.action} · {a.subject}</span><small>{new Date(a.created_at).toLocaleString()}</small></div>)}</details></>}</>;}
function SkinEditor({skin,busy,save}:{skin:any;busy:boolean;save:(value:unknown)=>Promise<void>}){const [v,setV]=useState({price:skin.price===null?null:Number(skin.price),paid:skin.config.paid,published:skin.published,multiplier:skin.config.multiplier,mass:skin.config.mass,seconds:skin.config.seconds});return <form className="mg-card mg-form" onSubmit={e=>{e.preventDefault();void save(v);}}><h3>{skin.config.name}</h3><Badge>{skin.config.tier}</Badge><label className="mg-check"><input type="checkbox" checked={v.paid} onChange={e=>setV({...v,paid:e.target.checked})}/>GUSD purchase required</label><label>GUSD price (blank = unavailable)<input type="number" min="1" value={v.price??''} onChange={e=>setV({...v,price:e.target.value?Number(e.target.value):null})}/></label><label>Multiplier (basis points, 10,000 = 1×)<input type="number" min="10000" max="20000" required value={v.multiplier} onChange={e=>setV({...v,multiplier:Number(e.target.value)})}/></label><label>Required peak mass<input type="number" min="0" value={v.mass} onChange={e=>setV({...v,mass:Number(e.target.value)})}/></label><label>Required active seconds<input type="number" min="0" value={v.seconds} onChange={e=>setV({...v,seconds:Number(e.target.value)})}/></label><label className="mg-check"><input type="checkbox" checked={v.published} onChange={e=>setV({...v,published:e.target.checked})}/>Published</label><button className="mg-button secondary" disabled={busy}>Save future skin settings</button></form>;}
function ReviewCard({submission:s,busy,review}:{submission:any;busy:boolean;review:(status:string,reason:string)=>Promise<void>}){const [reason,setReason]=useState('');return <article className="mg-card mg-form"><h3>{s.title}</h3><p>{s.platform} · {s.identity}</p><small>Owner: {s.owner}</small><p style={{overflowWrap:'anywhere',whiteSpace:'pre-wrap'}}>{s.proof}</p><label>Verification reason<input required minLength={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="mg-actions"><button className="mg-button primary" disabled={busy||reason.length<3} onClick={()=>void review('approved',reason)}>Approve reward</button><button className="mg-button danger" disabled={busy||reason.length<3} onClick={()=>void review('rejected',reason)}>Reject proof</button></div></article>;}
