import {replay,type ReplayInput} from '../shared/galaxy/replay';
import {describe,it,expect} from 'vitest';
import {createWorld,tick,addPlayer,applyAction} from '../shared/galaxy/engine';
import {huntCollector,type HuntDrop} from '../shared/galaxy/hunt';
import {lagosDay,rewardWeek,pickupAmount,SKINS} from '../shared/galaxy/economy';
import {merkleTree,rewardLeaf} from '../shared/galaxy/economy-chain';
import {keccak256,concatHex,type Hex} from 'viem';
const entrant={id:'one',name:'One',controller:'human' as const};
const drop:HuntDrop={id:'drop',asset:'TSLA',symbol:'TSLA',x:0,y:0,expires:Date.now()+60000,version:1};
describe('Stock Hunt authoritative rules',()=>{
 it('allows one player, late join and respawn without ending or shrinking',()=>{const w=createWorld('hunt',4,[entrant]);w.cells=[];tick(w);for(let i=0;i<90;i++)tick(w);expect(w.players[0].alive).toBe(true);expect(w.cells[0].mass).toBe(100);addPlayer(w,{...entrant,id:'two'});for(let i=0;i<2000;i++)tick(w);expect(w.finished).toBe(false);expect(w.safeHalf).toBe(w.size/2);});
 it('requires sustained contact and excludes protection and disconnected players',()=>{const w=createWorld('hunt',4,[entrant]);const cell=w.cells[0];cell.x=0;cell.y=0;const contacts=new Map(),eligible=new Set(['one']);expect(huntCollector(w,drop,contacts,eligible)).toBeUndefined();w.tick=100;expect(huntCollector(w,drop,contacts,eligible)).toBeUndefined();w.tick=114;expect(huntCollector(w,drop,contacts,eligible)).toBeUndefined();w.tick=115;expect(huntCollector(w,drop,contacts,eligible)).toBe('one');w.players[0].disconnectedTick=115;expect(huntCollector(w,drop,contacts,eligible)).toBeUndefined();expect(contacts.size).toBe(0);});
 it('resets interrupted or changed-cell contact',()=>{const w=createWorld('hunt',4,[entrant]),contacts=new Map(),eligible=new Set(['one']);w.tick=100;w.cells[0].x=0;w.cells[0].y=0;huntCollector(w,drop,contacts,eligible);w.cells[0].id+=100;w.tick=115;expect(huntCollector(w,drop,contacts,eligible)).toBeUndefined();w.tick=130;expect(huntCollector(w,drop,contacts,eligible)).toBe('one');w.cells[0].x=900;huntCollector(w,drop,contacts,eligible);expect(contacts.size).toBe(0);});
 it('uses seeded ordering, never array order, for simultaneous contacts',()=>{const w=createWorld('hunt',4,[entrant,{...entrant,id:'two'}]);w.tick=100;w.cells.forEach(c=>{c.x=0;c.y=0;});const contacts=new Map(),eligible=new Set(['one','two']);huntCollector(w,drop,contacts,eligible);w.tick=115;const first=huntCollector(w,drop,contacts,eligible);w.players.reverse();expect(huntCollector(w,drop,contacts,eligible)).toBe(first);});
 it('does not admit agent or daily-ineligible cells to collection',()=>{const w=createWorld('hunt',4,[{...entrant,controller:'agent'}]);w.tick=100;w.cells[0].x=0;w.cells[0].y=0;const contacts=new Map();huntCollector(w,drop,contacts,new Set(['one']));expect(contacts.size).toBe(0);});
});
describe('Stock Hunt economics',()=>{
 it('groups weeks at midnight Monday Lagos and daily reset at 23 UTC',()=>{expect(rewardWeek(Date.parse('2026-10-01T12:00:00Z'))).toEqual({start:Date.parse('2026-09-27T23:00:00Z')/1000,unlock:Date.parse('2026-10-04T23:00:00Z')/1000});expect(rewardWeek(Date.parse('2026-10-04T23:00:00Z')).start).toBe(Date.parse('2026-10-04T23:00:00Z')/1000);expect(lagosDay(Date.parse('2026-10-01T23:00:00Z'))).toBe('2026-10-02');});
 it('keeps reward multipliers in exact integer units with a two-times ceiling',()=>{expect(pickupAmount('10000000000000000',12500)).toBe('12500000000000000');expect(()=>pickupAmount('1',20001)).toThrow();expect(SKINS.filter(s=>s.tier==='VIP')).toHaveLength(2);});
 it('builds valid odd-sized merkle trees and binds chain, vault, wallet and amount',()=>{const vault='0x'+'1'.repeat(40) as `0x${string}`,asset='0x'+'2'.repeat(40) as `0x${string}`,wallet='0x'+'3'.repeat(40) as `0x${string}`;const leaves=Array.from({length:5},(_,i)=>rewardLeaf(vault,asset,100n,BigInt(i),wallet,BigInt(i+1)));const tree=merkleTree(leaves);for(let i=0;i<leaves.length;i++){let computed=leaves[i];for(const sibling of tree.proof(i))computed=keccak256(concatHex(computed<sibling?[computed,sibling]:[sibling,computed]));expect(computed).toBe(tree.root);}expect(rewardLeaf(vault,asset,100n,0n,wallet,2n)).not.toBe(leaves[0]);expect(rewardLeaf(vault,asset,100n,0n,wallet,1n,1n)).not.toBe(leaves[0]);});
});

describe('Continuous room replay',()=>{
 it('preserves late joins, expired departures and cosmetic snapshots',()=>{const w=createWorld('hunt',99,[entrant]),events:ReplayInput[]=[{tick:0,system:{kind:'skin-equipped',id:'one',skin:'solar-fox'}},{tick:10,join:{id:'two',name:'Two',controller:'human',skin:'luna'}},{tick:11,id:'two',action:{seq:0,type:'MOVE',x:1,y:0}},{tick:20,system:{kind:'players-left',ids:['one']}}];w.players[0].skin='solar-fox';while(w.tick<10)tick(w);addPlayer(w,{id:'two',name:'Two',controller:'human',skin:'luna'});tick(w);applyAction(w,'two',{seq:0,type:'MOVE',x:1,y:0});while(w.tick<20)tick(w);w.players=w.players.filter(p=>p.id!=='one');w.cells=w.cells.filter(c=>c.owner!=='one');while(w.tick<30)tick(w);const restored=replay({version:2,rulesHash:w.rulesHash,seed:99,mode:'hunt',capacity:100,entrants:[entrant]},events,30);expect(restored).toEqual(w);});
});
