import type {Strategy} from '../shared/galaxy/agent';
import {describe,it,expect,vi,afterEach} from 'vitest';
import {runAgent,type AgentAdapter} from '../sdk/agent';
import {createWorld,observe} from '../shared/galaxy/engine';
const mock=vi.hoisted(()=>({send:vi.fn(),close:vi.fn(async()=>{}),hooks:null as any,observation:null as any}));
vi.mock('../sdk/connection',()=>({connectArena:vi.fn(async(_server,_ticket,hooks)=>{mock.hooks=hooks;hooks.identity({id:'a',seq:-1});hooks.frame(mock.observation);return {send:mock.send,close:mock.close};})}));
const frame=()=>observe(createWorld('free',72,[{id:'a',name:'a',controller:'agent'}]),'a');
afterEach(()=>{vi.useRealTimers();vi.clearAllMocks();});
describe('Hosted decision scheduling',()=>{
 it('makes no model calls while a prize arena waits for launch',async()=>{vi.useFakeTimers();mock.observation={...frame(),mode:'prize',tick:0};const adapter={decide:vi.fn(async()=>({type:'WAIT' as const}))};const runner=await runAgent({server:'http://test',epoch:'1',admission:{roomId:'test',token:'test'},adapter});await vi.advanceTimersByTimeAsync(6000);expect(adapter.decide).not.toHaveBeenCalled();await runner.close();});
 it('keeps movement running and one request outstanding during a slow provider',async()=>{vi.useFakeTimers();mock.observation=frame();let concurrent=0,max=0;const adapter:AgentAdapter={decide:vi.fn(async(_o,_p,signal)=>{concurrent++;max=Math.max(max,concurrent);await new Promise<void>((_r,reject)=>signal.addEventListener('abort',()=>{concurrent--;reject(new Error('expired'));},{once:true}));return {type:'WAIT' as const};})};const runner=await runAgent({server:'http://test',admission:{roomId:'test',token:'test'},adapter});await vi.advanceTimersByTimeAsync(7000);expect(max).toBe(1);expect(mock.send.mock.calls.length).toBeGreaterThan(90);expect(mock.send.mock.calls.every(([a])=>a.type==='MOVE')).toBe(true);await runner.close();});
 it('discards a response when its observation is more than 120 ticks old',async()=>{vi.useFakeTimers();mock.observation=frame();let reply:(v:any)=>void=()=>{};const adapter:AgentAdapter={decide:vi.fn(()=>new Promise<Strategy>(r=>{reply=r;}))};const runner=await runAgent({server:'http://test',admission:{roomId:'test',token:'test'},adapter});await vi.advanceTimersByTimeAsync(2100);mock.hooks.frame({...mock.observation,tick:121});reply({type:'SPLIT',x:1,y:0});await vi.advanceTimersByTimeAsync(300);expect(mock.send.mock.calls.some(([a])=>a.type==='SPLIT')).toBe(false);await runner.close();});
 it('uses local control for malformed decisions and avoids model calls while eliminated',async()=>{vi.useFakeTimers();mock.observation=frame();const adapter={decide:vi.fn(async()=>({type:'MOVE',x:NaN,y:5} as any))};const runner=await runAgent({server:'http://test',admission:{roomId:'test',token:'test'},adapter});await vi.advanceTimersByTimeAsync(2200);expect(mock.send.mock.calls.every(([a])=>Number.isFinite(a.x)&&Number.isFinite(a.y))).toBe(true);const count=adapter.decide.mock.calls.length;mock.hooks.frame({...mock.observation,cells:[]});await vi.advanceTimersByTimeAsync(4000);expect(adapter.decide.mock.calls.length).toBe(count);await runner.close();});
});