import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import { db } from './store';
import type { Owner } from './auth';
import { deployment,epoch } from './chain';
export const activeStatuses=['queued','joining','running','reconnecting'];
export const agentInput=z.object({name:z.string().trim().min(1).max(24),description:z.string().max(300).default(''),personality:z.enum(['hunter','survivor','opportunist']).default('opportunist'),instructions:z.string().max(1000).default(''),idempotency:z.string().min(8).max(100).optional()});
export const budgetDay=(now=new Date())=>new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Lagos',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);
export const failure=(message:string,status=409)=>Object.assign(new Error(message),{status});
export function agentConfig(a:any){return {name:a.name,personality:a.personality,instructions:a.instructions,model:process.env.MEMEGALAXY_AGENT_MODEL??'gpt-6-luna',version:a.version};}
export async function hostedAvailable(){return (await db.query('SELECT 1 FROM mg_runtime_instances WHERE lease_until>now() LIMIT 1')).rowCount===1;}
export async function listAgents(auth:Owner){return (await db.query("SELECT a.id,a.name,a.description,a.personality,a.instructions,a.model,a.version,a.hosted_enabled,(a.key_hash IS NOT NULL) AS credential_active,COALESCE(s.matches,0) AS matches,COALESCE(s.wins,0) AS wins,COALESCE(s.peak_mass,0) AS peak_mass,r.id AS run_id,r.status AS run_status,r.message AS run_message,r.mode AS run_mode,r.epoch AS run_epoch FROM mg_agents a LEFT JOIN mg_stats s ON s.player_id='agent:'||a.id LEFT JOIN LATERAL(SELECT * FROM mg_agent_runs WHERE agent_id=a.id ORDER BY created_at DESC LIMIT 1) r ON true WHERE a.owner=$1 ORDER BY a.created_at",[auth.id])).rows;}
export async function createAgent(auth:Owner,raw:unknown){const input=agentInput.parse(raw),c=await db.connect();try{await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(hashtext($1))',[`agent-owner:${auth.id}`]);if(input.idempotency){const old=(await c.query('SELECT id FROM mg_agents WHERE owner=$1 AND idempotency=$2',[auth.id,input.idempotency])).rows[0];if(old){await c.query('COMMIT');return old;}}if(Number((await c.query('SELECT count(*) FROM mg_agents WHERE owner=$1',[auth.id])).rows[0].count)>=3)throw failure('You can create up to three agents');const id=randomUUID();await c.query('INSERT INTO mg_agents(id,owner,wallet,name,description,provider,personality,instructions,model,idempotency) VALUES($1,$2,$3,$4,$5,$6::text,$7,$8,$6::text,$9)',[id,auth.id,auth.wallet,input.name,input.description,process.env.MEMEGALAXY_AGENT_MODEL??'gpt-6-luna',input.personality,input.instructions,input.idempotency??null]);await c.query('COMMIT');return {id,...input};}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
export async function updateAgent(auth:Owner,id:string,raw:unknown){const input=agentInput.parse(raw);const r=await db.query('UPDATE mg_agents SET name=$3,description=$4,personality=$5,instructions=$6,version=version+1 WHERE id=$1 AND owner=$2 RETURNING id,version',[z.string().uuid().parse(id),auth.id,input.name,input.description,input.personality,input.instructions]);if(!r.rowCount)throw failure('Agent not found',404);return r.rows[0];}
export async function practice(auth:Owner,id:string){if(!await hostedAvailable())throw failure('Hosted runtime is not available yet. Your agent is saved; no entry fee has been charged.',503);const c=await db.connect();try{await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(hashtext($1))',[`agent-run:${auth.id}`]);const active=(await c.query('SELECT id,agent_id,mode FROM mg_agent_runs WHERE owner=$1 AND status=ANY($2::text[])',[auth.id,activeStatuses])).rows[0];if(active){if(active.agent_id===id&&active.mode==='free'){await c.query('COMMIT');return active;}throw failure('You already have an active or queued agent');}const a=(await c.query('SELECT * FROM mg_agents WHERE id=$1 AND owner=$2 AND hosted_enabled',[z.string().uuid().parse(id),auth.id])).rows[0];if(!a)throw failure('Agent not found',404);const pending=(await c.query("SELECT 1 FROM mg_entries e JOIN mg_epochs p ON p.deployment=e.deployment AND p.id=e.epoch WHERE e.owner=$1 AND e.confirmed AND e.controller='agent' AND p.status<>'closed'",[auth.id])).rowCount;if(pending)throw failure('Your agent is already registered for a prize match');const day=budgetDay();await c.query('INSERT INTO mg_practice_days(owner,day) VALUES($1,$2) ON CONFLICT DO NOTHING',[auth.id,day]);const quota=await c.query('UPDATE mg_practice_days SET seconds=seconds+300 WHERE owner=$1 AND day=$2 AND seconds+300<=300 RETURNING seconds',[auth.id,day]);if(!quota.rowCount)throw failure('Your five-minute practice allowance resets at midnight Lagos time');const runId=randomUUID();await c.query("INSERT INTO mg_agent_runs(id,agent_id,owner,mode,config) VALUES($1,$2,$3,'free',$4)",[runId,id,auth.id,agentConfig(a)]);await c.query('COMMIT');return {id:runId};}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
export async function stopRun(auth:Owner,id:string,forfeit=false){const r=await db.query("UPDATE mg_agent_runs SET status='stopped',message=$3,updated_at=now() WHERE id=$1 AND owner=$2 AND status=ANY($4::text[]) AND (mode='free' OR $5) RETURNING id",[z.string().uuid().parse(id),auth.id,forfeit?'Owner forfeited':'Practice stopped',activeStatuses,forfeit]);if(!r.rowCount)throw failure('Active run not found, or prize forfeiture was not confirmed');return {stopped:true};}
export async function runStatus(auth:Owner,id:string){const row=(await db.query('SELECT id,agent_id,mode,epoch,config,status,message,room_id,observation,decisions,started_at,ends_at,updated_at FROM mg_agent_runs WHERE id=$1 AND owner=$2',[z.string().uuid().parse(id),auth.id])).rows[0];if(!row)throw failure('Run not found',404);return row;}
export async function queueConfirmedAgents(){
 // Reconciliation owns confirmed flags. Never launch from an unsigned draft or a browser report.
 const rows=(await db.query("SELECT e.* FROM mg_entries e JOIN mg_epochs p ON p.deployment=e.deployment AND p.id=e.epoch WHERE e.deployment=$1 AND e.confirmed AND e.controller='agent' AND e.runtime_mode='hosted' AND p.status<>'closed' AND NOT EXISTS(SELECT 1 FROM mg_agent_runs r WHERE r.deployment=e.deployment AND r.epoch=e.epoch AND r.agent_id::text=substring(e.player_id from 7))",[deployment])).rows;
 for(const e of rows){const c=await db.connect();try{await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(hashtext($1))',[`agent-run:${e.owner}`]);await c.query("UPDATE mg_agent_runs SET status='stopped',message='Prize entry confirmed',updated_at=now() WHERE owner=$1 AND mode='free' AND status=ANY($2::text[])",[e.owner,activeStatuses]);await c.query("INSERT INTO mg_agent_runs(id,agent_id,owner,mode,deployment,epoch,config) VALUES($1,$2,$3,'prize',$4,$5,$6) ON CONFLICT DO NOTHING",[randomUUID(),e.player_id.slice(6),e.owner,deployment,e.epoch,e.agent_config]);await c.query('COMMIT');}catch(err){await c.query('ROLLBACK');throw err;}finally{c.release();}}
 await db.query("UPDATE mg_agent_runs r SET status='stopped',message='Entry cancelled or match ended',updated_at=now() WHERE r.mode='prize' AND r.status=ANY($1::text[]) AND NOT EXISTS(SELECT 1 FROM mg_entries e JOIN mg_epochs p ON p.deployment=e.deployment AND p.id=e.epoch WHERE e.deployment=r.deployment AND e.epoch=r.epoch AND e.owner=r.owner AND e.confirmed AND p.status<>'closed')",[activeStatuses]);
}
export async function draftEntry(auth:Owner,input:unknown){const x=z.object({agentId:z.string().uuid(),deposit:z.string().regex(/^\d{1,10}(\.\d{1,18})?$/).default('1000'),idempotency:z.string().min(8).max(100)}).parse(input);const e=await epoch();if(!e||e.status!==1||Date.now()/1000>=e.deadline)throw failure('Registration is closed');if(Number(x.deposit)<1000||Number(x.deposit)>1e9)throw failure('Deposit must be at least 1,000 tokens',400);if(!(await db.query('SELECT 1 FROM mg_agents WHERE id=$1 AND owner=$2 AND hosted_enabled',[x.agentId,auth.id])).rowCount)throw failure('Agent not found',404);const id=randomUUID();const row=(await db.query('INSERT INTO mg_entry_drafts(id,owner,wallet,epoch,agent_id,deposit,idempotency,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,now()+interval \'10 minutes\') ON CONFLICT(owner,idempotency) DO UPDATE SET idempotency=EXCLUDED.idempotency RETURNING id,epoch,expires_at',[id,auth.id,auth.wallet,e.id.toString(),x.agentId,x.deposit,x.idempotency])).rows[0];return {...row,reviewUrl:`${process.env.MEMEGALAXY_SITE_URL??'https://memegalaxy.usamahabduljalil21.chatgpt.site'}/#prizes?draft=${row.id}`,requiresWalletApproval:true};}
