import { createPublicClient,createWalletClient,http,isAddress,encodeFunctionData,keccak256,type Address,type Hex } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { robinhoodTestnet,galaxyEscrowAbi as abi } from '../../shared/galaxy/chain';
import { db } from './store';
const rpc=process.env.ROBINHOOD_RPC_URL??robinhoodTestnet.rpcUrls.default.http[0];
export const chain=createPublicClient({chain:robinhoodTestnet,transport:http(rpc,{timeout:15000,retryCount:1})});
export const escrow=process.env.MEMEGALAXY_ESCROW_ADDRESS as Address|undefined;
export const deployment=`46630:${escrow?.toLowerCase()??'unconfigured'}`;
export const paid=process.env.MEMEGALAXY_ENABLE_PRIZES==='true'&&!!escrow&&isAddress(escrow);
export async function assertNetwork(){if(await chain.getChainId()!==46630)throw new Error('Only Robinhood testnet is supported');}
export function signer(name:string){const key=(process.env[name]??(name==='MEMEGALAXY_OPERATOR_PRIVATE_KEY'?process.env.REGISTRAR_PRIVATE_KEY:undefined)) as Hex;if(!key)throw new Error(`Missing ${name}`);return createWalletClient({account:privateKeyToAccount(key),chain:robinhoodTestnet,transport:http(rpc,{timeout:15000,retryCount:1})});}
export async function read(fn:string,args:readonly unknown[]=[]){if(!escrow)throw new Error('Testnet escrow not configured');return chain.readContract({address:escrow,abi,functionName:fn as any,args:args as any}) as Promise<any>;}
export async function epoch(){if(!escrow)return null;const id=BigInt(await read('currentEpoch'));if(!id)return null;const v=await read('epochInfo',[id]);return {id,status:Number(v[0]),deadline:Number(v[1]),recovery:Number(v[2]),count:Number(v[3]),arenas:Number(v[4]),finished:Number(v[5]),commitment:v[6] as Hex,seed:v[7] as Hex,entropyBlock:BigInt(v[8])};}
export async function reconcile(){const {rows}=await db.query("SELECT operation_key,hash,raw FROM mg_transactions WHERE deployment=$1 AND status='submitted' ORDER BY updated_at",[deployment]);for(const row of rows){let receipt;try{receipt=await chain.getTransactionReceipt({hash:row.hash});}catch{if(row.raw)try{await chain.sendRawTransaction({serializedTransaction:row.raw});}catch{}receipt=await chain.waitForTransactionReceipt({hash:row.hash,timeout:15000});}await db.query('UPDATE mg_transactions SET status=$2,raw=NULL,updated_at=now() WHERE operation_key=$1',[row.operation_key,receipt.status==='success'?'confirmed':'failed']);}}
/** Caller holds the deployment worker lock. Signed bytes are saved before broadcasting. */
export async function transact(key:string,fn:string,args:readonly unknown[],epochId?:bigint,walletAddress?:string){await reconcile();const operation=`${deployment}:${key}`,previous=(await db.query('SELECT status,hash FROM mg_transactions WHERE operation_key=$1',[operation])).rows[0];if(previous?.status==='confirmed')return previous.hash;const account=signer(['finalizeArena','invalidateArena'].includes(fn)?'RESULT_SIGNER_PRIVATE_KEY':'MEMEGALAXY_OPERATOR_PRIVATE_KEY');await chain.simulateContract({account:account.account,address:escrow!,abi,functionName:fn as any,args:args as any});const request=await account.prepareTransactionRequest({to:escrow!,data:encodeFunctionData({abi,functionName:fn as any,args:args as any})}),raw=await account.signTransaction(request),hash=keccak256(raw);await db.query("INSERT INTO mg_transactions(operation_key,deployment,epoch,wallet,kind,status,hash,raw) VALUES($1,$2,$3,$4,$5,'submitted',$6,$7) ON CONFLICT(operation_key) DO UPDATE SET status='submitted',hash=$6,raw=$7,updated_at=now()",[operation,deployment,epochId?.toString()??null,walletAddress??null,fn,hash,raw]);await chain.sendRawTransaction({serializedTransaction:raw});await reconcile();const final=(await db.query('SELECT status FROM mg_transactions WHERE operation_key=$1',[operation])).rows[0];if(final?.status!=='confirmed')throw new Error(`Transaction ${hash} did not succeed`);return hash;}
