import {xConfigured,xStart,xComplete,verifyX} from './social';
import type express from 'express';
import {z} from 'zod';
import {randomBytes,randomUUID,createHash,createHmac,timingSafeEqual} from 'node:crypto';
import {erc20Abi,isAddress,keccak256,stringToHex,parseUnits,type Address,type Hex} from 'viem';
import {owner,issueAdmission,publicPlayerId} from './auth';
import {db,persistent} from './store';
import {chain,signer} from './chain';
import {profile,adminRoles,requireAdmin,config,wardrobe,unlock,equip,transaction,credit,audit,problem,huntSession,rewardBalance} from './economy';
import {retirementAbi,retirementTypes} from '../../shared/galaxy/economy-chain';
type Route=(fn:(req:express.Request,res:express.Response)=>Promise<unknown>)=>express.RequestHandler;
const nameSchema=z.string().trim().min(3).max(24).regex(/^[\p{L}\p{N} _.-]+$/u);
const idSchema=z.string().min(1).max(100);
const taskSchema=z.object({title:z.string().trim().min(3).max(100),instructions:z.string().min(3).max(2000),platform:z.enum(['x','telegram','other']),target:z.string().min(1).max(300),reward:z.number().int().min(1).max(1000000),budget:z.number().int().min(0).max(1000000000),maxParticipants:z.number().int().min(1).max(1000000),startsAt:z.string().datetime(),endsAt:z.string().datetime(),enabled:z.boolean()}).refine(v=>Date.parse(v.endsAt)>Date.parse(v.startsAt),'Task expiry must follow its start');
export function economyRoutes(app:express.Express,route:Route,findRoom:()=>Promise<string>){
 app.get('/api/v2/economy',route(async(req,res)=>{const a=await owner(req),p=await profile(a);res.json({profile:p,roles:adminRoles(a),gusd:(await db.query('SELECT balance FROM mg_credit_accounts WHERE owner=$1',[a.id])).rows[0]?.balance??'0',retirement:process.env.MEMEGALAXY_RETIREMENT_ADDRESS??null,telegramBot:process.env.MEMEGALAXY_TELEGRAM_BOT_NAME??null,xAvailable:xConfigured()});}));
 app.patch('/api/v2/profile',route(async(req,res)=>{const a=await owner(req),name=nameSchema.parse(req.body.name);await profile(a);await transaction(async c=>{await c.query('UPDATE mg_profiles SET name=$2,name_custom=true,updated_at=now() WHERE owner=$1',[a.id,name]);await c.query('UPDATE mg_stats SET name=$2 WHERE player_id=$1',[publicPlayerId(a.id),name]);});res.json({name});}));
 app.get('/api/v2/skins',route(async(req,res)=>res.json(await wardrobe(await owner(req)))));
 app.post('/api/v2/skins/:id/unlock',route(async(req,res)=>res.json(await unlock(await owner(req),idSchema.parse(req.params.id)))));
 app.post('/api/v2/skins/:id/equip',route(async(req,res)=>res.json(await equip(await owner(req),idSchema.parse(req.params.id)))));
 app.post('/api/v2/hunt/admission',route(async(req,res)=>{if(!persistent)throw problem('Stock Hunt requires persistent storage',503);const a=await owner(req),{roomId,session}=await allocateHunt(a,findRoom);res.json({roomId,token:await issueAdmission({id:publicPlayerId(a.id),name:session.name,controller:'human',owner:a.id,roomId,scope:'hunt',huntSession:session.id,skin:session.skin}),mode:'hunt',multiplier:session.multiplier});}));
 app.get('/api/v2/hunt/rewards',route(async(req,res)=>res.json(await rewardBalance(await owner(req)))));
 app.post('/api/v2/hunt/claims/transaction',route(async(req,res)=>{const a=await owner(req),v=z.object({asset:z.string().refine(isAddress),week:z.string().regex(/^\d+$/),index:z.number().int().nonnegative(),hash:z.string().regex(/^0x[0-9a-fA-F]{64}$/)}).parse(req.body);await db.query('UPDATE mg_stock_claims c SET hash=$4 WHERE asset=$1 AND week=$2 AND idx=$3 AND NOT claimed AND EXISTS(SELECT 1 FROM mg_stock_rewards r WHERE r.owner=$5 AND r.wallet=c.wallet AND r.asset=c.asset AND r.week=c.week)',[v.asset.toLowerCase(),v.week,v.index,v.hash,a.id]);res.json({submitted:true});}));
 app.get('/api/v2/economy/transactions',route(async(req,res)=>{const a=await owner(req);res.json((await db.query(`SELECT hash,kind,status,updated_at FROM (SELECT q.hash,'retire MEMEGALAXY' AS kind,CASE WHEN q.status='credited' THEN 'confirmed' WHEN q.status IN ('failed','invalid') THEN 'failed' ELSE 'submitted' END AS status,q.created_at AS updated_at FROM mg_retire_quotes q WHERE q.owner=$1 AND q.hash IS NOT NULL UNION ALL SELECT c.hash,'claim ' || s.symbol AS kind,CASE WHEN c.claimed THEN 'confirmed' ELSE 'submitted' END AS status,to_timestamp(c.week) AS updated_at FROM mg_stock_claims c JOIN mg_stock_assets s ON s.address=c.asset WHERE c.hash IS NOT NULL AND EXISTS(SELECT 1 FROM mg_stock_rewards r WHERE r.owner=$1 AND r.wallet=c.wallet AND r.asset=c.asset AND r.week=c.week)) history ORDER BY updated_at DESC LIMIT 100`,[a.id])).rows);}));
 app.get('/api/v2/gusd',route(async(req,res)=>{const a=await owner(req);res.json({balance:(await db.query('SELECT balance FROM mg_credit_accounts WHERE owner=$1',[a.id])).rows[0]?.balance??'0',history:(await db.query('SELECT delta,kind,created_at FROM mg_credit_ledger WHERE owner=$1 ORDER BY id DESC LIMIT 100',[a.id])).rows,retirement:(await config()).settings.retirement,quotes:(await db.query('SELECT id,amount,credits,status,hash FROM mg_retire_quotes WHERE owner=$1 ORDER BY created_at DESC LIMIT 20',[a.id])).rows});}));
 app.post('/api/v2/retirement/quote',route(async(req,res)=>{const a=await owner(req),amount=z.string().regex(/^\d{1,10}(\.\d{1,18})?$/).parse(req.body.amount),cfg=await config(),rate=cfg.settings.retirement,address=process.env.MEMEGALAXY_RETIREMENT_ADDRESS as Address|undefined;if(!address||!rate.enabled||BigInt(rate.tokens)<=0n||rate.credits<=0)throw problem('Token retirement is not configured');
  const [version,enabled]=await Promise.all([chain.readContract({address,abi:retirementAbi,functionName:'rateVersion'}),chain.readContract({address,abi:retirementAbi,functionName:'enabled'})]);if(!enabled||Number(version)!==rate.version)throw problem('The retirement rate is awaiting onchain activation');
  const units=parseUnits(amount,18),credits=units*BigInt(rate.credits)/BigInt(rate.tokens);if(units<=0n||credits<=0n||credits>1000000000n)throw problem('Amount is outside the configured conversion limits');const id=('0x'+randomBytes(32).toString('hex')) as Hex,expiry=BigInt(Math.floor(Date.now()/1000)+300),ownerHash=keccak256(stringToHex(a.id));const message={id,wallet:a.wallet as Address,owner:ownerHash,amount:units,credits,version,expiry};const signature=await signer('REGISTRAR_PRIVATE_KEY').signTypedData({domain:{name:'GalaxyRetirement',version:'1',chainId:46630,verifyingContract:address},types:retirementTypes,primaryType:'Retire',message});
  await db.query('INSERT INTO mg_retire_quotes(id,owner,owner_hash,wallet,amount,credits,version,expiry,signature) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[id,a.id,ownerHash,a.wallet,units.toString(),credits.toString(),Number(version),expiry.toString(),signature]);res.json({...message,amount:units.toString(),credits:credits.toString(),version:version.toString(),expiry:expiry.toString(),signature,contract:address,token:process.env.MEMEGALAXY_TOKEN_ADDRESS});
 }));
 app.post('/api/v2/retirement/transaction',route(async(req,res)=>{const a=await owner(req),v=z.object({id:z.string().regex(/^0x[\da-f]{64}$/),hash:z.string().regex(/^0x[\da-fA-F]{64}$/)}).parse(req.body);const updated=await db.query("UPDATE mg_retire_quotes SET hash=$3,status='submitted' WHERE id=$1 AND owner=$2 AND status<>'credited' RETURNING id",[v.id,a.id,v.hash]);if(!updated.rowCount)throw problem('Quote unavailable');res.json({submitted:true});}));
 app.get('/api/v2/tasks',route(async(req,res)=>{const a=await owner(req);res.json((await db.query("SELECT t.*,s.status,s.reason FROM mg_tasks t LEFT JOIN mg_task_submissions s ON s.task_id=t.id AND s.owner=$1 WHERE t.enabled AND t.starts_at<=now() AND t.ends_at>now() ORDER BY t.created_at DESC",[a.id])).rows);}));
 app.post('/api/v2/social/x/start',route(async(req,res)=>res.json(await xStart(await owner(req)))));
 app.post('/api/v2/social/x/complete',route(async(req,res)=>{const a=await owner(req),v=z.object({state:z.string().min(20).max(100),code:z.string().min(1).max(1000)}).parse(req.body);res.json(await xComplete(a,v.state,v.code));}));
 app.post('/api/v2/social/telegram',route(async(req,res)=>{const a=await owner(req),token=process.env.MEMEGALAXY_TELEGRAM_BOT_TOKEN;if(!token)throw problem('Telegram verification is not configured');const fields=z.record(z.union([z.string(),z.number()])).parse(req.body),hash=String(fields.hash??'');if(!/^[a-f0-9]{64}$/.test(hash)||Math.abs(Date.now()/1000-Number(fields.auth_date))>300||!Number.isSafeInteger(Number(fields.id)))throw problem('Telegram proof expired');const text=Object.keys(fields).filter(k=>k!=='hash').sort().map(k=>`${k}=${fields[k]}`).join('\n'),expected=createHmac('sha256',createHash('sha256').update(token).digest()).update(text).digest();if(!timingSafeEqual(Buffer.from(hash,'hex'),expected))throw problem('Telegram proof is invalid',403);await db.query("INSERT INTO mg_social_links(owner,platform,identity,verified) VALUES($1,'telegram',$2,true) ON CONFLICT(owner,platform) DO UPDATE SET identity=$2,verified=true",[a.id,String(fields.id)]);res.json({linked:true});}));
 app.post('/api/v2/tasks/:id/submit',route(async(req,res)=>{const a=await owner(req),id=z.string().uuid().parse(req.params.id),input=z.object({identity:z.string().trim().min(1).max(100),proof:z.string().trim().min(3).max(2000)}).parse(req.body);const t=(await db.query('SELECT * FROM mg_tasks WHERE id=$1 AND enabled AND starts_at<=now() AND ends_at>now()',[id])).rows[0];if(!t)throw problem('Task unavailable');let identity=input.identity.toLowerCase(),automatic=false;const linkedIdentity=(await db.query('SELECT identity FROM mg_social_links WHERE owner=$1 AND platform=$2 AND verified',[a.id,t.platform])).rows[0]?.identity;if(linkedIdentity)identity=linkedIdentity;
  if(t.platform==='telegram'&&process.env.MEMEGALAXY_TELEGRAM_BOT_TOKEN){const linked=(await db.query("SELECT identity FROM mg_social_links WHERE owner=$1 AND platform='telegram' AND verified",[a.id])).rows[0];if(linked){identity=linked.identity;try{const response=await fetch('https://api.telegram.org/bot'+process.env.MEMEGALAXY_TELEGRAM_BOT_TOKEN+'/getChatMember',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:t.target,user_id:Number(identity)}),signal:AbortSignal.timeout(5000)});const result=await response.json();automatic=!!result.ok&&(['creator','administrator','member'].includes(result.result?.status)||result.result?.status==='restricted'&&result.result?.is_member);}catch{automatic=false;}}}
  if(t.platform==='x'){const verified=await verifyX(a,t.target);if(verified){identity=verified.identity;automatic=verified.verified;}}
  const submission=randomUUID();await db.query("INSERT INTO mg_task_submissions(id,task_id,owner,identity,proof) VALUES($1,$2,$3,$4,$5) ON CONFLICT(task_id,owner) DO UPDATE SET identity=CASE WHEN $6::boolean THEN EXCLUDED.identity ELSE mg_task_submissions.identity END,proof=EXCLUDED.proof WHERE mg_task_submissions.status='pending'",[submission,id,a.id,identity,input.proof,!!linkedIdentity]);const stored=(await db.query('SELECT id,status FROM mg_task_submissions WHERE task_id=$1 AND owner=$2',[id,a.id])).rows[0];if(automatic&&stored?.status==='pending')await reviewSubmission(stored.id,'approved',t.platform+' action verified',t.platform+'-verifier');res.json({submitted:true,verification:automatic?'automatic':'manual'});
 }));
 app.get('/api/v2/admin/economy',route(async(req,res)=>{const a=await owner(req);requireAdmin(a);res.json({config:await config(),assets:(await db.query(`SELECT a.*,COALESCE((SELECT sum(reserved) FROM mg_stock_drops d WHERE d.asset=a.address AND d.state='reserved'),0) AS reserved,COALESCE((SELECT sum(amount) FROM mg_stock_rewards r WHERE r.asset=a.address),0)-COALESCE((SELECT sum(amount) FROM mg_stock_claims x WHERE x.asset=a.address AND x.claimed),0)+a.external_liability AS obligations FROM mg_stock_assets a ORDER BY symbol`)).rows,skins:(await db.query('SELECT * FROM mg_skins ORDER BY id')).rows,tasks:(await db.query('SELECT * FROM mg_tasks ORDER BY created_at DESC LIMIT 100')).rows,submissions:(await db.query("SELECT s.*,t.title,t.platform FROM mg_task_submissions s JOIN mg_tasks t ON t.id=s.task_id WHERE s.status='pending' ORDER BY s.created_at LIMIT 100")).rows,audit:(await db.query('SELECT actor,action,subject,detail,created_at FROM mg_economy_audit ORDER BY id DESC LIMIT 50')).rows,vault:process.env.MEMEGALAXY_HUNT_VAULT??null,retirement:process.env.MEMEGALAXY_RETIREMENT_ADDRESS??null});}));
 app.post('/api/v2/admin/config',route(async(req,res)=>{const a=await owner(req);requireAdmin(a);const settings=z.object({enabled:z.boolean(),minInterval:z.number().int().min(30).max(3600),maxInterval:z.number().int().min(30).max(7200),lifetime:z.number().int().min(10).max(300),contactTicks:z.number().int().min(15).max(90),dailyLimit:z.number().int().min(1).max(100),baseUnits:z.string().regex(/^[1-9]\d{0,20}$/),maxMultiplier:z.literal(20000),retirement:z.object({enabled:z.boolean(),version:z.number().int().nonnegative(),tokens:z.string().regex(/^\d{1,30}$/),credits:z.number().int().nonnegative().max(1000000)})}).refine(v=>v.maxInterval>=v.minInterval).parse(req.body);if(settings.retirement.enabled&&(BigInt(settings.retirement.tokens)===0n||settings.retirement.credits===0))throw problem('Set a positive retirement rate');await transaction(async c=>{await c.query("SELECT pg_advisory_xact_lock(hashtext('economy-settings'))");const previous=await config(c);if(JSON.stringify(previous.settings.retirement)!==JSON.stringify(settings.retirement)&&settings.retirement.version<=previous.settings.retirement.version)throw problem('Increase the retirement rate version');await c.query('INSERT INTO mg_economy_config(settings,actor) VALUES($1,$2)',[settings,a.id]);await audit(c,a.id,'config','economy',settings);});res.json({saved:true});}));
 app.post('/api/v2/admin/assets',route(async(req,res)=>{const a=await owner(req);requireAdmin(a);const v=z.object({address:z.string().refine(isAddress),enabled:z.boolean()}).parse(req.body),address=v.address.toLowerCase() as Address;const [code,symbol,decimals]=await Promise.all([chain.getCode({address}),chain.readContract({address,abi:erc20Abi,functionName:'symbol'}),chain.readContract({address,abi:erc20Abi,functionName:'decimals'})]);if(!code||code==='0x'||decimals!==18)throw problem('Only verified 18-decimal test assets are supported');await transaction(async c=>{await c.query('INSERT INTO mg_stock_assets(address,symbol,decimals,enabled) VALUES($1,$2,$3,$4) ON CONFLICT(address) DO UPDATE SET enabled=$4',[address,symbol,decimals,v.enabled]);await audit(c,a.id,'asset',address,{symbol,enabled:v.enabled});});res.json({saved:true});}));
 app.patch('/api/v2/admin/skins/:id',route(async(req,res)=>{const a=await owner(req);requireAdmin(a);const v=z.object({price:z.number().int().positive().max(1000000000).nullable(),paid:z.boolean().optional(),published:z.boolean(),multiplier:z.number().int().min(10000).max(20000),mass:z.number().int().min(0).max(1000000),seconds:z.number().int().min(0).max(10000000)}).parse(req.body);await transaction(async c=>{const skin=(await c.query('SELECT config FROM mg_skins WHERE id=$1 FOR UPDATE',[idSchema.parse(req.params.id)])).rows[0];if(!skin)throw problem('Skin unavailable',404);if(skin.config.tier==='Common'&&(v.paid||v.mass>0||v.seconds>0))throw problem('Common skins remain free starter styles');await c.query("UPDATE mg_skins SET price=$2,published=$3,config=config || $4::jsonb,version=version+1 WHERE id=$1",[idSchema.parse(req.params.id),v.price,v.published,JSON.stringify({multiplier:v.multiplier,mass:v.mass,seconds:v.seconds,...(v.paid===undefined?{}:{paid:v.paid})})]);await audit(c,a.id,'skin',String(req.params.id),v);});res.json({saved:true});}));
 app.post('/api/v2/admin/tasks',route(async(req,res)=>{const a=await owner(req);requireAdmin(a);const v=taskSchema.parse(req.body),id=randomUUID();await transaction(async c=>{await c.query('INSERT INTO mg_tasks(id,title,instructions,platform,target,reward,budget,max_participants,starts_at,ends_at,enabled) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[id,v.title,v.instructions,v.platform,v.target,v.reward,v.budget,v.maxParticipants,v.startsAt,v.endsAt,v.enabled]);await audit(c,a.id,'task-create',id,v);});res.json({id});}));
 app.patch('/api/v2/admin/tasks/:id',route(async(req,res)=>{const a=await owner(req);requireAdmin(a);const enabled=z.boolean().parse(req.body.enabled),id=z.string().uuid().parse(req.params.id);await transaction(async c=>{await c.query('UPDATE mg_tasks SET enabled=$2 WHERE id=$1',[id,enabled]);await audit(c,a.id,'task-enabled',id,{enabled});});res.json({saved:true});}));
 app.post('/api/v2/admin/reviews/:id',route(async(req,res)=>{const a=await owner(req);requireAdmin(a,'reviewer');const v=z.object({status:z.enum(['approved','rejected']),reason:z.string().min(3).max(500)}).parse(req.body);await reviewSubmission(z.string().uuid().parse(req.params.id),v.status,v.reason,a.id);res.json({reviewed:true});}));
 app.post('/api/v2/admin/credits',route(async(req,res)=>{const a=await owner(req);requireAdmin(a);const v=z.object({owner:z.string().min(1).max(200),delta:z.number().int().min(-1000000).max(1000000).refine(n=>n!==0),reason:z.string().min(5).max(500),idempotency:z.string().uuid()}).parse(req.body);await transaction(async c=>{if(await credit(c,v.owner,BigInt(v.delta),'adjustment','adjustment:'+v.idempotency,a.id))await audit(c,a.id,'credit-adjustment',v.owner,{delta:v.delta,reason:v.reason});});res.json({saved:true});}));
}
export async function reviewSubmission(id:string,status:'approved'|'rejected',reason:string,actor:string){await transaction(async c=>{const s=(await c.query('SELECT * FROM mg_task_submissions WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!s||s.status!=='pending')return;const t=(await c.query('SELECT * FROM mg_tasks WHERE id=$1 FOR UPDATE',[s.task_id])).rows[0];if(status==='approved'){const count=Number((await c.query("SELECT count(*) FROM mg_task_submissions WHERE task_id=$1 AND status='approved'",[t.id])).rows[0].count);if(BigInt(t.spent)+BigInt(t.reward)>BigInt(t.budget)||count>=t.max_participants)throw problem('Task reward budget is exhausted');await credit(c,s.owner,BigInt(t.reward),'task','task:'+t.id+':'+s.owner,actor);await c.query('UPDATE mg_tasks SET spent=spent+reward WHERE id=$1',[t.id]);}await c.query('UPDATE mg_task_submissions SET status=$2,reason=$3,reviewer=$4 WHERE id=$1',[id,status,reason,actor]);await audit(c,actor,'task-review',id,{status,reason});});}

async function allocateHunt(auth:Awaited<ReturnType<typeof owner>>,findRoom:()=>Promise<string>){
 const until=Date.now()+5000;
 while(Date.now()<until){const c=await db.connect();let locked=false;try{
  locked=(await c.query("SELECT pg_try_advisory_lock(hashtext('hunt-matchmaking')) AS locked")).rows[0].locked;
  if(locked){const roomId=await findRoom();return {roomId,session:await huntSession(auth,roomId)};}
 }finally{if(locked)await c.query("SELECT pg_advisory_unlock(hashtext('hunt-matchmaking'))");c.release();}
 await new Promise(resolve=>setTimeout(resolve,25));}
 throw problem('Stock Hunt is busy. Please try again.',503);
}
