import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import { rateLimit } from 'express-rate-limit';
import { createServer } from 'node:http';
import { randomBytes,randomUUID } from 'node:crypto';
import { Server,matchMaker } from '@colyseus/core';
import { WebSocketTransport } from '@colyseus/ws-transport';
import { RedisDriver } from '@colyseus/redis-driver';
import { sharedPresence } from './presence';
import { z } from 'zod';
import { GalaxyRoom,roomCreationKey } from './room';
import { owner,agent,hashKey,issueAdmission,publicPlayerId } from './auth';
import { db,persistent,migrateGalaxy } from './store';
import { authorizeEntry,myPrizeEntries,prizeAdmission,prizeLobby,recordTransaction } from './prizes';
import { deployment,paid } from './chain';
const origins=(process.env.MEMEGALAXY_WEB_ORIGINS??process.env.WEB_ORIGINS??'http://127.0.0.1:5173,http://localhost:5173').split(',');
const app=express();app.disable('x-powered-by');app.set('trust proxy',1);app.use(cors({origin(origin,done){done(null,!origin||origins.includes(origin));}}));app.use(express.json({limit:'8kb'}));app.use(rateLimit({windowMs:60000,limit:120}));
const route=(fn:(req:express.Request,res:express.Response)=>Promise<unknown>):express.RequestHandler=>(req,res,next)=>{Promise.resolve(fn(req,res)).catch(next);};
app.get('/health',(_req,res)=>res.json({ok:true,product:'MEMEGalaxy',protocol:2,chainId:46630,persistent,paidEnabled:paid&&persistent}));
app.get('/api/v2/lobby',route(async(_req,res)=>res.json({chainId:46630,paidEnabled:paid&&persistent,message:paid&&persistent?'Testnet prize registration is open. All prizes are test assets.':'Free play is open. Prize matches await release verification.',rooms:(await matchMaker.query({name:'galaxy'})).map(r=>({id:r.roomId,players:r.clients,mode:r.metadata?.mode})),capacity:100})));
async function freeRoom(){const rooms=await matchMaker.query({name:'galaxy',locked:false});const room=rooms.find(r=>r.metadata?.mode==='free'&&r.clients<100);return room?.roomId??(await matchMaker.createRoom('galaxy',{mode:'free',serviceKey:roomCreationKey})).roomId;}
app.post('/api/v2/free/admission',rateLimit({windowMs:60000,limit:10}),route(async(req,res)=>{const {name}=z.object({name:z.string().trim().min(1).max(24).regex(/^[\p{L}\p{N} _.-]+$/u).default('Explorer')}).parse(req.body);const auth=req.headers.authorization?await owner(req):null;const id=auth?publicPlayerId(auth.id):`guest:${randomUUID()}`,roomId=await freeRoom();res.json({roomId,token:await issueAdmission({id,name,controller:'human',owner:auth?.id??id,roomId,scope:'free'})});}));
app.get('/api/v2/agents',route(async(req,res)=>{const auth=await owner(req);const {rows}=await db.query('SELECT id,name,description,provider,personality,(key_hash IS NOT NULL) AS credential_active FROM mg_agents WHERE owner=$1 ORDER BY created_at',[auth.id]);res.json(rows);}));
app.post('/api/v2/agents',route(async(req,res)=>{const auth=await owner(req);const input=z.object({name:z.string().trim().min(1).max(24),description:z.string().max(300).default(''),provider:z.string().max(60).default('External'),personality:z.enum(['hunter','survivor','opportunist']).default('opportunist')}).parse(req.body);const id=randomUUID();await db.query('INSERT INTO mg_agents(id,owner,wallet,name,description,provider,personality) VALUES($1,$2,$3,$4,$5,$6,$7)',[id,auth.id,auth.wallet,input.name,input.description,input.provider,input.personality]);res.status(201).json({id,...input});}));
app.post('/api/v2/agents/:id/credential',route(async(req,res)=>{const auth=await owner(req),id=z.string().uuid().parse(req.params.id),key=`mg_${randomBytes(32).toString('hex')}`;const result=await db.query('UPDATE mg_agents SET key_hash=$3 WHERE id=$1 AND owner=$2 RETURNING id',[id,auth.id,hashKey(key)]);if(!result.rowCount)return res.status(404).json({error:'Agent not found'});res.setHeader('Cache-Control','no-store');res.json({key});}));
app.delete('/api/v2/agents/:id/credential',route(async(req,res)=>{const auth=await owner(req);await db.query('UPDATE mg_agents SET key_hash=NULL WHERE id=$1 AND owner=$2',[z.string().uuid().parse(req.params.id),auth.id]);res.sendStatus(204);}));
app.post('/api/v2/agents/admission',rateLimit({windowMs:60000,limit:10}),route(async(req,res)=>{const a=await agent(req),roomId=await freeRoom();res.json({roomId,personality:a.personality,token:await issueAdmission({id:`agent:${a.id}`,name:a.name,controller:'agent',owner:a.owner,roomId,scope:'free'})});}));
app.get('/api/v2/me',route(async(req,res)=>{const auth=await owner(req);const agents=(await db.query('SELECT id,name,personality,provider FROM mg_agents WHERE owner=$1',[auth.id])).rows;const ids=[publicPlayerId(auth.id),...agents.map(a=>`agent:${a.id}`)];res.json({playerId:ids[0],wallet:auth.wallet,agents,statistics:(await db.query('SELECT * FROM mg_stats WHERE player_id=ANY($1::text[])',[ids])).rows});}));
app.get('/api/v2/rooms/:id/replay',route(async(req,res)=>{const id=z.string().min(1).max(100).parse(req.params.id),after=z.coerce.number().int().min(-1).default(-1).parse(req.query.after);const match=(await db.query("SELECT header,result,checkpoint_tick FROM mg_matches WHERE id=$1 AND status='completed'",[id])).rows[0];if(!match)return res.status(404).json({error:'Replay not available until the match completes'});const chunks=(await db.query('SELECT sequence,events FROM mg_events WHERE match_id=$1 AND sequence>$2 ORDER BY sequence LIMIT 10',[id,after])).rows;res.json({...match,chunks,next:chunks.length===10?chunks[chunks.length-1].sequence:null});}));
app.get('/api/v2/leaderboard',route(async(_req,res)=>{if(!persistent)return res.json([]);res.json((await db.query('SELECT player_id,name,controller,matches,wins,peak_mass FROM mg_stats ORDER BY wins DESC,peak_mass DESC LIMIT 100')).rows);}));
app.post('/api/v2/prizes/transactions',route(recordTransaction));
app.get('/api/v2/prizes',route(prizeLobby));
app.get('/api/v2/prizes/me',route(myPrizeEntries));
app.post('/api/v2/prizes/authorize',rateLimit({windowMs:60000,limit:8}),route(authorizeEntry));
app.post('/api/v2/prizes/admission',route(prizeAdmission));
app.post('/api/v2/rooms/:id/spectate',route(async(req,res)=>{const roomId=z.string().min(1).max(100).parse(req.params.id);const room=(await matchMaker.query({roomId}))[0];if(!room)throw Object.assign(new Error('Room unavailable'),{status:404});const id=`spectator:${randomUUID()}`;res.json({roomId,token:await issueAdmission({id,name:'Spectator',controller:'human',owner:id,roomId,scope:'spectator'})});}));
app.use((err:any,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{const status=err instanceof z.ZodError?400:err.status??500;res.status(status).json({error:status>=500?'This feature is not available yet.':err.message});});
const redis=process.env.MEMEGALAXY_REDIS_URL;
if(redis&&!process.env.MEMEGALAXY_PUBLIC_ADDRESS)throw new Error('Configure a directly routable public address per game process when using shared matchmaking');
const server=new Server({...(redis?{driver:new RedisDriver(redis),presence:sharedPresence(redis),publicAddress:process.env.MEMEGALAXY_PUBLIC_ADDRESS}:{}),transport:new WebSocketTransport({server:createServer(app),maxPayload:4096,verifyClient:(info,done)=>done(!info.origin||origins.includes(info.origin))})});server.define('galaxy',GalaxyRoom);
if(persistent)await migrateGalaxy();
let coordinating=false;const coordinator=persistent?setInterval(async()=>{if(coordinating)return;coordinating=true;const c=await db.connect();try{await c.query('BEGIN');const jobs=(await c.query("SELECT * FROM mg_jobs WHERE deployment=$1 AND status='pending' ORDER BY starts_at FOR UPDATE SKIP LOCKED LIMIT 1",[deployment])).rows;for(const job of jobs){if(Date.now()/1000-Number(job.starts_at)>20){await c.query("UPDATE mg_jobs SET status='invalid' WHERE id=$1",[job.id]);continue;}await c.query("UPDATE mg_jobs SET status='claiming',claim_time=now() WHERE id=$1",[job.id]);const room=await matchMaker.createRoom('galaxy',{serviceKey:roomCreationKey,mode:'prize',entrants:job.roster,seed:Number(job.seed),startsAt:Number(job.starts_at)});await c.query("UPDATE mg_jobs SET status='active',room_id=$2 WHERE id=$1",[job.id,room.roomId]);}await c.query('COMMIT');}catch(e){await c.query('ROLLBACK');console.error('Room assignment failed');}finally{c.release();coordinating=false;}},1000):undefined;
const port=Number(process.env.MEMEGALAXY_PORT??process.env.PORT??2568);await server.listen(port);console.log(`MEMEGalaxy service listening on ${port}`);process.on('SIGTERM',()=>{if(coordinator)clearInterval(coordinator);void server.gracefullyShutdown();});
