import {profile as playerProfile} from './economy';
import type express from 'express';
import { z } from 'zod';
import { owner,publicPlayerId } from './auth';
import { db } from './store';
import { activeStatuses,hostedAvailable,createAgent,updateAgent,listAgents,practice,runStatus,stopRun,failure } from './agents';
import { deployment } from './chain';
type Route=(fn:(req:express.Request,res:express.Response)=>Promise<unknown>)=>express.RequestHandler;
export function platformRoutes(app:express.Express,route:Route){
 app.get('/api/v2/hosted',route(async(_req,res)=>res.json({available:await hostedAvailable(),model:process.env.MEMEGALAXY_AGENT_MODEL??'gpt-6-luna',dailyBudget:10,runBudget:.25})));
 app.get('/api/v2/agents',route(async(req,res)=>res.json(await listAgents(await owner(req)))));
 app.post('/api/v2/agents',route(async(req,res)=>res.status(201).json(await createAgent(await owner(req),req.body))));
 app.patch('/api/v2/agents/:id',route(async(req,res)=>res.json(await updateAgent(await owner(req),String(req.params.id),req.body))));
 app.post('/api/v2/agents/:id/practice',route(async(req,res)=>res.json(await practice(await owner(req),String(req.params.id)))));
 app.get('/api/v2/runs/:id',route(async(req,res)=>res.json(await runStatus(await owner(req),String(req.params.id)))));
 app.post('/api/v2/runs/:id/stop',route(async(req,res)=>{const input=z.object({forfeit:z.literal(true).optional()}).parse(req.body??{});res.json(await stopRun(await owner(req),String(req.params.id),!!input.forfeit));}));
 app.post('/api/v2/session/wallet',route(async(req,res)=>{const auth=await owner(req);if((await db.query('SELECT 1 FROM mg_hunt_sessions WHERE owner=$1 AND wallet<>$2 AND lease_until>now()',[auth.id,auth.wallet])).rowCount)throw failure('Leave Stock Hunt before switching wallets');const conflict=(await db.query("SELECT 1 FROM mg_entries e JOIN mg_epochs p ON p.deployment=e.deployment AND p.id=e.epoch WHERE e.owner=$1 AND e.wallet<>$2 AND p.status<>'closed' AND e.confirmed",[auth.id,auth.wallet])).rowCount;if(conflict)throw failure('Finish or cancel your existing entry before switching wallets');await db.query('INSERT INTO mg_owners(owner,wallet) VALUES($1,$2) ON CONFLICT(owner) DO UPDATE SET wallet=$2,updated_at=now()',[auth.id,auth.wallet]);res.json(auth);}));
 app.get('/api/v2/entry-drafts/:id',route(async(req,res)=>{const auth=await owner(req);const draft=(await db.query('SELECT id,wallet,epoch,agent_id,deposit FROM mg_entry_drafts WHERE id=$1 AND owner=$2 AND expires_at>now()',[z.string().uuid().parse(req.params.id),auth.id])).rows[0];if(!draft)throw failure('This entry review expired. Prepare a new entry.',404);if(draft.wallet!==auth.wallet)throw failure('Connect the wallet used to prepare this entry');res.json(draft);}));
 app.get('/api/v2/players/:id',route(async(req,res)=>{const id=z.string().regex(/^(human:[a-f0-9]{32}|agent:[a-f0-9-]{36})$/).parse(req.params.id);const stats=(await db.query('SELECT player_id,name,controller,matches,wins,peak_mass FROM mg_stats WHERE player_id=$1',[id])).rows[0];const agent=id.startsWith('agent:')?(await db.query('SELECT name,description,personality,model FROM mg_agents WHERE id=$1',[id.slice(6)])).rows[0]:null;if(!stats&&!agent)throw failure('Contender profile not found',404);const history=(await db.query("SELECT j.epoch,j.status AS settlement,m.result,m.id FROM mg_matches m LEFT JOIN mg_jobs j ON j.room_id=m.id WHERE m.status='completed' AND EXISTS(SELECT 1 FROM jsonb_array_elements(m.result) r WHERE r->>'id'=$1) ORDER BY m.heartbeat DESC LIMIT 20",[id])).rows.map(m=>({...m,result:m.result.filter((r:any)=>r.id===id)}));res.json({id,...stats,...agent,controller:id.startsWith('agent:')?'agent':'human',history});}));
 app.get('/api/v2/profile',route(async(req,res)=>{const auth=await owner(req),agents=await listAgents(auth),ids=[publicPlayerId(auth.id),...agents.map(a=>`agent:${a.id}`)];const statistics=(await db.query('SELECT * FROM mg_stats WHERE player_id=ANY($1::text[])',[ids])).rows;const matches=(await db.query("SELECT m.id,m.mode,m.status,m.result,m.heartbeat,j.epoch,j.budget,j.status AS settlement FROM mg_matches m LEFT JOIN mg_jobs j ON j.room_id=m.id WHERE (m.deployment=$2 OR j.deployment=$2) AND EXISTS(SELECT 1 FROM jsonb_array_elements(COALESCE(m.result,'[]')) p WHERE p->>'id'=ANY($1::text[])) ORDER BY m.heartbeat DESC LIMIT 30",[ids,deployment])).rows.map(m=>({...m,ownedResult:m.result.filter((p:any)=>ids.includes(p.id))}));const runs=(await db.query('SELECT id,agent_id,mode,epoch,status,message,started_at,ends_at FROM mg_agent_runs WHERE owner=$1 ORDER BY created_at DESC LIMIT 20',[auth.id])).rows;res.json({...await playerProfile(auth),wallet:auth.wallet,playerId:ids[0],statistics,matches,runs,agents,activeRun:runs.find(r=>activeStatuses.includes(r.status))});}));
 app.get('/api/v2/mcp/connections',route(async(req,res)=>{const auth=await owner(req);res.json((await db.query('SELECT grant_id,name,verified_at,created_at,revoked_at FROM mg_mcp_connections WHERE owner=$1 ORDER BY created_at DESC',[auth.id])).rows);}));
 app.delete('/api/v2/mcp/connections/:id',route(async(req,res)=>{const auth=await owner(req);await db.query('UPDATE mg_mcp_connections SET revoked_at=now() WHERE grant_id=$1 AND owner=$2',[String(req.params.id),auth.id]);res.sendStatus(204);}));
}
