import type express from 'express';
import { z } from 'zod';
import { keccak256,stringToHex,parseUnits,decodeFunctionData,type Address,type Hex } from 'viem';
import { owner,agent,issueAdmission,publicPlayerId } from './auth';
import { db,persistent } from './store';
import { assertNetwork,chain,deployment,epoch,escrow,paid,read,signer } from './chain';
import { agentConfig,hostedAvailable } from './agents';
import { galaxyEntryTypes,galaxyEscrowAbi } from '../../shared/galaxy/chain';
export async function recordTransaction(req:express.Request,res:express.Response){const auth=await owner(req);const {hash}=z.object({hash:z.string().regex(/^0x[0-9a-fA-F]{64}$/)}).parse(req.body);const [tx,receipt]=await Promise.all([chain.getTransaction({hash:hash as Hex}),chain.getTransactionReceipt({hash:hash as Hex})]);if(!escrow||tx.to?.toLowerCase()!==escrow.toLowerCase()||tx.from.toLowerCase()!==auth.wallet||receipt.status!=='success')throw Object.assign(new Error('Transaction is not a confirmed escrow action from your wallet'),{status:400});const decoded=decodeFunctionData({abi:galaxyEscrowAbi,data:tx.input});if(!['register','cancel','claimToken','claimUSDC','recoverArena'].includes(decoded.functionName))throw Object.assign(new Error('Unsupported history action'),{status:400});await db.query("INSERT INTO mg_transactions(operation_key,deployment,epoch,wallet,kind,status,hash) VALUES($1,$2,$3,$4,$5,'confirmed',$6) ON CONFLICT(operation_key) DO NOTHING",[`${deployment}:user:${hash}`,deployment,String(decoded.args?.[0]),auth.wallet,decoded.functionName,hash]);res.json({confirmed:true});}
export async function prizeLobby(_req:express.Request,res:express.Response){const e=await epoch();const available=escrow?BigInt(await read('availablePrize')):0n;res.json({chainId:46630,enabled:paid&&persistent,escrow,token:process.env.MEMEGALAXY_TOKEN_ADDRESS,usdc:process.env.MEMEGALAXY_USDC_ADDRESS,faucet:process.env.MEMEGALAXY_FAUCET_ADDRESS,timing:{underfilledRolloverMinutes:process.env.MEMEGALAXY_ENTROPY_SOURCE==='contract'?5:20,randomness:process.env.MEMEGALAXY_ENTROPY_SOURCE==='contract'?'contract-blockhash':'finalized-parent'},pool:(available>1000000000n?1000000000n:available).toString(),epoch:e?{...e,id:e.id.toString(),entropyBlock:e.entropyBlock.toString()}:null});}
export async function authorizeEntry(req:express.Request,res:express.Response){if(!paid||!persistent)throw Object.assign(new Error('Prize entries are not open yet'),{status:503});await assertNetwork();const auth=await owner(req),input=z.object({deposit:z.string().regex(/^\d{1,10}(\.\d{1,18})?$/),agentId:z.string().uuid().optional(),name:z.string().trim().min(1).max(24)}).parse(req.body),e=await epoch();if(!e||e.status!==1||e.count>=500||Date.now()/1000>=e.deadline)throw Object.assign(new Error('Registration is closed'),{status:409});const amount=parseUnits(input.deposit,18);if(amount<1000n*10n**18n||amount>1000000000n*10n**18n)throw Object.assign(new Error('Deposit must be between 1,000 and 1,000,000,000 MEMEGALAXY'),{status:400});const existing=await read('entryInfo',[e.id,auth.wallet]);if(existing[0]>0n)throw Object.assign(new Error('Already registered'),{status:409});let id=publicPlayerId(auth.id),name=input.name,config:unknown=null;const controller=input.agentId?'agent':'human';if(input.agentId){if(!await hostedAvailable())throw Object.assign(new Error('Hosted agents are not available yet; no entry has been charged'),{status:503});const a=(await db.query('SELECT * FROM mg_agents WHERE id=$1 AND owner=$2 AND hosted_enabled',[input.agentId,auth.id])).rows[0];if(!a)throw Object.assign(new Error('Choose an owned hosted agent'),{status:400});id=`agent:${a.id}`;name=a.name;config=agentConfig(a);}const controllerHash=keccak256(stringToHex(`${controller}:${id}`));
 const c=await db.connect();try{await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(hashtext($1))',[`${deployment}:${e.id}:${auth.id}`]);const previous=(await c.query('SELECT * FROM mg_entries WHERE deployment=$1 AND epoch=$2 AND (wallet=$3 OR owner=$4)',[deployment,e.id.toString(),auth.wallet,auth.id])).rows[0];if(previous&&(previous.controller_hash!==controllerHash||previous.wallet!==auth.wallet))throw Object.assign(new Error('This owner already selected a controller for this epoch'),{status:409});if(previous){config=previous.agent_config;name=previous.name;}await c.query('INSERT INTO mg_entries(deployment,epoch,wallet,owner,player_id,name,controller,controller_hash,runtime_mode,agent_config) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(deployment,epoch,wallet) DO NOTHING',[deployment,e.id.toString(),auth.wallet,auth.id,id,name,controller,controllerHash,input.agentId?'hosted':'human',config]);await c.query('COMMIT');}catch(error){await c.query('ROLLBACK');throw error;}finally{c.release();}
 const userId=keccak256(stringToHex(auth.id)),ruleset=await read('RULESET'),nonce=await read('nonces',[auth.wallet]),expiry=BigInt(Math.min(e.deadline,Math.floor(Date.now()/1000)+120));const signature=await signer('REGISTRAR_PRIVATE_KEY').signTypedData({domain:{name:'MEMEGalaxy',version:'2',chainId:46630,verifyingContract:escrow!},types:galaxyEntryTypes,primaryType:'Entry',message:{epoch:e.id,wallet:auth.wallet as Address,userId,controller:controllerHash,ruleset,amount,nonce,expiry}});res.json({wallet:auth.wallet,name,config,epoch:e.id.toString(),userId,controller:controllerHash,ruleset,amount:amount.toString(),expiry:expiry.toString(),signature,startingMass:100});}
export async function myPrizeEntries(req:express.Request,res:express.Response){const auth=await owner(req);if(!persistent)return res.json({entries:[],transactions:[]});const entries=(await db.query('SELECT epoch,wallet,player_id,name,controller,confirmed,runtime_mode,agent_config FROM mg_entries WHERE deployment=$1 AND owner=$2 ORDER BY epoch DESC LIMIT 30',[deployment,auth.id])).rows;const transactions=(await db.query('SELECT epoch,kind,status,hash,updated_at FROM mg_transactions WHERE deployment=$1 AND wallet=$2 ORDER BY updated_at DESC LIMIT 50',[deployment,auth.wallet])).rows;res.json({wallet:auth.wallet,entries,transactions});}
export async function prizeAdmission(req:express.Request,res:express.Response){const input=z.object({epoch:z.string().regex(/^\d+$/),agent:z.boolean().default(false)}).parse(req.body);let ownerId:string,id:string;if(input.agent){const a=await agent(req);ownerId=a.owner;id=`agent:${a.id}`;}else{const a=await owner(req);ownerId=a.id;id=publicPlayerId(a.id);}const entry=(await db.query('SELECT * FROM mg_entries WHERE deployment=$1 AND epoch=$2 AND owner=$3 AND player_id=$4 AND confirmed',[deployment,input.epoch,ownerId,id])).rows[0];if(!entry)throw Object.assign(new Error('Confirmed entry required'),{status:403});if(input.agent&&entry.runtime_mode==='hosted')throw Object.assign(new Error('This entry uses the hosted runtime; external credentials cannot take control'),{status:403});const job=(await db.query("SELECT j.room_id,j.budget FROM mg_jobs j JOIN mg_matches m ON m.id=j.room_id WHERE j.deployment=$1 AND j.epoch=$2 AND j.roster @> $3::jsonb AND m.status='active'",[deployment,input.epoch,JSON.stringify([{id}])])).rows[0];if(!job)throw Object.assign(new Error('Your arena is not ready'),{status:409});res.json({roomId:job.room_id,budget:String(job.budget),token:await issueAdmission({id,name:entry.name,controller:entry.controller,owner:ownerId,roomId:job.room_id,scope:'prize'})});}
