import {HuntRoom} from './hunt-room';
import { encodeObservation } from '../../shared/galaxy/wire';
import { Room,type Client } from '@colyseus/core';
import { randomBytes,createHash } from 'node:crypto';
import { addPlayer,applyAction,connection,createWorld,observe,rankings,tick,massOf,standings } from '../../shared/galaxy/engine';
import type { Action,Entrant,Observation,World } from '../../shared/galaxy/types';
import type { ReplayInput } from '../../shared/galaxy/replay';
import { verifyAdmission,agentActive,type Admission } from './auth';
import { db,persistent } from './store';
import {deployment} from './chain';
import { PRIZE_JOIN_WINDOW_MS } from './lifecycle';
export const roomCreationKey=createHash('sha256').update(process.env.MEMEGALAXY_ADMISSION_SECRET??process.env.ADMISSION_SECRET??randomBytes(32).toString('hex')).update('memegalaxy-internal-room-creation').digest('hex');
export class GalaxyRoom extends Room {
  metrics:{simulation:number[];broadcast:number[];total:number[]}={simulation:[],broadcast:[],total:[]};
  maxClients=120;autoDispose=false;world!:World;private hunt?:HuntRoom;private progressTick=0;private visibleFood=new Map<string,Set<number>>();private sessions=new Map<string,Admission>();private budgets=new Map<string,{tick:number;count:number}>();private events:ReplayInput[]=[];private sequence=0;private saving=Promise.resolve();private failed=false;private delay:Array<{tick:number;observation:Observation}>=[];private previous=performance.now();private accumulated=0;private lifetime=0;private finished=false;private lastBroadcast=-1;private lastFlush=-1;private validating=false;private prizeReadyAt=0;private prizeRecoveryAt=0;private prizeStarted=false;
  async onCreate(options:{mode?:'free'|'prize'|'hunt';entrants?:Entrant[];seed?:number;startsAt?:number;serviceKey?:string}){
    if(options.serviceKey!==roomCreationKey)throw new Error('Use the authenticated admission API to create a room');
    const seed=options.seed??randomBytes(4).readUInt32LE();this.world=createWorld(options.mode??'free',seed,options.entrants??[]);this.setMetadata({mode:this.world.mode,protocol:2});if(this.world.mode==='prize'){for(const p of this.world.players){connection(this.world,p.id,false);this.events.push({tick:0,id:p.id,connected:false});}this.prizeReadyAt=Date.now()+PRIZE_JOIN_WINDOW_MS;this.prizeRecoveryAt=(options.startsAt??Date.now()/1000)*1000+7200000;}
    if(persistent)await db.query('INSERT INTO mg_matches(id,deployment,mode,rules,header,status) VALUES($1,$2,$3,$4,$5,$6)',[this.roomId,deployment,this.world.mode,this.world.rulesHash,{version:2,rulesHash:this.world.rulesHash,mode:this.world.mode,capacity:100,seed,entrants:options.entrants??[]},'active']);
    this.onMessage('action',(client,a:Action)=>{const session=this.sessions.get(client.sessionId);if(!session||session.scope==='spectator'||!a||this.world.mode==='prize'&&!this.prizeStarted)return;const budget=this.budgets.get(session.id)??{tick:this.world.tick,count:0};if(this.world.tick-budget.tick>=30){budget.tick=this.world.tick;budget.count=0;}budget.count++;this.budgets.set(session.id,budget);if(budget.count>40)return;if(applyAction(this.world,session.id,a))this.events.push({tick:this.world.tick,id:session.id,action:{seq:a.seq,type:a.type,...(a.type==='WAIT'?{}:{x:a.x,y:a.y})}});});
    if(this.world.mode==='hunt')this.hunt=new HuntRoom(this.roomId,()=>[...this.sessions.values()].filter(s=>s.scope==='hunt'),system=>this.events.push({tick:this.world.tick,system}));
    this.setSimulationInterval(()=>this.advance(),1000/30);
  }
  async onAuth(_client:Client,options:{token?:string}){if(!options.token)throw new Error('Admission required');const a=await verifyAdmission(options.token,this.roomId);if(persistent&&a.controller==='agent'&&!await agentActive(a.id,a.owner,a.runId))throw new Error('Agent credential revoked');if(persistent&&a.scope==='prize'&&a.controller==='agent'){const entry=(await db.query('SELECT e.runtime_mode FROM mg_entries e JOIN mg_jobs j ON j.deployment=e.deployment AND j.epoch=e.epoch WHERE j.room_id=$1 AND e.player_id=$2 AND e.confirmed',[this.roomId,a.id])).rows[0];if(!entry||entry.runtime_mode==='hosted'&&!a.runId||entry.runtime_mode!=='hosted'&&a.runId)throw new Error('Use the frozen entry controller');}if(a.scope==='spectator'&&[...this.sessions.values()].filter(s=>s.scope==='spectator').length>=20)throw new Error('Spectator capacity reached');if(a.scope==='hunt'){if(a.controller!=='human'||!a.huntSession)throw new Error('Human hunting session required');const ok=await db.query('SELECT 1 FROM mg_hunt_sessions WHERE id=$1 AND owner=$2 AND player_id=$3 AND room_id=$4 AND lease_until>now()',[a.huntSession,a.owner,a.id,this.roomId]);if(!ok.rowCount)throw new Error('Hunting session expired');}if(a.scope!==this.world.mode&&a.scope!=='spectator')throw new Error('Wrong game mode');if(a.scope!=='spectator'&&[...this.sessions.values()].filter(s=>s.scope!=='spectator').length>=100)throw new Error('Player capacity reached');if(this.world.mode==='prize'&&a.scope!=='spectator'&&!this.world.players.some(p=>p.id===a.id))throw new Error('Not on frozen roster');if([...this.sessions.values()].some(s=>s.id===a.id))throw new Error('Already connected');return a;}
  onJoin(client:Client,_options:unknown,a:Admission){if(a.scope==='spectator'&&[...this.sessions.values()].filter(s=>s.scope==='spectator').length>=20){void client.leave(4003);return;}if([...this.sessions.values()].some(s=>s.id===a.id)){void client.leave(4003);return;}if(a.scope!=='spectator'&&[...this.sessions.values()].filter(s=>s.scope!=='spectator').length>=100){void client.leave(4003);return;}if(a.scope!=='spectator'){if(!this.world.players.some(p=>p.id===a.id)){const entrant={id:a.id,name:a.name,controller:a.controller,...(a.skin?{skin:a.skin}:{})};addPlayer(this.world,entrant);this.events.push({tick:this.world.tick,join:entrant});}const player=this.world.players.find(p=>p.id===a.id);if(a.skin&&player&&!player.skin){player.skin=a.skin;this.events.push({tick:this.world.tick,system:{kind:'skin-equipped',id:a.id,skin:a.skin}});}connection(this.world,a.id,true);this.events.push({tick:this.world.tick,id:a.id,connected:true});}this.sessions.set(client.sessionId,a);client.send('identity',{id:a.id,seq:this.world.players.find(p=>p.id===a.id)?.seq??-1});if(a.scope!=='spectator')this.sendObservation(client,observe(this.world,a.id));}
  async onLeave(client:Client,consented:boolean){const a=this.sessions.get(client.sessionId);if(a&&a.scope!=='spectator'){connection(this.world,a.id,false);this.events.push({tick:this.world.tick,id:a.id,connected:false});}this.visibleFood.delete(client.sessionId);if(!consented&&a&&!this.finished&&!this.failed){try{const returning=await this.allowReconnection(client,20);if(a.controller==='agent'&&persistent&&!await agentActive(a.id,a.owner,a.runId)){void returning.leave(4003);return;}connection(this.world,a.id,true);this.events.push({tick:this.world.tick,id:a.id,connected:true});returning.send('identity',{id:a.id,seq:this.world.players.find(p=>p.id===a.id)?.seq??-1});return;}catch{}}this.sessions.delete(client.sessionId);if(a?.huntSession)void db.query('DELETE FROM mg_hunt_sessions WHERE id=$1',[a.huntSession]).catch(()=>{});}
  private async validateAgents(){if(!persistent||this.validating)return;this.validating=true;try{for(const client of this.clients){const a=this.sessions.get(client.sessionId);if(a?.controller==='agent'){let valid=false;try{valid=await agentActive(a.id,a.owner,a.runId);}catch{}if(!valid)void client.leave(4003);}}}finally{this.validating=false;}}
  private sendObservation(client:Client,o:Observation){const encoded=encodeObservation(this.hunt?this.hunt.view(o):o,this.visibleFood.get(client.sessionId));this.visibleFood.set(client.sessionId,encoded.visible);client.send('frame',JSON.stringify(encoded.frame));}
  private advance(){if(this.failed||this.finished)return;const start=performance.now(),delta=(start-this.previous)/1000;this.previous=start;if(this.world.mode==='prize'&&Date.now()>=this.prizeRecoveryAt){void this.invalidate('Recovery deadline reached');return;}if(this.world.mode==='prize'&&!this.prizeStarted){if(Date.now()<this.prizeReadyAt)return;this.prizeStarted=true;if(this.world.players.filter(p=>p.disconnectedTick===null).length<3){void this.invalidate('Fewer than three entrants reached the arena');return;}}this.accumulated+=delta;this.lifetime+=delta;if(this.accumulated>3){void this.invalidate('Simulation lag exceeded recovery budget');return;}
    while(this.accumulated>=1/30&&!this.world.finished){tick(this.world);this.hunt?.tick(this.world);this.accumulated-=1/30;}
    const simulated=performance.now();if(this.world.tick-this.lastBroadcast>=3){this.lastBroadcast=this.world.tick;const board=standings(this.world);const leader=rankings(this.world)[0];if(leader)this.delay.push({tick:this.world.tick,observation:observe(this.world,leader.id,board)});while(this.delay.length>110)this.delay.shift();for(const client of this.clients){const a=this.sessions.get(client.sessionId);if(!a)continue;const player=this.world.players.find(p=>p.id===a.id);if(a.scope==='spectator'||this.world.mode==='prize'&&!player?.alive){const frame=[...this.delay].reverse().find(x=>x.tick<=this.world.tick-300);if(frame)this.sendObservation(client,{...frame.observation,self:a.id});}else this.sendObservation(client,observe(this.world,a.id,board));}}
    if(this.world.tick-this.lastFlush>=150){this.lastFlush=this.world.tick;this.flush();void this.validateAgents();void this.recordProgress();}
    if(this.world.mode!=='prize'){const expired=this.world.players.filter(p=>p.disconnectedTick!==null&&this.world.tick-p.disconnectedTick>=600).map(p=>p.id);if(expired.length)this.events.push({tick:this.world.tick,system:{kind:'players-left',ids:expired}});this.world.players=this.world.players.filter(p=>!expired.includes(p.id));this.world.cells=this.world.cells.filter(c=>!expired.includes(c.owner));if(this.lifetime>60&&!this.clients.length){this.finished=true;void this.disconnect();}}
    if(this.world.finished){this.finished=true;this.flush();void this.finish();};
    const end=performance.now();this.metrics.simulation.push(simulated-start);this.metrics.broadcast.push(end-simulated);this.metrics.total.push(end-start);for(const list of Object.values(this.metrics))if(list.length>1000)list.shift();
  }
  async onDispose(){await this.hunt?.close();if(this.world.mode==='prize'&&!this.world.finished){await this.invalidate('Game service stopped before completion');return;}if(!this.failed){this.flush();await this.finish();}}
  private async recordProgress(){if(!persistent)return;const at=this.world.tick,seconds=Math.min(5,(at-this.progressTick)/30);this.progressTick=at;try{for(const a of this.sessions.values()){const p=this.world.players.find(p=>p.id===a.id);if(a.controller!=='human'||a.scope==='spectator'||!a.id.startsWith('human:')||!p||p.disconnectedTick!==null)continue;const active=p.alive&&Math.hypot(p.intent.x,p.intent.y)>.05?Math.floor(seconds):0;await db.query(`WITH award AS (INSERT INTO mg_progress_cursors(room_id,player_id,tick) VALUES($1,$2,$3) ON CONFLICT(room_id,player_id) DO UPDATE SET tick=$3 WHERE mg_progress_cursors.tick<$3 RETURNING 1) INSERT INTO mg_profiles(owner,peak_mass,active_seconds,name,progress_at) SELECT $4,$5::double precision,$6::bigint,$7::varchar(24),CASE WHEN $6::bigint>0 THEN now() ELSE NULL END FROM award ON CONFLICT(owner) DO UPDATE SET peak_mass=GREATEST(mg_profiles.peak_mass,$5::double precision),active_seconds=mg_profiles.active_seconds+LEAST($6::bigint,GREATEST(0,FLOOR(COALESCE(EXTRACT(EPOCH FROM now()-mg_profiles.progress_at),$6::numeric)))::bigint),progress_at=CASE WHEN $6::bigint>0 THEN now() ELSE mg_profiles.progress_at END`,[this.roomId,p.id,at,a.owner,p.peakMass,active,p.name]);}}catch(e){console.warn('Player progress persistence deferred:',(e as {code?:string}).code??'unknown',(e as Error).message);}}
  private flush(){const events=this.events.splice(0),sequence=this.sequence++;if(!persistent)return;const checkpoint=JSON.stringify(this.world);this.saving=this.saving.then(async()=>{const c=await db.connect();try{await c.query('BEGIN');await c.query('INSERT INTO mg_events(match_id,sequence,events) VALUES($1,$2,$3)',[this.roomId,sequence,JSON.stringify(events)]);await c.query('UPDATE mg_matches SET checkpoint=$2,checkpoint_tick=$3,heartbeat=now() WHERE id=$1',[this.roomId,checkpoint,JSON.parse(checkpoint).tick]);await c.query('COMMIT');}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}});this.saving.catch(()=>void this.invalidate('Persistence unavailable'));}
  private async finish(){try{await this.saving;const result=rankings(this.world).map((p,i)=>({id:p.id,name:p.name,controller:p.controller,rank:i+1,mass:p.alive?massOf(this.world,p.id):p.lastMass,peakMass:p.peakMass,earned:p.earned,eliminatedTick:p.eliminatedTick}));if(persistent)await db.query("UPDATE mg_matches SET status='completed',result=$2,heartbeat=now() WHERE id=$1 AND status='active'",[this.roomId,JSON.stringify(result)]);this.broadcast('result',result);}catch{await this.invalidate('Unable to persist result');}}
  private async invalidate(reason:string){if(this.failed)return;this.failed=true;this.broadcast('invalid',{message:'This room stopped safely. Unresolved prize entries remain recoverable.'});if(persistent)try{await db.query("UPDATE mg_matches SET status='invalid' WHERE id=$1 AND status='active'",[this.roomId]);}catch{}console.error('galaxy_invalid',this.roomId,reason);void this.disconnect();}
}
