import 'dotenv/config';
import { createServer } from 'node:http';
import { randomUUID,createHash,createCipheriv,createDecipheriv,randomBytes } from 'node:crypto';
import { db,migrateGalaxy,persistent } from './store';
import { activeStatuses,queueConfirmedAgents } from './agents';
import { issueAdmission } from './auth';
import { runAgent } from '../../sdk/agent';
import { HostedModelAdapter } from './model';
if(!persistent)throw new Error('Agent runtime requires PostgreSQL');await migrateGalaxy();
const holder=randomUUID(),origin=process.env.MEMEGALAXY_API_URL??'https://memegalaxy-staging-production.up.railway.app';
const secret=process.env.MEMEGALAXY_ADMISSION_SECRET??process.env.ADMISSION_SECRET;if(!secret||secret.length<32)throw new Error('Agent admission secret is required');
const key=createHash('sha256').update(secret).update('runtime-reconnect').digest();
export function seal(value:string){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',key,iv);const encrypted=Buffer.concat([c.update(value,'utf8'),c.final()]);return Buffer.concat([iv,c.getAuthTag(),encrypted]).toString('base64');}
function unseal(value:string){const b=Buffer.from(value,'base64'),d=createDecipheriv('aes-256-gcm',key,b.subarray(0,12));d.setAuthTag(b.subarray(12,28));return Buffer.concat([d.update(b.subarray(28)),d.final()]).toString('utf8');}
const runners=new Map<string,{abort:AbortController;close?:()=>Promise<void>;frame?:unknown;message:string;frameAt:number;terminal?:string}>();let cycling=false,lastCycle=Date.now();
async function launch(row:any){const abort=new AbortController(),state={abort,message:'Connecting to arena',frameAt:0} as {abort:AbortController;close?:()=>Promise<void>;frame?:unknown;message:string;frameAt:number;terminal?:string};runners.set(row.id,state);
 try{let roomId=row.room_id;if(row.mode==='prize'){const job=(await db.query("SELECT j.room_id,m.status FROM mg_jobs j JOIN mg_matches m ON m.id=j.room_id WHERE j.deployment=$1 AND j.epoch=$2 AND j.roster @> $3::jsonb",[row.deployment,row.epoch,JSON.stringify([{id:`agent:${row.agent_id}`}])])).rows[0];if(!job||job.status==='active'&&!job.room_id){runners.delete(row.id);await db.query("UPDATE mg_agent_runs SET status='queued',lease_until=NULL,lease_owner=NULL WHERE id=$1 AND lease_owner=$2",[row.id,holder]);return;}if(job.status!=='active'){state.terminal='completed';return;}roomId=job.room_id;}else if(!roomId){const response=await fetch(origin+'/api/v2/internal/agent-room',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+createHash('sha256').update(secret!).update('agent-runtime').digest('hex')},body:JSON.stringify({runId:row.id,holder})});if(!response.ok)throw new Error('Practice admission unavailable');roomId=(await response.json()).roomId;}
  await db.query("UPDATE mg_agent_runs SET status='joining',room_id=$3,started_at=COALESCE(started_at,now()),ends_at=CASE WHEN mode='free' THEN COALESCE(ends_at,now()+interval '5 minutes') ELSE ends_at END WHERE id=$1 AND lease_owner=$2",[row.id,holder,roomId]);
  const ticket={roomId,token:await issueAdmission({id:`agent:${row.agent_id}`,name:row.config.name,owner:row.owner,controller:'agent',scope:row.mode==='prize'?'prize':'free',roomId,runId:row.id}),...(row.reconnect?{reconnect:unseal(row.reconnect)}:{})};
  const runner=await runAgent({server:origin,admission:ticket,personality:row.config.personality,epoch:row.mode==='prize'?String(row.epoch):undefined,adapter:new HostedModelAdapter(row,message=>{state.message=message;}),signal:abort.signal,onReconnect:value=>{void db.query('UPDATE mg_agent_runs SET reconnect=$3 WHERE id=$1 AND lease_owner=$2',[row.id,holder,seal(value)]).catch(()=>abort.abort());},onObservation:o=>{if(Date.now()-state.frameAt>=1000){state.frame=o;state.frameAt=Date.now();}},onStatus:message=>{state.message=message;if(message==='Match finished')state.terminal='completed';else if(message.includes('session ended')||message.includes('Unable to reconnect')||message.includes('stopped safely'))state.terminal='failed';}});state.close=runner.close;
 }catch{state.terminal='failed';state.message='Agent could not reach the arena';}
}
async function cycle(){await db.query("INSERT INTO mg_runtime_instances(id,lease_until) VALUES($1,now()+interval '7 seconds') ON CONFLICT(id) DO UPDATE SET lease_until=EXCLUDED.lease_until",[holder]);lastCycle=Date.now();await queueConfirmedAgents();
 for(const [id,state]of runners){const row=(await db.query('UPDATE mg_agent_runs SET lease_until=now()+interval \'7 seconds\',updated_at=now(),observation=COALESCE($3::jsonb,observation),message=$4,status=CASE WHEN $5 THEN status ELSE \'running\' END WHERE id=$1 AND lease_owner=$2 AND status=ANY($6::text[]) RETURNING ends_at,status',[id,holder,state.frame?JSON.stringify(state.frame):null,state.message,!state.frame,activeStatuses])).rows[0];if(!row||state.terminal||row.ends_at&&new Date(row.ends_at).getTime()<=Date.now()){state.abort.abort();await state.close?.();runners.delete(id);if(row)await db.query('UPDATE mg_agent_runs SET status=$3,reconnect=NULL,lease_until=NULL,updated_at=now() WHERE id=$1 AND lease_owner=$2',[id,holder,state.terminal??'completed']);}}
 const claimed=(await db.query("UPDATE mg_agent_runs SET lease_owner=$1,lease_until=now()+interval '7 seconds',status='joining' WHERE id IN (SELECT id FROM mg_agent_runs WHERE status=ANY($2::text[]) AND (lease_until IS NULL OR lease_until<now()) ORDER BY CASE WHEN mode='prize' THEN 0 ELSE 1 END,created_at FOR UPDATE SKIP LOCKED LIMIT 20) RETURNING *",[holder,activeStatuses])).rows;for(const row of claimed)void launch(row);
}
const timer=setInterval(()=>{if(cycling)return;cycling=true;void cycle().catch(()=>{for(const state of runners.values()){state.abort.abort();void state.close?.();}runners.clear();}).finally(()=>{cycling=false;});},1000);
createServer((_req,res)=>{res.writeHead(Date.now()-lastCycle<7000?200:503,{'Content-Type':'application/json'});res.end(JSON.stringify({role:'agent-runtime',active:runners.size,modelConfigured:!!process.env.OPENAI_API_KEY}));}).listen(Number(process.env.PORT??2570));
console.log('MEMEGalaxy hosted agent runtime ready');// Exit without a consented room leave so an isolated runtime restart can reconnect.
process.on('SIGTERM',()=>{clearInterval(timer);process.exit(0);});
