import {randomBytes,createHash,createCipheriv,createDecipheriv} from 'node:crypto';
import {db} from './store';
import {problem} from './economy';
import type {Owner} from './auth';
const clientId=()=>process.env.MEMEGALAXY_X_CLIENT_ID;
export const xConfigured=()=>!!(clientId()&&process.env.MEMEGALAXY_X_REDIRECT_URI&&(process.env.MEMEGALAXY_ADMISSION_SECRET??process.env.ADMISSION_SECRET));
function cryptKey(){const secret=process.env.MEMEGALAXY_ADMISSION_SECRET??process.env.ADMISSION_SECRET;if(!secret||secret.length<32)throw problem('Social verification unavailable');return createHash('sha256').update(secret).update('galaxy-social-v1').digest();}
function encrypt(text:string,owner:string){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',cryptKey(),iv);cipher.setAAD(Buffer.from(owner));const encrypted=Buffer.concat([cipher.update(text,'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),encrypted]).toString('base64');}
function decrypt(text:string,owner:string){const b=Buffer.from(text,'base64'),decipher=createDecipheriv('aes-256-gcm',cryptKey(),b.subarray(0,12));decipher.setAAD(Buffer.from(owner));decipher.setAuthTag(b.subarray(12,28));return Buffer.concat([decipher.update(b.subarray(28)),decipher.final()]).toString('utf8');}
export async function xStart(auth:Owner){if(!xConfigured())throw problem('X verification is not configured');const state=randomBytes(32).toString('base64url'),verifier=randomBytes(48).toString('base64url');await db.query("DELETE FROM mg_x_oauth WHERE expires_at<now() OR owner=$1",[auth.id]);await db.query("INSERT INTO mg_x_oauth(state,owner,verifier,expires_at) VALUES($1,$2,$3,now()+interval '5 minutes')",[createHash('sha256').update(state).digest('hex'),auth.id,encrypt(verifier,auth.id)]);const params=new URLSearchParams({response_type:'code',client_id:clientId()!,redirect_uri:process.env.MEMEGALAXY_X_REDIRECT_URI!,scope:'tweet.read users.read follows.read like.read',state,code_challenge:createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'S256'});return {state,url:'https://x.com/i/oauth2/authorize?'+params};}
export async function xComplete(auth:Owner,state:string,code:string){if(!xConfigured())throw problem('X verification is not configured');const row=(await db.query('DELETE FROM mg_x_oauth WHERE state=$1 AND owner=$2 AND expires_at>now() RETURNING verifier',[createHash('sha256').update(state).digest('hex'),auth.id])).rows[0];if(!row)throw problem('X connection expired');const headers:Record<string,string>={'Content-Type':'application/x-www-form-urlencoded'};if(process.env.MEMEGALAXY_X_CLIENT_SECRET)headers.Authorization='Basic '+Buffer.from(clientId()+':'+process.env.MEMEGALAXY_X_CLIENT_SECRET).toString('base64');const response=await fetch('https://api.x.com/2/oauth2/token',{method:'POST',headers,body:new URLSearchParams({grant_type:'authorization_code',code,client_id:clientId()!,redirect_uri:process.env.MEMEGALAXY_X_REDIRECT_URI!,code_verifier:decrypt(row.verifier,auth.id)}),signal:AbortSignal.timeout(5000)});if(!response.ok)throw problem('X authorization failed. Reconnect your account.');const token=await response.json();const me=await xGet('/users/me',token.access_token);if(!me.data?.id)throw problem('Unable to verify X identity');await db.query("INSERT INTO mg_social_links(owner,platform,identity,verified,credential,expires_at) VALUES($1,'x',$2,true,$3,$4) ON CONFLICT(owner,platform) DO UPDATE SET identity=$2,verified=true,credential=$3,expires_at=$4",[auth.id,me.data.id,encrypt(token.access_token,auth.id),new Date(Date.now()+Number(token.expires_in??7200)*1000)]);return {linked:true};}
async function xGet(path:string,token:string){const response=await fetch('https://api.x.com/2'+path,{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(5000)});if(!response.ok)throw problem('X verification unavailable; submit for manual review');return response.json();}
/** Bounded read-only verification; API limits and unconfirmed actions fall back to review. */
export async function verifyX(auth:Owner,target:string){const link=(await db.query("SELECT * FROM mg_social_links WHERE owner=$1 AND platform='x' AND verified AND expires_at>now()",[auth.id])).rows[0];if(!link?.credential)return null;try{const token=decrypt(link.credential,auth.id);const url=new URL(target);if(!['x.com','www.x.com','twitter.com','www.twitter.com'].includes(url.hostname))return null;const parts=url.pathname.split('/').filter(Boolean),post=parts[1]==='status'&&/^\d+$/.test(parts[2]??'')?parts[2]:undefined;let targetId=post;if(!post){if(!/^[\w]{1,15}$/.test(parts[0]??''))return null;targetId=(await xGet('/users/by/username/'+parts[0],token)).data?.id;}if(!targetId)return null;let next:string|undefined;for(let page=0;page<3;page++){const query=new URLSearchParams({max_results:'100',...(next?{pagination_token:next}:{})});const result=await xGet('/users/'+link.identity+(post?'/liked_tweets?':'/following?')+query,token);if(result.data?.some((r:any)=>r.id===targetId))return {identity:link.identity,verified:true};next=result.meta?.next_token;if(!next)break;}return {identity:link.identity,verified:false};}catch{return {identity:link.identity,verified:false};}}
