import { createServer } from 'node:http';
import { performance } from 'node:perf_hooks';
import { Server,matchMaker,WebSocketTransport } from '../server/galaxy/colyseus';
import { Client,type Room } from 'colyseus.js';
process.env.DATABASE_URL='';process.env.MEMEGALAXY_DATABASE_URL='';
const {GalaxyRoom,roomCreationKey}=await import('../server/galaxy/room');const {issueAdmission}=await import('../server/galaxy/auth');
const http=createServer(),server=new Server({transport:new WebSocketTransport({server:http,maxPayload:4096})});server.define('galaxy',GalaxyRoom);await server.listen(0,'127.0.0.1');const port=(http.address() as {port:number}).port,client=new Client(`ws://127.0.0.1:${port}`),connections:Room[]=[],frames=new Map<string,number>(),rooms:string[]=[];
try{for(let a=0;a<5;a++){const entrants=Array.from({length:100},(_,i)=>({id:`${a}:${i}`,name:`Load ${i}`,controller:i%2?'human' as const:'agent' as const}));const room=await matchMaker.createRoom('galaxy',{mode:'free',seed:a+50,entrants,serviceKey:roomCreationKey});rooms.push(room.roomId);for(let i=0;i<100;i+=10)await Promise.all(entrants.slice(i,i+10).map(async p=>{const token=await issueAdmission({...p,owner:p.id,roomId:room.roomId,scope:'free'});const r=await client.joinById(room.roomId,{token});frames.set(p.id,0);r.onMessage('identity',()=>{});r.onMessage('frame',()=>frames.set(p.id,(frames.get(p.id)??0)+1));r.onMessage('invalid',()=>{throw new Error('Room invalidated under load');});connections.push(r);}));}
 let seq=0;const interval=setInterval(()=>{seq++;connections.forEach((r,i)=>r.send('action',{seq,type:seq%75===0?'SPLIT':'MOVE',x:Math.cos(i+seq/30),y:Math.sin(i+seq/30)}));},1000/15);const start=performance.now();await new Promise(resolve=>setTimeout(resolve,30000));clearInterval(interval);const timings=rooms.map(id=>(matchMaker.getLocalRoomById(id) as InstanceType<typeof GalaxyRoom>).metrics);const p95=(list:number[])=>{list.sort((a,b)=>a-b);return list[Math.floor(list.length*.95)];};console.log(JSON.stringify({p95SimulationMs:p95(timings.flatMap(m=>m.simulation)),p95BroadcastMs:p95(timings.flatMap(m=>m.broadcast)),p95TotalMs:p95(timings.flatMap(m=>m.total))}));const minimum=Math.min(...frames.values()),live=connections.filter(r=>r.connection.isOpen).length;console.log(JSON.stringify({connections:connections.length,live,rooms:rooms.length,durationSeconds:(performance.now()-start)/1000,minimumFrames:minimum,pass:live===500&&minimum>=200},null,2));if(live!==500||minimum<200)process.exitCode=1;
}finally{await Promise.all(connections.map(r=>r.leave()));await server.gracefullyShutdown(false);}
