import 'dotenv/config';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createPublicClient,http,erc20Abi,parseAbi,keccak256,stringToHex,formatUnits} from 'viem';
import {arcTestnet,escrowAbi} from '../shared/chain';
const d=JSON.parse(readFileSync('.local/deployment.json','utf8')),a=JSON.parse(readFileSync('.local/testnet-accounts.json','utf8'));
const c=createPublicClient({chain:arcTestnet,transport:http(process.env.ARC_RPC_URL)});
assert.equal(await c.getChainId(),5042002);
const [supply,faucetBalance,decimals,budget,epoch]=await Promise.all([c.readContract({address:d.dominate,abi:erc20Abi,functionName:'totalSupply'}),c.readContract({address:d.dominate,abi:erc20Abi,functionName:'balanceOf',args:[d.faucet]}),c.readContract({address:d.usdc,abi:erc20Abi,functionName:'decimals'}),c.readContract({address:d.escrow,abi:escrowAbi,functionName:'availablePrize'}),c.readContract({address:d.escrow,abi:escrowAbi,functionName:'currentEpoch'})]);
assert.equal(supply,1_000_000_000n*10n**18n);assert.equal(decimals,6);
for(const address of [d.dominate,d.faucet,d.escrow])assert.ok((await c.getCode({address}))?.length);
const abi=parseAbi(['function hasRole(bytes32,address) view returns(bool)']);
const roles=[['0x'+'00'.repeat(32),d.admin],[keccak256(stringToHex('OPERATOR_ROLE')),a.result_signer],[keccak256(stringToHex('REGISTRAR_ROLE')),a.registrar]];
for(const [role,wallet] of roles)assert.equal(await c.readContract({address:d.escrow,abi,functionName:'hasRole',args:[role as `0x${string}`,wallet as `0x${string}`]}),true);
console.log(JSON.stringify({chainId:5042002,contractsVerified:true,rolesVerified:true,supply:formatUnits(supply,18),faucetBalance:formatUnits(faucetBalance,18),prizeTestUSDC:formatUnits(budget,6),epoch:epoch.toString()},null,2));
