import { createContext,useContext,useMemo,type ReactNode } from 'react';
import { PrivyProvider,usePrivy,useWallets } from '@privy-io/react-auth';
import { createPublicClient,createWalletClient,custom,http,encodeFunctionData,erc20Abi,formatUnits,type Address,type Hex } from 'viem';
import { arcTestnet } from '../shared/chain';
const appId=import.meta.env.VITE_PRIVY_APP_ID;
export const rpc=createPublicClient({chain:arcTestnet,transport:http(import.meta.env.VITE_RPC_URL||arcTestnet.rpcUrls.default.http[0])});
export const addresses={escrow:import.meta.env.VITE_ESCROW_ADDRESS as Address|undefined,dominate:import.meta.env.VITE_DOMINATE_ADDRESS as Address|undefined,usdc:import.meta.env.VITE_USDC_ADDRESS as Address|undefined,faucet:import.meta.env.VITE_FAUCET_ADDRESS as Address|undefined};
type WalletContext={configured:boolean;ready:boolean;authenticated:boolean;address?:Address;login:()=>void;logout:()=>Promise<void>;getToken:()=>Promise<string|null>;send:(to:Address,data:Hex)=>Promise<Hex>};
const missing=async()=>{throw new Error('Wallet sign-in is not configured yet. Practice is available now.');};
const context=createContext<WalletContext>({configured:false,ready:true,authenticated:false,login:()=>{},logout:async()=>{},getToken:async()=>null,send:missing});
function Connected({children}:{children:ReactNode}){const privy=usePrivy(),{wallets}=useWallets();const wallet=wallets.find(w=>w.walletClientType==='privy');const value=useMemo<WalletContext>(()=>({configured:true,ready:privy.ready,authenticated:privy.authenticated,address:wallet?.address as Address|undefined,login:privy.login,logout:privy.logout,getToken:privy.getAccessToken,send:async(to,data)=>{if(!wallet)throw new Error('Your embedded wallet is still being created.');await wallet.switchChain(arcTestnet.id);const provider=await wallet.getEthereumProvider();const client=createWalletClient({account:wallet.address as Address,chain:arcTestnet,transport:custom(provider)});const hash=await client.sendTransaction({to,data});const receipt=await rpc.waitForTransactionReceipt({hash,timeout:90000});if(receipt.status!=='success')throw new Error('Transaction reverted. No entry was confirmed.');return hash;}}),[privy.ready,privy.authenticated,wallet,privy.login,privy.logout,privy.getAccessToken]);return <context.Provider value={value}>{children}</context.Provider>;}
export function WalletProvider({children}:{children:ReactNode}){if(!appId)return <context.Provider value={{configured:false,ready:true,authenticated:false,login:()=>{},logout:async()=>{},getToken:async()=>null,send:missing}}>{children}</context.Provider>;return <PrivyProvider appId={appId} config={{loginMethods:['email'],appearance:{theme:'light',accentColor:'#426b9d',logo:'/favicon.svg'},defaultChain:arcTestnet,supportedChains:[arcTestnet],embeddedWallets:{ethereum:{createOnLogin:'all-users'}}}}><Connected>{children}</Connected></PrivyProvider>;}
export function useWallet(){return useContext(context);}
export async function allowance(wallet:Address,asset:Address,spender:Address){return rpc.readContract({address:asset,abi:erc20Abi,functionName:'allowance',args:[wallet,spender]});}
export function approvalData(spender:Address,amount:bigint){return encodeFunctionData({abi:erc20Abi,functionName:'approve',args:[spender,amount]});}
export async function estimateGasCost(wallet:Address,transactions:{to:Address;data:Hex;fallbackGas?:bigint}[]){const price=await rpc.getGasPrice();let gas=0n,estimated=false;for(const t of transactions){try{gas+=await rpc.estimateGas({account:wallet,to:t.to,data:t.data});}catch(error){if(!t.fallbackGas)throw error;gas+=t.fallbackGas;estimated=true;}}return {amount:gas*price*12n/10n,approximate:estimated,text:formatUnits(gas*price*12n/10n,18)};}
